### ISSUE TITLE
I can't connect to Hive(Mapr-fs) via JdbcSourceConnector

### ISSUE THREAD

**Issue by jv-optum** [confluentinc/kafka-connect-jdbc#1019]
I am trying to move data from mapr-fs to kafka. I have Hive over maprfs and I can connect to it outside of kafka-connect with hive-jdbc jars. But with the same jars copied into kafka-connect jdbc folder, I can't not connect to the Hive. Is there something I need to be doing?

**Comment by OneCricketeer** [comment]
There is no dialect for Hive in this project, so I'm not sure this will work.

Hive has its own Kafka handler that can be installed

**Comment by niaomingjian** [comment]
I placed hive-jdbc driver in kafka-connect jdbc folder and wanted to move data for hive to kafka, then got the following error.

```
[2022-05-31 10:56:35,042] INFO Attempting to open connection #1 to Generic (io.confluent.connect.jdbc.util.CachedConnectionProvider)
[2022-05-31 10:56:35,363] WARN Request to set autoCommit to false; Hive does not support autoCommit=false. (org.apache.hive.jdbc.HiveConnection)
[2022-05-31 10:56:35,790] INFO Begin using SQL query: select * from xxx) (io.confluent.connect.jdbc.source.TableQuerier)
[2022-05-31 10:56:36,218] ERROR Non-transient SQL exception while running query for table: TimestampTableQuerier{table=null, query='select * from xxx)', topicPrefix='test', timestampColumns=[]} (io.confluent.connect.jdbc.source.JdbcSourceTask)
java.sql.SQLFeatureNotSupportedException: Method not supported
at org.apache.hive.jdbc.HiveResultSetMetaData.getCatalogName(HiveResultSetMetaData.java:46)
at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.describeColumn(GenericDatabaseDialect.java:735)
```

In [org.apache.hive.jdbc.HiveResultSetMetaData](https://github.com/apache/hive/blob/master/jdbc/src/java/org/apache/hive/jdbc/HiveResultSetMetaData.java#L71), many methods are not supported.
```
    @Override
    public String getCatalogName(final int column) throws SQLException {
        throw new SQLFeatureNotSupportedException("Method not supported");
    }

    @Override
    public String getSchemaName(final int column) throws SQLException {
        throw new SQLFeatureNotSupportedException("Method not supported");
    }
    
    @Override
    public String getTableName(final int column) throws SQLException {
        throw new SQLFeatureNotSupportedException("Method not supported");
    }
```
Could kafka-connect-jdbc add support for hive?

@OneCricketeer What Kafka handler do you mean?

**Comment by OneCricketeer** [comment]
@niaomingjian https://github.com/apache/hive/tree/master/kafka-handler
