### ISSUE TITLE
jdbc sink fails after running for a while

### ISSUE THREAD

**Issue by ReasonDuan** [confluentinc/kafka-connect-jdbc#1021]
My task often runs for several hours and then suddenly stops automatically. The creation statement and error message are as follows：

```sql
CREATE SINK CONNECTOR `CrawlerList` WITH(
"connector.class"='io.confluent.connect.jdbc.JdbcSinkConnector',
"table.name.format"='CrawlerListNew',
"connection.password"='******',
"topics"='KSQL_T_CrawlerList_1H',
"task.max"='3',
"key.ignore"='true',
"value.converter.schema.registry.url"='http://10.45.84.65:8081',
"connection.user"='root',
"connection.url"='jdbc:mysql://10.45.46.54:8306/CrawlerList',
"value.converter"='io.confluent.connect.avro.AvroConverter',
"insert.mode"='insert',
"key.converter"='org.apache.kafka.connect.storage.StringConverter',
"pk.mode"='none'
);
```
Error message:
```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:194)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.ConnectException: No fields found using key and value schemas for table: CrawlerListNew
	at io.confluent.connect.jdbc.sink.metadata.FieldsMetadata.extract(FieldsMetadata.java:125)
	at io.confluent.connect.jdbc.sink.metadata.FieldsMetadata.extract(FieldsMetadata.java:62)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:77)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:126)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:65)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:73)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:565)
```

**Comment by ReasonDuan** [comment]
The answer to the problem is that the value is null.
```
[13:31:56.702] offset = 306572, partition = 4, value = null
```
