### ISSUE TITLE
error with postgres array

### ISSUE THREAD

**Issue by pdasgupt** [confluentinc/kafka-connect-jdbc#1060]
Tried testing array support with jdbc sink connector using the latest source code (based on fix for issue #805 

Message sent using kafka_console_producer
{"schema": {"type": "struct","fields": [{"type":"int64","optional":false,"field":"id"}, {"type":"float[]","optional":false,"field":"temp1"}],"optional":false,"name": "temp"},"payload": {"id":100,"temp1":{30.7,31,5}}} EOF

Error seen

[2021-05-14 03:06:50,860] ERROR WorkerSinkTask{id=gradescan-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:187)
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:196)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:122)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:495)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:472)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:198)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.connect.errors.DataException: Converting byte[] to Kafka Connect data failed due to serialization error: 
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:366)
	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$1(WorkerSinkTask.java:495)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:146)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:180)
	... 13 more
Caused by: org.apache.kafka.common.errors.SerializationException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('3' (code 51)): was expecting double-quote to start field name
 at [Source: (byte[])"{"schema": {"type": "struct","fields": [{"type":"int64","optional":false,"field":"id"}, {"type":"float[]","optional":false,"field":"temp1"}],"optional":false,"name": "temp"},"payload": {"id":100,"temp1":{30.7,31,5}}} EOF"; line: 1, column: 206]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('3' (code 51)): was expecting double-quote to start field name
 at [Source: (byte[])"{"schema": {"type": "struct","fields": [{"type":"int64","optional":false,"field":"id"}, {"type":"float[]","optional":false,"field":"temp1"}],"optional":false,"name": "temp"},"payload": {"id":100,"temp1":{30.7,31,5}}} EOF"; line: 1, column: 206]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleOddName(UTF8StreamJsonParser.java:2020)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseName(UTF8StreamJsonParser.java:1671)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextFieldName(UTF8StreamJsonParser.java:1029)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:249)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4254)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2725)
	at org.apache.kafka.connect.json.JsonDeserializer.deserialize(JsonDeserializer.java:64)
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:364)
	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$1(WorkerSinkTask.java:495)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:146)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:180)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:122)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:495)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:472)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:198)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by joshuagrisham** [comment]
Hi,

You are seeing this `JsonParseException` error because the syntax of your array in your message payload is incorrect.  The array values should be wrapped in square brackets instead of curly braces (so like `[1, 2, 3]` instead of `{1, 2, 3}`).

See here for examples: https://www.w3schools.com/JS/js_json_arrays.asp

Hope this helps!

**Comment by pdasgupt** [comment]
> Hi,
> 
> You are seeing this `JsonParseException` error because the syntax of your array in your message payload is incorrect. The array values should be wrapped in square brackets instead of curly braces (so like `[1, 2, 3]` instead of `{1, 2, 3}`).
> 
> See here for examples: https://www.w3schools.com/JS/js_json_arrays.asp
> 
> Hope this helps!

Thank you Joshua for your response. I tried the following with square brackets
{"schema": {"type": "struct","fields": [{"type":"int64","optional":false,"field":"id"}, {"type":"float[]","optional":false,"field":"temp1"}],"optional":false,"name": "temp"},"payload": {"id":100,"temp1":[30.7,31.5]}} EOF

I get the following exception now
Caused by: org.apache.kafka.connect.errors.DataException: Unknown schema type: float[]

Does this mean, I need to define a schema in some other way? Any help in this regard
