### ISSUE TITLE
Invalid value null for configuration transforms.unwrap.type: Not a Transformation

### ISSUE THREAD

**Issue by louteq** [confluentinc/kafka-connect-jdbc#1064]
my  configure like this:
cat /opt/confluent/etc/kafka/mysource.properties
name=mysql-source
connector.class=io.debezium.connector.mysql.MySqlConnector
tasks.max=1
database.hostname=192.168.xx.xx
database.port=3307
database.user=xxx
database.password=xxxx
database.server.id=3232236
database.server.name=dbserver1
database.whitelist=test
database.history.kafka.bootstrap.servers=localhost:9092
database.history.kafka.topic=account_topic
include.schema.changes=true

cat /opt/confluent/etc/kafka/mysink.properties
name=mysql-sink
connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
tasks.max=1
connection.url=jdbc:mysql://192.168.xx.xx:3306/test?user=xxx&password=xxx
topics=dbserver1.test.students
auto.create=true
delete.enabled=true
insert.mode=upsert
pk.fields=id
pk.mode=record_key
table.name.format=students
transforms=unwrap
transforms.unwrap.type=io.debezium.transforms.UnwrapFromEnvelope

when  I run:
 /opt/confluent/bin/connect-standalone /opt/confluent/etc/kafka/connect-standalone.properties /opt/confluent/etc/kafka/mysource.properties /opt/confluent/etc/kafka/mysink.properties > /tmp/debezium.running.log 

it failed with those error:

[2021-05-17 16:55:24,167] ERROR Failed to create job for /opt/confluent/etc/kafka/mysink.properties (org.apache.kafka.connect.cli.ConnectStandalone:110)
[2021-05-17 16:55:24,168] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:121)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid and contains the following 2 error(s):
Invalid value io.debezium.transforms.UnwrapFromEnvelope for configuration transforms.unwrap.type: Class io.debezium.transforms.UnwrapFromEnvelope could not be found.
Invalid value null for configuration transforms.unwrap.type: Not a Transformation
You can also find the above list of errors at the endpoint `/connector-plugins/{connectorType}/config/validate`
        at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:115)
        at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:99)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:118)
Caused by: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid and contains the following 2 error(s):
Invalid value io.debezium.transforms.UnwrapFromEnvelope for configuration transforms.unwrap.type: Class io.debezium.transforms.UnwrapFromEnvelope could not be found.
Invalid value null for configuration transforms.unwrap.type: Not a Transformation
You can also find the above list of errors at the endpoint `/connector-plugins/{connectorType}/config/validate`
        at org.apache.kafka.connect.runtime.AbstractHerder.maybeAddConfigErrors(AbstractHerder.java:586)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:194)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:115)

**Comment by louteq** [comment]
version is : confluent-community-5.5.4-2.12
mysql-connector-java-5.1.49.jar

**Comment by OneCricketeer** [comment]
Remove these. They don't come with the JDBC source or Confluent Platform, and are only meant to be used with Debezium source

```
transforms=unwrap
transforms.unwrap.type=io.debezium.transforms.UnwrapFromEnvelope
```
