### ISSUE TITLE
Not support batch upsert operations

### ISSUE THREAD

**Issue by cobolbaby** [confluentinc/kafka-connect-jdbc#1081]
```
"connection.url": "jdbc:postgresql://???:???/????ApplicationName=cdc_sync&reWriteBatchedInserts=true",
```

```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:571)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:329)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.ConnectException: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "fis"."cto_change_order_log" ("id","seq","po","rno","description","input_signal","output_signal","message","cdt","udt") VALUES (2696109,732762,'0033888845','00001','<root><T203>华润置地有限公司</T203><T204>F47100887</T204><T205>广东省深圳市龙岗区坂田街道杨美社区华美街2号</T205><T206>赵春旺 0755-33353633 / 13168768791</T206><T207>厂房308</T207><T208></T208><T209>深圳  310000</T209><T210></T210><T211>CN</T211><T212></T212><T213></T213><T214></T214><T215>China</T215><T216>深圳</T216><T217></T217><T218>310000</T218><T160>50</T160></root>','NC','','','2021-06-08 14:40:21.083+00','2021-06-08 14:40:21.083+00'),(2696109,732762,'0033888845','00001','<root><T203>华润置地有限公司</T203><T204>F47100887</T204><T205>广东省深圳市龙岗区坂田街道杨美社区华美街2号</T205><T206>赵春旺 0755-33353633 / 13168768791</T206><T207>厂房308</T207><T208></T208><T209>深圳  310000</T209><T210></T210><T211>CN</T211><T212></T212><T213></T213><T214></T214><T215>China</T215><T216>深圳</T216><T217></T217><T218>310000</T218><T160>50</T160></root>','NC','NC','00001,1,OK','2021-06-08 14:40:21.083+00','2021-06-08 14:40:22.583+00'),(2696115,732767,'0033888277','000000','Ship Release from EDI 850','SR','HA','000000,1,OK','2021-06-08 14:46:01.077+00','2021-06-08 14:46:01.077+00'),(2696117,0,'0033888810','RAW','','HR','IA','Realse from Dn Dwonload','2021-06-08 14:47:34.427+00','2021-06-08 14:47:34.427+00'),(2696118,0,'0033888810','RAW','','SR','IA','Realse from Dn Dwonload','2021-06-08 14:47:34.427+00','2021-06-08 14:47:34.427+00'),(2696119,0,'0033888810','RAW','','ZD','IA','Realse from Dn Dwonload','2021-06-08 14:47:34.427+00','2021-06-08 14:47:34.427+00'),(2696120,0,'0033888810','RAW','','HR','IA','Realse from Dn Dwonload','2021-06-08 14:47:37.4+00','2021-06-08 14:47:37.4+00'),(2696124,732770,'6902961400','000000','Ship Release from EDI 850','SR','HA','000000,1,OK','2021-06-08 14:47:31.263+00','2021-06-08 14:47:31.263+00'),(2696126,0,'0033888811','RAW','','SR','IA','Realse from Dn Dwonload','2021-06-08 14:47:42.517+00','2021-06-08 14:47:42.517+00'),(2696127,0,'0033888811','RAW','','ZD','IA','Realse from Dn Dwonload','2021-06-08 14:47:42.517+00','2021-06-08 14:47:42.517+00'),(2696130,0,'0033888844','RAW','','SR','IA','Realse from Dn Dwonload','2021-06-08 14:47:53.893+00','2021-06-08 14:47:53.893+00'),(2696133,0,'0033888844','RAW','','SR','IA','Realse from Dn Dwonload','2021-06-08 14:47:56.943+00','2021-06-08 14:47:56.943+00'),(2696140,0,'0033888847','RAW','','SR','IA','Realse from Dn Dwonload','2021-06-08 14:48:03.79+00','2021-06-08 14:48:03.79+00'),(2696141,0,'0033888847','RAW','','ZD','IA','Realse from Dn Dwonload','2021-06-08 14:48:03.79+00','2021-06-08 14:48:03.79+00'),(2696151,0,'0033888842','RAW','','ZD','IA','Realse from Dn Dwonload','2021-06-08 14:48:18.677+00','2021-06-08 14:48:18.677+00'),(2696153,0,'0033888842','RAW','','SR','IA','Realse from Dn Dwonload','2021-06-08 14:48:21.687+00','2021-06-08 14:48:21.687+00'),(2696154,0,'0033888842','RAW','','ZD','IA','Realse from Dn Dwonload','2021-06-08 14:48:21.687+00','2021-06-08 14:48:21.687+00'),(2696155,0,'0033888842','RAW','','HR','IA','Realse from Dn Dwonload','2021-06-08 14:48:24.66+00','2021-06-08 14:48:24.66+00'),(2696161,732774,'0033888842','000000','Ship Release from EDI 850','SR','HA','000000,1,OK','2021-06-08 14:48:15.117+00','2021-06-08 14:48:15.117+00'),(2696162,0,'0033888845','RAW','','HR','IA','Realse from Dn Dwonload','2021-06-08 14:48:31.727+00','2021-06-08 14:48:31.727+00'),(2696163,0,'0033888845','RAW','','SR','IA','Realse from Dn Dwonload','2021-06-08 14:48:31.727+00','2021-06-08 14:48:31.727+00'),(2696164,0,'0033888845','RAW','','ZD','IA','Realse from Dn Dwonload','2021-06-08 14:48:31.727+00','2021-06-08 14:48:31.727+00'),(2696165,0,'0033888845','RAW','','HR','IA','Realse from Dn Dwonload','2021-06-08 14:48:34.747+00','2021-06-08 14:48:34.747+00'),(2696169,0,'0033888845','RAW','','SR','IA','Realse from Dn Dwonload','2021-06-08 14:48:37.76+00','2021-06-08 14:48:37.76+00'),(2696170,0,'0033888845','RAW','','ZD','IA','Realse from Dn Dwonload','2021-06-08 14:48:37.76+00','2021-06-08 14:48:37.76+00'),(2696171,0,'0033888845','RAW','','HR','IA','Realse from Dn Dwonload','2021-06-08 14:48:40.81+00','2021-06-08 14:48:40.81+00'),(2696174,732775,'0033888845','000000','Ship Release from EDI 850','SR','HA','000000,1,OK','2021-06-08 14:48:27.807+00','2021-06-08 14:48:27.807+00'),(2696176,0,'0033888846','RAW','','SR','IA','Realse from Dn Dwonload','2021-06-08 14:48:47.723+00','2021-06-08 14:48:47.723+00'),(2696177,0,'0033888846','RAW','','ZD','IA','Realse from Dn Dwonload','2021-06-08 14:48:47.723+00','2021-06-08 14:48:47.723+00'),(2696179,0,'0033888846','RAW','','SR','IA','Realse from Dn Dwonload','2021-06-08 14:48:50.723+00','2021-06-08 14:48:50.723+00'),(2696180,0,'0033888846','RAW','','ZD','IA','Realse from Dn Dwonload','2021-06-08 14:48:50.723+00','2021-06-08 14:48:50.723+00'),(2696181,0,'0033888846','RAW','','HR','IA','Realse from Dn Dwonload','2021-06-08 14:48:53.797+00','2021-06-08 14:48:53.797+00') ON CONFLICT ("id") DO UPDATE SET "seq"=EXCLUDED."seq","po"=EXCLUDED."po","rno"=EXCLUDED."rno","description"=EXCLUDED."description","input_signal"=EXCLUDED."input_signal","output_signal"=EXCLUDED."output_signal","message"=EXCLUDED."message","cdt"=EXCLUDED."cdt","udt"=EXCLUDED."udt" was aborted: ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time
  Hint: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.  Call getNextException to see other errors in the batch.
org.postgresql.util.PSQLException: ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time
  Hint: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
org.postgresql.util.PSQLException: ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time
  Hint: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:89)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:549)
	... 10 more
Caused by: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "fis"."cto_change_order_log" ("id","seq","po","rno","description","input_signal","output_signal","message","cdt","udt") VALUES (2696109,732762,'0033888845','00001','<root><T203>华润置地有限公司</T203><T204>F47100887</T204><T205>广东省深圳市龙岗区坂田街道杨美社区华美街2号</T205><T206>赵春旺 0755-33353633 / 13168768791</T206><T207>厂房308</T207><T208></T208><T209>深圳  310000</T209><T210></T210><T211>CN</T211><T212></T212><T213></T213><T214></T214><T215>China</T215><T216>深圳</T216><T217></T217><T218>310000</T218><T160>50</T160></root>','NC','','','2021-06-08 14:40:21.083+00','2021-06-08 14:40:21.083+00'),(2696109,732762,'0033888845','00001','<root><T203>华润置地有限公司</T203><T204>F47100887</T204><T205>广东省深圳市龙岗区坂田街道杨美社区华美街2号</T205><T206>赵春旺 0755-33353633 / 13168768791</T206><T207>厂房308</T207><T208></T208><T209>深圳  310000</T209><T210></T210><T211>CN</T211><T212></T212><T213></T213><T214></T214><T215>China</T215><T216>深圳</T216><T217></T217><T218>310000</T218><T160>50</T160></root>','NC','NC','00001,1,OK','2021-06-08 14:40:21.083+00','2021-06-08 14:40:22.583+00'),(2696115,732767,'0033888277','000000','Ship Release from EDI 850','SR','HA','000000,1,OK','2021-06-08 14:46:01.077+00','2021-06-08 14:46:01.077+00'),(2696117,0,'0033888810','RAW','','HR','IA','Realse from Dn Dwonload','2021-06-08 14:47:34.427+00','2021-06-08 14:47:34.427+00'),(2696118,0,'0033888810','RAW','','SR','IA','Realse from Dn Dwonload','2021-06-08 14:47:34.427+00','2021-06-08 14:47:34.427+00'),(2696119,0,'0033888810','RAW','','ZD','IA','Realse from Dn Dwonload','2021-06-08 14:47:34.427+00','2021-06-08 14:47:34.427+00'),(2696120,0,'0033888810','RAW','','HR','IA','Realse from Dn Dwonload','2021-06-08 14:47:37.4+00','2021-06-08 14:47:37.4+00'),(2696124,732770,'6902961400','000000','Ship Release from EDI 850','SR','HA','000000,1,OK','2021-06-08 14:47:31.263+00','2021-06-08 14:47:31.263+00'),(2696126,0,'0033888811','RAW','','SR','IA','Realse from Dn Dwonload','2021-06-08 14:47:42.517+00','2021-06-08 14:47:42.517+00'),(2696127,0,'0033888811','RAW','','ZD','IA','Realse from Dn Dwonload','2021-06-08 14:47:42.517+00','2021-06-08 14:47:42.517+00'),(2696130,0,'0033888844','RAW','','SR','IA','Realse from Dn Dwonload','2021-06-08 14:47:53.893+00','2021-06-08 14:47:53.893+00'),(2696133,0,'0033888844','RAW','','SR','IA','Realse from Dn Dwonload','2021-06-08 14:47:56.943+00','2021-06-08 14:47:56.943+00'),(2696140,0,'0033888847','RAW','','SR','IA','Realse from Dn Dwonload','2021-06-08 14:48:03.79+00','2021-06-08 14:48:03.79+00'),(2696141,0,'0033888847','RAW','','ZD','IA','Realse from Dn Dwonload','2021-06-08 14:48:03.79+00','2021-06-08 14:48:03.79+00'),(2696151,0,'0033888842','RAW','','ZD','IA','Realse from Dn Dwonload','2021-06-08 14:48:18.677+00','2021-06-08 14:48:18.677+00'),(2696153,0,'0033888842','RAW','','SR','IA','Realse from Dn Dwonload','2021-06-08 14:48:21.687+00','2021-06-08 14:48:21.687+00'),(2696154,0,'0033888842','RAW','','ZD','IA','Realse from Dn Dwonload','2021-06-08 14:48:21.687+00','2021-06-08 14:48:21.687+00'),(2696155,0,'0033888842','RAW','','HR','IA','Realse from Dn Dwonload','2021-06-08 14:48:24.66+00','2021-06-08 14:48:24.66+00'),(2696161,732774,'0033888842','000000','Ship Release from EDI 850','SR','HA','000000,1,OK','2021-06-08 14:48:15.117+00','2021-06-08 14:48:15.117+00'),(2696162,0,'0033888845','RAW','','HR','IA','Realse from Dn Dwonload','2021-06-08 14:48:31.727+00','2021-06-08 14:48:31.727+00'),(2696163,0,'0033888845','RAW','','SR','IA','Realse from Dn Dwonload','2021-06-08 14:48:31.727+00','2021-06-08 14:48:31.727+00'),(2696164,0,'0033888845','RAW','','ZD','IA','Realse from Dn Dwonload','2021-06-08 14:48:31.727+00','2021-06-08 14:48:31.727+00'),(2696165,0,'0033888845','RAW','','HR','IA','Realse from Dn Dwonload','2021-06-08 14:48:34.747+00','2021-06-08 14:48:34.747+00'),(2696169,0,'0033888845','RAW','','SR','IA','Realse from Dn Dwonload','2021-06-08 14:48:37.76+00','2021-06-08 14:48:37.76+00'),(2696170,0,'0033888845','RAW','','ZD','IA','Realse from Dn Dwonload','2021-06-08 14:48:37.76+00','2021-06-08 14:48:37.76+00'),(2696171,0,'0033888845','RAW','','HR','IA','Realse from Dn Dwonload','2021-06-08 14:48:40.81+00','2021-06-08 14:48:40.81+00'),(2696174,732775,'0033888845','000000','Ship Release from EDI 850','SR','HA','000000,1,OK','2021-06-08 14:48:27.807+00','2021-06-08 14:48:27.807+00'),(2696176,0,'0033888846','RAW','','SR','IA','Realse from Dn Dwonload','2021-06-08 14:48:47.723+00','2021-06-08 14:48:47.723+00'),(2696177,0,'0033888846','RAW','','ZD','IA','Realse from Dn Dwonload','2021-06-08 14:48:47.723+00','2021-06-08 14:48:47.723+00'),(2696179,0,'0033888846','RAW','','SR','IA','Realse from Dn Dwonload','2021-06-08 14:48:50.723+00','2021-06-08 14:48:50.723+00'),(2696180,0,'0033888846','RAW','','ZD','IA','Realse from Dn Dwonload','2021-06-08 14:48:50.723+00','2021-06-08 14:48:50.723+00'),(2696181,0,'0033888846','RAW','','HR','IA','Realse from Dn Dwonload','2021-06-08 14:48:53.797+00','2021-06-08 14:48:53.797+00') ON CONFLICT ("id") DO UPDATE SET "seq"=EXCLUDED."seq","po"=EXCLUDED."po","rno"=EXCLUDED."rno","description"=EXCLUDED."description","input_signal"=EXCLUDED."input_signal","output_signal"=EXCLUDED."output_signal","message"=EXCLUDED."message","cdt"=EXCLUDED."cdt","udt"=EXCLUDED."udt" was aborted: ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time
  Hint: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.  Call getNextException to see other errors in the batch.
org.postgresql.util.PSQLException: ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time
  Hint: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
org.postgresql.util.PSQLException: ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time
  Hint: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:86)
	... 11 more
```

**Comment by gaurav7261** [comment]
@rhauch   I have the solution for same, same issue we are getting in debezium jdbc sink, can you confirm if same solution can be apply here, then after I can start creating PR for it here as well.

**Comment by gaurav7261** [comment]
@sangeet259 can you please check above approach
