### ISSUE TITLE
Kafka connect sink JDBC - Postgres - SQLException - there is no unique or exclusion constraint matching the ON CONFLICT specification

### ISSUE THREAD

**Issue by dungnt081191** [confluentinc/kafka-connect-jdbc#1127]
my work flow is : Postgress 12 --> Debezium connect source --> Kafka --> Connect sink jdbc --> Postgres 12

Table in DB source is already set primary key. Could you take a look for me.

My db table have key Id with type bigint

My source connector config:
```
name=connector
connector.class=io.debezium.connector.postgresql.PostgresConnector
tasks.max=1
slot.name=test12
plugin.name=pgoutput
database.hostname=10.10.1.1
database.port=5432 
database.user=postgres 
database.password=123123123
database.dbname=DBsource 
database.server.name=10.10.1.1
table.include.list=public.TestTable
slot.drop.on.stop=true
key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://localhost:8081
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=http://localhost:8081
value.converter.schemas.enable=true
key.converter.schemas.enable=true
internal.key.converter=io.confluent.connect.avro.AvroConverter
internal.value.converter=io.confluent.connect.avro.AvroConverter
transforms=unwrap
transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState
decimal.handling.mode=double
time.precision.mode=connect
```
--> after create source connector debezium, data record go into kafka topic ( I confirm is correct number of record )
Then add sink connector use confluent kafka connect sink jdbc
Here is sink connector setting :
```
{
    "name": "JdbcSinkConnector123",
    "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
    "connection.password": "123123123",
    "topics": "10.10.1.1.public.TestTable",
    "delete.enabled": "false",
    "connection.user": "postgres",
    "connection.url": "jdbc:postgresql://10.10.1.1:5432/DBdest",
    "insert.mode": "upsert",
    "transforms": "renameTopic,tombstoneHandlerExample,TimestampConverter",
    "transforms.renameTopic.type": "org.apache.kafka.connect.transforms.RegexRouter",
    "transforms.renameTopic.regex": "10.10.1.1.public.TestTable",
    "transforms.renameTopic.replacement": "TestTable",
    "transforms.tombstoneHandlerExample.type": "io.confluent.connect.transforms.TombstoneHandler",
    "key.converter": "io.confluent.connect.avro.AvroConverter",
    "key.converter.schemas.enable": "true",
    "key.converter.schema.registry.url": "http://localhost:8081",
    "value.converter": "io.confluent.connect.avro.AvroConverter",
    "value.converter.schemas.enable": "true",
    "value.converter.schema.registry.url": "http://localhost:8081",
    "auto.evolve": "true",
    "pk.fields": "Id",
    "pk.mode": "record_value",
    "transforms.TimestampConverter.type": "org.apache.kafka.connect.transforms.TimestampConverter$Value",
    "transforms.TimestampConverter.target.type": "Timestamp",
    "transforms.TimestampConverter.field": "CreateDate,UpdateDate"
}
```
After create sink connector, exception on sink connect here :

```
18:42:51.917+00'::timestamp,'2018-11-22 11:34:19.387+00'::timestamp,'2020-12-28 08:59:39.95+00'::timestamp,'2020-12-28 08:59:39.95+00'::timestamp) ON CONFLICT ("Id") DO UPDATE SET "OrganCode"=EXCLUDED."OrganCode","Ticker"=EXCLUDED."Ticker","ComGroupCode"=EXCLUDED."ComGroupCode","AdjustedDate"=EXCLUDED."AdjustedDate","RateAdjusted"=EXCLUDED."RateAdjusted","Status"=EXCLUDED."Status","CreateDate"=EXCLUDED."CreateDate","UpdateDate"=EXCLUDED."UpdateDate" was aborted: ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification  Call getNextException to see other errors in the batch.
org.postgresql.util.PSQLException: ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification
org.postgresql.util.PSQLException: ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:122)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
	... 10 more
Caused by: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "TestTable" ("Id","OrganCode","Ticker","ComGroupCode","AdjustedDate","RateAdjusted","Status","CreateDate","UpdateDate") VALUES (:timestamp) ON CONFLICT ("Id") DO UPDATE SET "OrganCode"=EXCLUDED."OrganCode","Ticker"=EXCLUDED."Ticker","ComGroupCode"=EXCLUDED."ComGroupCode","AdjustedDate"=EXCLUDED."AdjustedDate","RateAdjusted"=EXCLUDED."RateAdjusted","Status"=EXCLUDED."Status","CreateDate"=EXCLUDED."CreateDate","UpdateDate"=EXCLUDED."UpdateDate" was aborted: ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification  Call getNextException to see other errors in the batch.
org.postgresql.util.PSQLException: ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification
org.postgresql.util.PSQLException: ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification
```
Could you take a look for me ?

**Comment by dungnt081191** [comment]
@nvladimiroff  what do you think about this exception
