### ISSUE TITLE
Timestamp Columns are not writing using JdbcSinkConnector

### ISSUE THREAD

**Issue by salemn** [confluentinc/kafka-connect-jdbc#115]
Hi Everybody,

I'm using the JdbcSinkConnector to read from Kafka and push to postgres database. I'm facing a problem with the timestamp columns.
Each time, i try to add a timestamp without time zone column in the JdbcSourceConnector configuration, it throws an exception:
```
[2016-08-24 15:11:43,633] ERROR Task jdbc-sink-UNIQUE-i-request-1 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask:390)
java.lang.ClassCastException: java.util.Date cannot be cast to java.lang.Long
	at io.confluent.connect.jdbc.sink.PreparedStatementBinder.bindField(PreparedStatementBinder.java:121)
	at io.confluent.connect.jdbc.sink.PreparedStatementBinder.bindField(PreparedStatementBinder.java:103)
	at io.confluent.connect.jdbc.sink.PreparedStatementBinder.bindRecord(PreparedStatementBinder.java:96)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:95)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:64)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:57)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:370)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:227)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:142)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-08-24 15:11:43,650] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerSinkTask:391)
[2016-08-24 15:11:43,650] INFO WorkerSinkTask{id=jdbc-sink-UNIQUE-i-request-1} Committing offsets (org.apache.kafka.connect.runtime.WorkerSinkTask:244)
[2016-08-24 15:11:43,653] ERROR Task jdbc-sink-UNIQUE-i-request-1 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:142)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:392)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:227)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:142)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

I checked the schema generated, and seems that the column type is converted to long during the serialization
{"name":"updated","type":["null",{"type":"long","connect.version":1,"connect.name":"org.apache.kafka.connect.data.Timestamp"}]}
which sounds logic from what read in https://github.com/confluentinc/kafka-connect-jdbc/issues/64

I configured the SinkConnector to create table automatically auto.create=true, and in the created table the column type is bigint.
Is there any why to make the SinkConnector create the column in the database target as a timestamp without time zone so that we can push the column's value into it?

**Comment by willyhoang** [comment]
Hey @salemn,

I was having the same issue earlier. It looks like the latest kafka-connect-jdbc commit resolves the the issue. I believe it was fixed by adding in the logical type converters to the PreparedStatementBinder. See https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/sink/PreparedStatementBinder.java#L165

I do have the same question though of whether it's possible to create the column with timestamp type instead of big int.

**Comment by shikhar** [comment]
@willyhoang is right, that PR adds basic support. @salemn can you reopen if you still see errors?

WRT using logical types like timestamp in the CREATE/ALTER DDL and when binding, I noted those as future improvements on that PR. We would like to incorporate that before a release.

**Comment by salemn** [comment]
Thank you for your answer @willyhoang. indeed, with the commit you mentioned, date insertion as a bigint seems to be working fine.

@shikhar thanks for your answering, i'll be following those future improvement closely :)

**Comment by chaitras** [comment]
I have a similar issue, I'm using the JdbcSinkConnector to read from Kafka and push to oracle database. Timestamp columns are going in as number in oracle.
VirtualBox:~/confluent/confluent-3.2.0$ ./bin/kafka-avro-console-producer --broker-list localhost:9092 --topic MYTS_TT --property value.schema='{"type":"record","name":"mytime","fields":[{"name":"MY_TS","type":{"type":"long","connect.version":1,"connect.name":"org.apache.kafka.connect.data.Timestamp"}}]}'
{"MY_TS":1489148657000002}


In kafka connect I see>
[2017-03-20 16:56:37,889] INFO Creating table:MYTS_TT with SQL: CREATE TABLE "MYTS_TT" (
"MY_TS" NUMBER(19,0) NOT NULL) (io.confluent.connect.jdbc.sink.DbStructure:88)

How can I get the timestamp into my oracle db from kafkaconnect_

**Comment by edmondo1984** [comment]
Why is this issue seems to relate to JdbcSinkConnector while it refers to JdbcSourceConnector?
