### ISSUE TITLE
I am getting this error while testing

### ISSUE THREAD

**Issue by kkrgwbj** [confluentinc/kafka-connect-jdbc#1173]
`Caused by: org.apache.kafka.connect.errors.ConnectException: Sink connector 'test-sink' is configured with 'delete.enabled=false' and 'pk.mode=none' and therefore requires records with a non-null Struct value and non-null Struct schema, but found record at (topic='quickstart-events',partition=0,offset=0,timestamp=1645938414713) with a Long value and null value schema.
        at io.confluent.connect.jdbc.sink.RecordValidator.lambda$requiresValue$2(RecordValidator.java:86)
        at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:82)
        at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:74)
        at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:84)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)`

connect-stand.properties

![image](https://user-images.githubusercontent.com/6836934/155891573-8a3d7fec-70ed-4e63-918e-fd462e5fc1d0.png)

sink.properteis

![image](https://user-images.githubusercontent.com/6836934/155891589-4895f8df-95f8-4129-9b4a-fa84de748b03.png)

some one help to me ? thanks...

**Comment by yansheng105** [comment]
key.converter.shcemas.enable  and value.converter.shcemas.enable in connect-stand.properties  should be true.
You should add pk.mode attribute to sink.properties, and its value should be record_key
