### ISSUE TITLE
JDBC (MySQL) Sink Connector fails after adding new column to the table

### ISSUE THREAD

**Issue by pmalon** [confluentinc/kafka-connect-jdbc#1193]
Scenario:
1. Sink Connector is running
2. DDL is executed that adds new columns to the table
3. Messages with new fields are written to the Kafka Topic (new schema version is registered)
4. Connector fails totally with the error:
```
  | 2022-05-18T21:18:58.000Z | [Worker-0055605ac5e2cc929] [2022-05-18 21:18:58,559] ERROR [dev-reporting-jdbc-sink-purchase-item\|task-0] Error encountered in task dev-reporting-jdbc-sink-purchase-item-0. Executing stage 'TASK_PUT' with class 'org.apache.kafka.connect.sink.SinkTask', where consumed record is {topic='reporting-purchase-item', partition=3, offset=196, timestamp=1652908735000, timestampType=CreateTime}. (org.apache.kafka.connect.runtime.errors.LogReporter:66)
  | 2022-05-18T21:18:58.000Z | [Worker-0055605ac5e2cc929] io.confluent.connect.jdbc.sink.TableAlterOrCreateException: Table "purchase_item" is missing fields ([SinkRecordField{schema=Schema{BOOLEAN}, name='void', isPrimaryKey=false}, SinkRecordField{schema=Schema{BOOLEAN}, name='supervisor_deleted', isPrimaryKey=false}]) and auto-evolution is disabled
  | 2022-05-18T21:18:58.000Z | [Worker-0055605ac5e2cc929] at io.confluent.connect.jdbc.sink.DbStructure.amendIfNecessary(DbStructure.java:193)
  | 2022-05-18T21:18:58.000Z | [Worker-0055605ac5e2cc929] at io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:83)
  | 2022-05-18T21:18:58.000Z | [Worker-0055605ac5e2cc929] at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:123)
  | 2022-05-18T21:18:58.000Z | [Worker-0055605ac5e2cc929] at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:74)
  | 2022-05-18T21:18:58.000Z | [Worker-0055605ac5e2cc929] at io.confluent.connect.jdbc.sink.JdbcSinkTask.unrollAndRetry(JdbcSinkTask.java:133)
  | 2022-05-18T21:18:58.000Z | [Worker-0055605ac5e2cc929] at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:87)
```

Connector configuration:
```
auto.evolve=false
auto.create=false
batch.size=1000
connection.attempts=60
connection.backoff.ms=30000
connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
connection.password=XXX
connection.user=YYY
connection.url=jdbc:mysql://db-host:3306/reporting
errors.log.enable=true
errors.log.include.messages=true
insert.mode=upsert
key.converter=org.apache.kafka.connect.storage.StringConverter
pk.mode=record_value
pk.fields=id
table.name.format=purchase_item
tasks.max=1
topics=reporting-purchase-item
value.converter.avroRecordType=GENERIC_RECORD
value.converter.schemaAutoRegistrationEnabled=true
value.converter.registry.name=some-registry
value.converter.region=eu-west-1
value.converter=com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter
```

**Comment by OneCricketeer** [comment]
> `auto-evolution is disabled`

Have you tried setting `auto.evolve=true` to allow for the connector to update the table itself rather than you running DDL outside of it?

**Comment by pmalon** [comment]
@OneCricketeer that's not a solution - I do not wish to have "connector" driven DDLs

**Comment by OneCricketeer** [comment]
The show your table schema and Kafka record in the question itself, please.

According to the logs, your table is missing `supervisor_deleted` boolean field

**Comment by khasanjon-dev** [comment]
In my experience, using schema changes is not correct
I don't know exactly how the jdbc sink connector detects schema changes, but the pgoutput plugin cannot listen to ddl changes for postgres and does not send them to the kafka topic
My advice is to make the schema changes custom
