### ISSUE TITLE
JDBC source connector with bulk mode giving error as tableName is not a valid field name (io.confluent.connect.jdbc.source.JdbcSourceTask:437)

### ISSUE THREAD

**Issue by krishnendudas1979** [confluentinc/kafka-connect-jdbc#1200]
Hi 
I have to configure the JDBC source connector in bulk mode. Below is the connector configuration

name=<name_1>
connector.class=io.confluent.connect.jdbc.CmJdbcSourceConnector
tasks.max=1    
connection.url=<url>
connection.user=<user id>
connection.password=<password>
mode=bulk
topic.prefix=<topic_prefix>
table.whitelist=<table name>
poll.interval.ms=10000
schema.pattern=<schema name>
validate.non.null=false
batch.max.rows=1000
numeric.mapping=best_fit

When I started the connector in standalone mode, got the below error as --

`[2022-06-08 08:47:07,673] INFO Closing resources for JDBC source task (io.confluent.connect.jdbc.source.JdbcSourceTask:333)
[2022-06-08 08:47:07,673] INFO Closing connection #1 to Oracle (io.confluent.connect.jdbc.util.CachedConnectionProvider:105)
[2022-06-08 08:47:07,676] ERROR JDBC_CM_SOURCE_CONNECTOR | CRITICAL | 8166 | Taking is getting closed. | **tableName is not a valid field name (io.confluent.connect.jdbc.source.JdbcSourceTask:437)**
[2022-06-08 08:47:07,676] ERROR CRITICAL | 8166 | Taking is getting closed. (auditLogger:440)
[2022-06-08 08:47:07,676] INFO WorkerSourceTask{id=FT-Topic-pullcm_cmporder-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:488)
[2022-06-08 08:47:07,676] INFO WorkerSourceTask{id=FT-Topic-pullcm_cmporder-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:505)
[2022-06-08 08:47:07,677] ERROR WorkerSourceTask{id=FT-Topic-pullcm_cmporder-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:191)
org.apache.kafka.connect.errors.DataException: tableName is not a valid field name
        at org.apache.kafka.connect.data.Struct.lookupField(Struct.java:254)
        at org.apache.kafka.connect.data.Struct.put(Struct.java:202)
        at io.confluent.connect.jdbc.source.BulkTableQuerier.extractRecord(BulkTableQuerier.java:87)
        at io.confluent.connect.jdbc.source.JdbcSourceTask.poll(JdbcSourceTask.java:389)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:291)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:248)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:189)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:239)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
[2022-06-08 08:47:07,679] ERROR WorkerSourceTask{id=FT-Topic-pullcm_cmporder-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:192)
[2022-06-08 08:47:07,679] INFO Stopping JDBC source task (io.confluent.connect.jdbc.source.JdbcSourceTask:326)
`

is there any mistake in the configuration or something else?

**Comment by krishnendudas1979** [comment]
The issue is solved.
