### ISSUE TITLE
question about db structure cache

### ISSUE THREAD

**Issue by cstmgl** [confluentinc/kafka-connect-jdbc#1220]
Hi all,
I'm having a weird error, that I know is not caused by the code but I'm very curious how this happens and I don't understand the implementation.
Basically I get a Null Pointer exception in version 10.2.8 (even if the code seems unchanged forever).

```
java.lang.NullPointerException
	at io.confluent.connect.jdbc.sink.DbStructure.amendIfNecessary(DbStructure.java:154)
	at io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:83)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:123)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:74)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:84)
```

The question I don't get is:
Table gets created successfully here:
https://github.com/confluentinc/kafka-connect-jdbc/blob/v10.2.8/src/main/java/io/confluent/connect/jdbc/sink/DbStructure.java#L67

The amendIfNecessary will fail because there is no cache
https://github.com/confluentinc/kafka-connect-jdbc/blob/v10.2.8/src/main/java/io/confluent/connect/jdbc/sink/DbStructure.java#L83

`final TableDefinition tableDefn = tableDefns.get(connection, tableId);`
is null because there is nothing in the tableDefns yet
https://github.com/confluentinc/kafka-connect-jdbc/blob/v10.2.8/src/main/java/io/confluent/connect/jdbc/sink/DbStructure.java#L142

Is it not missing an update on the cache after the create?
https://github.com/confluentinc/kafka-connect-jdbc/blob/v10.2.8/src/main/java/io/confluent/connect/jdbc/sink/DbStructure.java#L67

```
      try {
        create(config, connection, tableId, fieldsMetadata);
        tableDefns.refresh(connection, tableId);
      } catch (SQLException sqle) {
```

Anyway this is strange because I'm sure the code works and I'm using it but based on this error I'm now getting, I don't understand how it works. Because I'm following the execution on my debug and I see the table being created, so it's not in the cache but 
`return amendIfNecessary(config, connection, tableId, fieldsMetadata, config.maxRetries);` always assume the cache to be populated so I'm a bit lost where the update of the cache should be done.

Sorry for the long message, I'm just trying to understand the code

**Comment by cstmgl** [comment]
ok my first question was not so smart... I guess just tired of trying to read other people code.
https://github.com/confluentinc/kafka-connect-jdbc/blob/v10.2.8/src/main/java/io/confluent/connect/jdbc/util/TableDefinitions.java#L61

It's obvious how the cache is built, the part I need to try and understand is why Oracle Dialect is telling me the table does not exist even if he creates it.

**Comment by cstmgl** [comment]
somehow on version 2 of H2 in memory DBs we have a new type that is neither TABLE nor VIEW but BASE TABLE and the table was then not found. Anyway we can't configure it because the types only accept TABLE or VIEW and nothing else.

**Comment by cstmgl** [comment]
> ok my first question was not so smart... I guess just tired of trying to read other people code. https://github.com/confluentinc/kafka-connect-jdbc/blob/v10.2.8/src/main/java/io/confluent/connect/jdbc/util/TableDefinitions.java#L61
> 
> It's obvious how the cache is built, the part I need to try and understand is why Oracle Dialect is telling me the table does not exist even if he creates it.

just for reference the problem was related to the config for the table.types that only allows values VIEW, TABLE and not "null" 
Since in H2 version 2.X they introduced a new type (BASE TABLE) then we can't make it work.
We use H2 just for testing so this is not an issue per-se but it would probably be nice if the Enum would support more values or if somehow we would be able to define null instead of an empty list.

**Comment by cstmgl** [comment]
somehow on version 2 of H2 in memory DBs we have a new type that is neither TABLE nor VIEW but BASE TABLE and the table was then not found. Anyway we can't configure it because the types only accept TABLE or VIEW and nothing else.

just for reference:
https://github.com/h2database/h2database/issues/3213
