### ISSUE TITLE
No suitable driver found (Firebird)

### ISSUE THREAD

**Issue by lukens** [confluentinc/kafka-connect-jdbc#1252]
I'm trying to get a source connector working from a Firebird database.

I've turned on debugging, and it looks like it's loading the relevant jar files from the plugins path:

```
2022-10-18 12:59:36,025 DEBUG Loading plugin urls: [file:/opt/kafka/plugins/jaybird/669bac1f/antlr4-runtime-4.7.2.jar, file:/opt/kafka/plugins/jaybird/669bac1f/connector-api-1.5.jar, file:/opt/kafka/plugins/jaybird/669bac1f/jaybird-4.0.2.java11.jar, file:/opt/kafka/plugins/jaybird/669bac1f/jna-5.5.0.jar] (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader) [main]
```

and is registering the driver:

```
2022-10-18 12:59:36,202 DEBUG Registered java.sql.Driver: org.firebirdsql.jdbc.FBDriver@29f7cefd to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader) [main]
```

but when it tries to connect, I get the "No Suitable Driver Found" error:

```
java.sql.SQLException: No suitable driver found for jdbc:firebirdsql://xxx.xxx.xxx:3050//db/xxx/xxx.gdb
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.getConnection(GenericDatabaseDialect.java:250)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.newConnection(CachedConnectionProvider.java:80)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:52)
	at io.confluent.connect.jdbc.JdbcSourceConnector.start(JdbcSourceConnector.java:94)
	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:184)
	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:209)
	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:348)
	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:331)
	at org.apache.kafka.connect.runtime.WorkerConnector.doRun(WorkerConnector.java:140)
	at org.apache.kafka.connect.runtime.WorkerConnector.run(WorkerConnector.java:117)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

(I'm using Strimzi, if that makes any difference)

**Comment by lukens** [comment]
I've figured it out.

I suddenly remembered I'd had an issue before in my 20+ years of Java programming, where a class wasn't being found by another as it had been loaded by a different class loader, and I wondered if this was the issue here.

I had been loading the `kafka-connect-jdbc` and `jaybird` files in two different folders under `plugins`. I instead combined them into the same folder, and bingo, it's now finding the driver.

Now onto the next problem!
