### ISSUE TITLE
Error with SQL Server Text data type 

### ISSUE THREAD

**Issue by wegged** [confluentinc/kafka-connect-jdbc#126]
Hi,  

I am encountering the following error using the jtds 1.3.1 jdbc driver for sql server when we encounter a column with TEXT data type.  from the stack trace it looks like the error is in JTDS but I wonder if we can recover/ignore this column or if there was a different jdbc driver I should be trying that is more compatible with Kafka Connect.

Thanks,
Eli

> [2016-09-08 15:51:57,644] ERROR Task sql12Alloc-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:142)
> java.lang.AbstractMethodError
>         at net.sourceforge.jtds.jdbc.ClobImpl.free(ClobImpl.java:219)
>         at io.confluent.connect.jdbc.DataConverter.convertFieldValue(DataConverter.java:400)
>         at io.confluent.connect.jdbc.DataConverter.convertRecord(DataConverter.java:68)
>         at io.confluent.connect.jdbc.TimestampIncrementingTableQuerier.extractRecord(TimestampIncrementingTableQuerier.java:179)
>         at io.confluent.connect.jdbc.JdbcSourceTask.poll(JdbcSourceTask.java:217)
>         at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:155)
>         at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
>         at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)

**Comment by wegged** [comment]
was able to resolve by adding ;useLOBs=false to my database url
