### ISSUE TITLE
There is an issue with the SystemTime in JdbcSourceTask in Kafka version 3.9.0.

### ISSUE THREAD

**Issue by kkh03291** [confluentinc/kafka-connect-jdbc#1445]
I am not good at English, so I received help from GPT.

In Kafka version `3.9.0`, the method for creating an instance of the `SystemTime` class has changed.

Previously, you could obtain an instance of `SystemTime` using `new SystemTime()`. However, it now appears that `SystemTime` has adopted the Singleton pattern, requiring you to call `SystemTime.getSystemTime()` to create an instance.

Below are the related Kafka 3.9.0 release notes and the GitHub link to the changes:
https://issues.apache.org/jira/browse/KAFKA-16879
https://github.com/apache/kafka/pull/16266

Below is a portion of the modified source code for the `SystemTime` class:
```
class SystemTime implements Time {
    private static final SystemTime SYSTEM_TIME = new SystemTime();

    public static SystemTime getSystemTime() {
        return SYSTEM_TIME;
    }

   //...

    private SystemTime() {

    }
}
```

And below is the part of the `JdbcSourceTask` in Kafka Connect JDBC version `10.8.0` where the `SystemTime` field is initialized.

```
public class JdbcSourceTask extends SourceTask {
//..
  public JdbcSourceTask() {
    this.time = new SystemTime();
  }

  public JdbcSourceTask(Time time) {
    this.time = time;
  }
//..
}
```

Currently, even with the latest version of Kafka Connect JDBC (`10.8.0`), it cannot be used with Kafka version `3.9.0` due to the following error.
```
[2024-11-15 17:29:25,300] ERROR [test-connector-mysql|task-0] Failed to start task test-connector-mysql-0 (org.apache.kafka.connect.runtime.Worker:707)
org.apache.kafka.connect.errors.ConnectException: Instantiation error
	at org.apache.kafka.connect.runtime.isolation.Plugins.newPlugin(Plugins.java:142)
	at org.apache.kafka.connect.runtime.isolation.Plugins.newTask(Plugins.java:340)
	at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:664)
	at org.apache.kafka.connect.runtime.Worker.startSourceTask(Worker.java:592)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.startTask(StandaloneHerder.java:504)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.createConnectorTasks(StandaloneHerder.java:488)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.createConnectorTasks(StandaloneHerder.java:482)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.updateConnectorTasks(StandaloneHerder.java:541)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.lambda$null$2(StandaloneHerder.java:255)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: org.apache.kafka.common.KafkaException: Could not instantiate class io.confluent.connect.jdbc.source.JdbcSourceTask
	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:405)
	at org.apache.kafka.connect.runtime.isolation.Plugins.newPlugin(Plugins.java:140)
	... 14 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485)
	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:401)
	... 15 more
Caused by: java.lang.IllegalAccessError: failed to access class org.apache.kafka.common.utils.SystemTime from class io.confluent.connect.jdbc.source.JdbcSourceTask (org.apache.kafka.common.utils.SystemTime is in unnamed module of loader 'app'; io.confluent.connect.jdbc.source.JdbcSourceTask is in unnamed module of loader org.apache.kafka.connect.runtime.isolation.PluginClassLoader @63021689)
	at io.confluent.connect.jdbc.source.JdbcSourceTask.<init>(JdbcSourceTask.java:78)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 18 more
```

**Comment by movertaker** [comment]
We are not able to update our Kafka Connect instances because of this bug. When is it going to be fixed?

**Comment by zSeabraz** [comment]
Please fix this..

**Comment by sputnyq** [comment]
a fix would be nice

**Comment by rielcarol** [comment]
We are also experiencing this problem with latest versions (confluentinc/cp-kafka:latest -> 7.9.0) of confluent and jdbc-connector (confluentinc/kafka-connect-jdbc:latest -> 1.8.1)

**Comment by zSeabraz** [comment]
> For the time being, I've implemented the following workaround:
> 
> 1. Pull the latest code from the repository.
> 2. Modify the following item in the pom.xml file:
> 
> ![Image](https://github.com/user-attachments/assets/85d5984f-3b9f-47be-9a64-04fab5cb8ceb)
> 
> 3. Code modifications in the JDBCSourceTask class:
> 
> ![Image](https://github.com/user-attachments/assets/306494ee-8751-400e-b72f-89dbf06203b7)
> 
> 4. Removed the following in some test cases to complete the build:
> 
> ![Image](https://github.com/user-attachments/assets/970d6b1f-2bfd-407e-b752-de4e3d9e9aeb)
> 
> 5. After the build is complete, use the JAR file from the target folder.
> 
> **I assume you're familiar with the required build process (Maven).**
> 
> [@sputnyq](https://github.com/sputnyq) [@zSeabraz](https://github.com/zSeabraz) [@kkh03291](https://github.com/kkh03291)

Thank you so much , I'll try this out.

**Comment by azathoth123** [comment]
Please fix.

**Comment by sangeet259** [comment]
It has been fixed in the versions `v10.7.14` and `v10.8.2`. Those will be available in the confluent hub in a while.

![Image](https://github.com/user-attachments/assets/e961a079-5b6c-477d-9317-10f97f8a8ffa)

**Comment by huckpdx** [comment]
> It has been fixed in the versions `v10.7.14` and `v10.8.2`. Those will be available in the confluent hub in a while.
> 
> ![Image](https://github.com/user-attachments/assets/e961a079-5b6c-477d-9317-10f97f8a8ffa)

thanks for fixing this! but I do not see 10.8.2 in confluent hub. only 10.8.1. and sadly I don't have the skills to build it. please update the hub as soon as possible. I have a stuck migration.

thanks!

**Comment by huckpdx** [comment]
the new version is available now. thanks!
https://www.confluent.io/hub/confluentinc/kafka-connect-jdbc
