### ISSUE TITLE
org.apache.kafka.common.config.ConfigException: Incrementing column: ID does not exist.

### ISSUE THREAD

**Issue by c0desurfer** [confluentinc/kafka-connect-jdbc#1446]
[This introduced check](https://github.com/confluentinc/kafka-connect-jdbc/pull/1394) seems to work incorrectly. We have the following JDBC connector configuration.

```
{
	"numeric.mapping": "best_fit",
	"table.whitelist": <SNIP>",
	"auto.register.schemas": "false",
	"auth.type": "<SNIP>",
	"tasks.max": "1",
	"transforms.createKey.fields": "<SNIP>",
	"connector.class": "JdbcSourceConnector",
	"transforms.RenameField.renames": "<SNIP>",
	"consumer.override.security.protocol": "<SNIP>",
	"transforms.reroute.type": "org.apache.kafka.connect.transforms.RegexRouter",
	"transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value",
	"producer.override.sasl.mechanism": "<SNIP>",
	"producer.override.bootstrap.servers": "<SNIP>",
	"transforms.ReplaceField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value",
	"topic.prefix": "<SNIP>",
	"value.converter.schema.registry.url": "<SNIP>",
	"incrementing.column.name": "ID",
	"value.converter.auto.register.schemas": "false",
	"timestamp.column.name": "<SNIP>",
	"validate.non.null": "false",
	"key.converter": "io.confluent.connect.json.JsonSchemaConverter",
	"consumer.override.sasl.jaas.config": "<SNIP>",
	"value.converter": "io.confluent.connect.json.JsonSchemaConverter",
	"connection.attempts": "480",
	"connection.backoff.ms": "30000",
	"key.converter.schema.registry.url": "<SNIP>",
	"connection.url": "jdbc:oracle:thin:@(DESCRIPTION = (ADDRESS_LIST = (FAILOVER = ON)(LOAD_BALANCE = OFF)(ADDRESS = (PROTOCOL = TCP)(HOST = <SNIP>)(PORT = <SNIP>))(ADDRESS = (PROTOCOL = TCP)(HOST = <SNIP>)(PORT = <SNIP>))) (CONNECT_DATA = (SERVICE_NAME = <SNIP>)))",
	"connection.user": "<SNIP>",
	"key.converter.schemas.enable": "true",
	"key.converter.auto.register.schemas": "false",
	"consumer.override.sasl.mechanism": "<SNIP>",
	"connection.password": "<SNIP>",
	"consumer.override.group.id": "<SNIP>",
	"producer.override.security.protocol": "SASL_SSL",
	"transforms.ReplaceField.blacklist": "ID,<SNIP>",
	"use.latest.version": "true",
	"producer.override.sasl.jaas.config": "<SNIP>",
	"value.converter.schemas.enable": "true",
	"schema.pattern": "<SNIP>",
	"mode": "timestamp+incrementing",
	"transforms.reroute.replacement": "<SNIP>",
	"transforms.reroute.regex": "<SNIP>",
	"transforms": "reroute,ReplaceField,RenameField,createKey",
	"consumer.override.bootstrap.servers": "<SNIP>",
	"db.timezone": "Europe/<SNIP>",
	"transforms.createKey.type": "org.apache.kafka.connect.transforms.ValueToKey",
	"table.types": "SYNONYM"
}
```

Please note that the following properties are set.

```
"mode": "timestamp+incrementing"
"incrementing.column.name": "ID"
"timestamp.column.name": "<SNIP>"
```

The columns exist inside the DB.

![image](https://github.com/user-attachments/assets/4859a2d9-c682-4f70-b073-e07d52424377)

However since update to 10.8.0 we are getting the following error and had to rollback to 10.7.4.

```
[<SNIP>|task-0] WorkerSourceTask{id=<SNIP>} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-<SNIP>-0]
org.apache.kafka.common.config.ConfigException: Incrementing column: ID does not exist.
	at io.confluent.connect.jdbc.source.JdbcSourceTask.validateColumnsExist(JdbcSourceTask.java:333)
	at io.confluent.connect.jdbc.source.JdbcSourceTask.start(JdbcSourceTask.java:201)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.initializeAndStart(AbstractWorkerSourceTask.java:280)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:259)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.run(AbstractWorkerSourceTask.java:77)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

Not sure why the check fails, the code looks good at first sight. Any ideas?

**Comment by michherren** [comment]
I did some digging and identified the root cause of the issue.

The problem lies in this line of code:
https://github.com/confluentinc/kafka-connect-jdbc/blob/6ac424e9dae44a6622d3b360aef1c1bf93508633/src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java#L324

The describeColumns method returns an empty map for synonym tables. By default, JDBC does not resolve synonyms:
https://docs.oracle.com/en/database/oracle/oracle-database/21/okjdc/org/oracle/okafka/clients/admin/DescribeConfigsOptions.html#includeSynonyms__

To address this, the includeSynonyms flag must be set to true on the database connection. This allows the metadata of the tables to be retrieved correctly during the checks. Since multiple methods rely on this flag, it probably make sense to enable this option by default.

I have prepared a pull request and an integration test to resolve this issue:
https://github.com/confluentinc/kafka-connect-jdbc/pull/1496

As I am new to this codebase, I’m not certain if this is the best way of solving this. I appreciate any feedback!
