### ISSUE TITLE
Sporadic ConnectException leads to non processing of table data

### ISSUE THREAD

**Issue by vamossagar12** [confluentinc/kafka-connect-jdbc#160]
I had setup a 2 node distributed kafka-connect process. Everything went well and I could see lot of data flowing into the relevant kafka topics.
After some time, JDBCUtils.getCurrentTimeOnDB threw a ConnectException with the following stacktrace:

> The last packet successfully received from the server was 792 milliseconds ago. The last packet sent successfully to the server was 286 milliseconds ago. (io.confluent.connect.jdbc.source.JdbcSourceTask:234)
> [2016-11-02 12:42:06,116] ERROR Failed to get current time from DB using query select CURRENT_TIMESTAMP; on database MySQL (io.confluent.connect.jdbc.util.JdbcUtils:226)
> com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
> The last packet successfully received from the server was 1,855 milliseconds ago. The last packet sent successfully to the server was 557 milliseconds ago.
> at sun.reflect.GeneratedConstructorAccessor51.newInstance(Unknown Source)
> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
> at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1117)
> at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3829)
> at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2449)
> at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2629)
> at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2719)
> at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
> at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1379)
> at com.mysql.jdbc.StatementImpl.createResultSetUsingServerFetch(StatementImpl.java:651)
> at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1527)
> at io.confluent.connect.jdbc.util.JdbcUtils.getCurrentTimeOnDB(JdbcUtils.java:220)
> at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.executeQuery(TimestampIncrementingTableQuerier.java:157)
> at io.confluent.connect.jdbc.source.TableQuerier.maybeStartQuery(TableQuerier.java:78)
> at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.maybeStartQuery(TimestampIncrementingTableQuerier.java:57)
> at io.confluent.connect.jdbc.source.JdbcSourceTask.poll(JdbcSourceTask.java:207)
> at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:155)
> at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
> at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> at java.lang.Thread.run(Thread.java:745)
> Caused by: java.net.SocketException: Broken pipe (Write failed)
> at java.net.SocketOutputStream.socketWrite0(Native Method)
> at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
> at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
> at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
> at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
> at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3810)
> ... 20 more

This was just a minor glitch to the connection as the ec2 isntances are able to connect to the Mysql Aurora instances without any issues.
But, after this exception(which is there a number of times), the connector doesn't process any data from the table. Beyond this, all I see in the logs is

> [2016-11-02 16:17:41,983] ERROR Failed to run query for table TimestampIncrementingTableQuerier
> {name='eng_match_series', query='null', topicPrefix='ci-eng-', timestampColumn='modified', incrementingColumn='id'}
> com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after statement closed. (io.confluent.connect.jdbc.source.JdbcSourceTask:234)

I restarted the connector using REST apis but that didn't help. Eventually I had to delete the connector and restart. 
The kafka version I am using is 0.10.0.1-cp1 as there were some custom changes we needed to make at the Connect level.

**Comment by shikhar** [comment]
@vamossagar12 any chance you can try with the current master, since that includes #144?

**Comment by vamossagar12** [comment]
@shikhar I checked out master and on local I still got the same behavior as there was a network drop. Have deployed on our AWS instance to check.. I can't check the logs currently would update  tomorrow.

**Comment by vamossagar12** [comment]
@shikhar I have redeployed the jar with the new changes(the previous one had some issues from my end). I haven't got any connectivity errors as yet. Once that's there I will monitor the behavior and close the ticket accordingly.

**Comment by vamossagar12** [comment]
@shikhar So I got the exception again. After quite a few ConnectionRefusedException, and a few hours, the log says:

[2016-11-16 01:54:40,843] INFO The database connection is invalid. Reconnecting... (io.confluent.connect.jdbc.util.CachedConnectionProvider:54)

But beyond this, nothing seems to have happened.... The db is on Aurora and there have been a couple of automatic restarts and the issue stems from that... But it was momentary and the DBs were up in a minute.

**Comment by shikhar** [comment]
> But beyond this, nothing seems to have happened...

Sounds like it is hanging on the reconnection attempt? Could you get a thread-dump with `jstack`, if it is still in that state?

If it is indeed hanging on reconnecting you may want to consider setting `socketTimeout`  / `connectionTimeout` in your JDBC `connection.url`, as those default to 0 (no timeout). https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html

**Comment by vamossagar12** [comment]
@shikhar  I am attaching the thread dump as the exception came again and it gets hung on the recoonection attempt.
[threaddump.txt](https://github.com/confluentinc/kafka-connect-jdbc/files/597822/threaddump.txt)

Time being i will restart the workers but I would look into these config options.

**Comment by vamossagar12** [comment]
There's another issue we're facing. We have 2 workers which belong to the same cluster. 

And both throw the same exception. Now when I restarted the kafka-connect job on one of the workers, then 

1) All the tasks get pushed to the other worker. This is expected behaviour.

2) The worker which was restarted, can never get any of the tasks. The logs only have these lines multiple times:

> 
> 
> [2016-11-15 17:12:33,051] WARN Catching up to assignment's config offset. (org.apache.kafka.connect.runtime.distributed.DistributedHerder:686)
> [2016-11-15 17:12:33,051] INFO Current config state offset -1 is behind group assignment 82, reading to end of config log (org.apache.kafka.connect.runtime.distributed.DistributedHerder:730)
> [2016-11-15 17:12:33,551] INFO Finished reading to end of log and updated config snapshot, new config log offset: -1 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:734)
> [2016-11-15 17:12:33,551] INFO Current config state offset -1 does not match group assignment 82. Forcing rebalance. (org.apache.kafka.connect.runtime.distributed.DistributedHerder:710)
> [2016-11-15 17:12:33,552] INFO Rebalance started (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1044)
> [2016-11-15 17:12:33,552] INFO Wasn't unable to resume work after last rebalance, can skip stopping connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1074)
> [2016-11-15 17:12:33,552] INFO (Re-)joining group cricinfo-wcms-cluster (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:349)
> [2016-11-15 17:12:33,553] INFO Successfully joined group cricinfo-wcms-cluster with generation 17 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:457)
> [2016-11-15 17:12:33,553] INFO Joined group and got assignment: Assignment{error=0, leader='connect-1-8716805f-6b0b-4b3c-a1f9-cbb15f66f6ea', leaderUrl='http://10.184.0.34:8083/', offset=82, connectorIds=[ci-wcms-cms, ci-wcms-lookup], taskIds=[ci-wcms-cms-1, ci-wcms-cms-3, ci-wcms-cms-5, ci-wcms-lookup-1, ci-wcms-lookup-3, ci-wcms-lookup-5, ci-wcms-rel-0]} (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1023)
> [2016-11-15 17:12:33,553] WARN Catching up to assignment's config offset. (org.apache.kafka.connect.runtime.distributed.DistributedHerder:686)
> [2016-11-15 17:12:33,553] INFO Current config state offset -1 is behind group assignment 82, reading to end of config log (org.apache.kafka.connect.runtime.distributed.DistributedHerder:730)
                                                                                                                                                                                          

Also, it never catches up and the worker has been this way for a couple of days now.

**Comment by shikhar** [comment]
While trying to reproduce this I noticed a bug that we have a really high default timeout which could have led to the big gap you saw. https://github.com/confluentinc/kafka-connect-jdbc/blob/0d38f87db9b6c88326137543b338ba203a462f32/src/main/java/io/confluent/connect/jdbc/util/CachedConnectionProvider.java#L53 -- the API expects seconds not milliseconds. I'll patch that up.

One workaround to avoid blocking such a long time is to set the `socketTimeout` and/or `connectTimeout` properties on the `connection.url`. They take precedence. So for now I would suggest to set them to reasonable values.

I haven't yet had a chance to look into the issue you mention in https://github.com/confluentinc/kafka-connect-jdbc/issues/160#issuecomment-261300238

**Comment by vamossagar12** [comment]
Thanks @shikhar I tried with just setting connectTimeout to 10 s. That should be reasonable I guess? Also, do we need to use socketTimeout value to a reasonably long value so as to give a larger time period before it declares the connection as dead?

**Comment by vamossagar12** [comment]
@shikhar  Regarding this issue, we have migrated to confluent 3.1 now.. I was looking at the code for 3.1.0-Post branch( as I still needed to patch up the tinyint issue) but over there as well. the timeout value is set to 5000

https://github.com/confluentinc/kafka-connect-jdbc/blob/3.1.0-post/src/main/java/io/confluent/connect/jdbc/util/CachedConnectionProvider.java#L31

As you had pointed out, the api takes seconds and not milliseconds. I would set the connectTimeout param again but just wanted to know has the fix gone in or am I looking at a wrong branch?
