### ISSUE TITLE
Missing fields with oracle

### ISSUE THREAD

**Issue by charliwardbd** [confluentinc/kafka-connect-jdbc#183]
When i try to connect to oracle 11g XE with ojdbc6.jar i have problems. 

If i use the example in web site of confluent with the same configuration that it's indicated in the example i have problems with miising fields PK 

Can someone help me? I dont know if is a problem with the databse configuration or if a problem with de sink connector. I can see that someone has implemented with oracle.

**the logs indicates**

[2017-01-18 16:27:36,296] INFO Creating table:test9 with SQL: CREATE TABLE "test9" (
"product" CLOB NOT NULL,
"quantity" NUMBER(10,0) NOT NULL,
"price" BINARY_FLOAT NOT NULL,
"id" NUMBER(10,0) NOT NULL) (io.confluent.connect.jdbc.sink.DbStructure:88)
[2017-01-18 16:27:36,802] INFO Querying column metadata for product:Oracle schema:SYSTEM catalog:null table:TEST9 (io.confluent.connect.jdbc.sink.DbMetadataQueries:64)
[2017-01-18 16:27:37,759] INFO Updating cached metadata -- DbTable{name='test9', columns={}} (io.confluent.connect.jdbc.sink.metadata.TableMetadataLoadingCache:49)
[2017-01-18 16:27:37,760] ERROR Task test-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask:404)
org.apache.kafka.connect.errors.ConnectException: Cannot ALTER to add missing field SinkRecordField{schema=Schema{FLOAT32}, name='price', isPrimaryKey=false}, as it is not optional and does not have a default value
	at io.confluent.connect.jdbc.sink.DbStructure.amendIfNecessary(DbStructure.java:130)
	at io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:72)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:65)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:62)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:66)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:384)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:240)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:172)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:143)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-01-18 16:27:37,768] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerSinkTask:405)
[2017-01-18 16:27:37,769] INFO WorkerSinkTask{id=test-sink-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSinkTask:262)
[2017-01-18 16:27:37,784] ERROR Task test-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:142)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:406)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:240)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:172)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:143)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-01-18 16:27:37,784] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:143)
[2017-01-18 16:27:37,785] INFO Stopping task (io.confluent.connect.jdbc.sink.JdbcSinkTask:88)
[2017-01-18 16:27:41,090] INFO Reflections took 8031 ms to scan 272 urls, producing 12953 keys and 84565 values  (org.reflections.Reflections:229)

**Comment by shikhar** [comment]
> [2017-01-18 16:27:37,759] INFO Updating cached metadata -- DbTable{name='test9', columns={}} (io.confluent.connect.jdbc.sink.metadata.TableMetadataLoadingCache:49)

It seems there is a bug in the library or the driver when retrieving the table metadata. As you can see it seems to determine that the table has 0 columns.

**Comment by shikhar** [comment]
I wonder if it's a case sensitivity issue?

**Comment by charliwardbd** [comment]
No, I try with all in uppercase, all in downcase. 

If i put auto create for create the table, i create the table manually. I test with differents configurations. In this moment this is my config file

name=test-sink
connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
tasks.max=1
topics=TEST9
connection.url=jdbc:oracle:thin:@localhost:1521:xe
connection.user=myuser
connection.password=mypassword
auto.create=true

When start the connect create the table but the problem its missing fields. 

I think, similar to you, that the problem it's beacuse de ojdbc can't get the catalog. 

debbuging the code of the connect the method that get all info its java.sql.DatabaseMetaData;

**Comment by charliwardbd** [comment]
Was problem with uppercase letter. But sometimes i could use downcase. 

Next i saw other limitations. With oracle it needed use other properties that indicate de pk field, pk mode, insert mode, etc etc. If i dont put this de connect doesn't work. 

Thanks

**Comment by chaitras** [comment]
Hi, 
Similar issue is blocking us on the setup we have. Were you able to resolve this problem? How did you go about solving it? or is this an know bug in JDBC connector?

[2017-03-10 15:00:31,227] INFO Checking table:dev-TEST exists for product:Oracle schema:DEST_KAFKA catalog: (io.confluent.connect.jdbc.sink.DbMetadataQueries:47)
[2017-03-10 15:00:31,423] INFO product:Oracle schema:DEST_KAFKA catalog:null -- table:dev-TEST is present (io.confluent.connect.jdbc.sink.DbMetadataQueries:51)
[2017-03-10 15:00:31,440] INFO Querying column metadata for product:Oracle schema:DEST_KAFKA catalog:null table:DEV-TEST (io.confluent.connect.jdbc.sink.DbMetadataQueries:64)
[2017-03-10 15:00:31,495] ERROR Task oracle-cididb01-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask:449)
org.apache.kafka.connect.errors.ConnectException: Cannot ALTER to add missing field SinkRecordField{schema=Schema{INT64}, name='ID', isPrimaryKey=true}, as it is not optional and does not have a default value
	at io.confluent.connect.jdbc.sink.DbStructure.amendIfNecessary(DbStructure.java:130)


I have both auto create and auto evolve enabled. Auto create creates the table but complains about missing fields

name=oracle-cididb01
connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
tasks.max=1

# The topics to consume from - required for sink connectors like this one
topics=dev-TEST
pk.mode=record_value
pk.fields=ID


# Configuration specific to the JDBC sink connector.
connection.url=jdbc:oracle:thin:@server
connection.user=dest_kafka
connection.password=pswd

insert.mode=upsert
auto.create=true
auto.evolve=true


any pointers on how this was resolved will be helpful.

thanks

**Comment by charliwardbd** [comment]
Hi Chaitras, 

You must have several things in mind. 
1º For mi the Topic only works in UPPERCASE. the name of your topic its downcase and uppercase. 
2º Depending on the mode of insertion you use you must use other properties configured in differents modes. 
3º The name of the connector (the propertie name) in some case can have problem if you create multiple connectors with the same name. 
4º The topic create all strings fields as CLOB. You cannot use the strings fields as PRIMARY KEY. We change the connector for creation of string as VARCHAR2

This its my config file when use Primary Keys

connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
connection.password=distribuido
tasks.max:1,topics=MYTOPIC
batch.size=1,auto.evolve:true
connection.user=distribuido
name=sink-oracle-alfa-centauri
auto.create=true
connection.url=jdbc:oracle:thin:@localhost:1521:xe
insert.mode=upsert,pk.mode:record_value
pk.fields=FIELDA,FIELDB,FIELDC

And this without primary keys
name=test-sink-oracle
connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
tasks.max=1
#URL donde se encuentra la base de datos
connection.url=jdbc:oracle:thin:@localhost:1521:xe
connection.user=kafka
connection.password=kafka
#Usa la semántica apropiada soportada por el connector
insert.mode=upsert
topics=MYTOPIC
#Esta propiedad crea la base de datos en Oracle si no existe
auto.create=true
pk.mode=record_value
#Agrega automáticamente una columna si no existe
auto.evolve=true
#Esta propiedad especifica cuántos registros se agruparan para insertar
batch.size=1

**Comment by chaitras** [comment]
Thanks charliwardbd,

I will try with the uppercase topic and check the configs again.
Also had another question did you get it working with avro schema or something else?

**Comment by charliwardbd** [comment]
yes, for me its working with AVRO schema without problem. Works perfectly.

**Comment by chaitras** [comment]
Thanks I got it working after changing my topic name to uppercase. 
Looks like a bug in the jdbc connector for being case sensitive??

**Comment by charliwardbd** [comment]
No I dont think that it's a bug. I think that its how oracle manage the name of tables, views, columns, etc etc etc

**Comment by chaitras** [comment]
Sure, I mean uppercase  conversion can be handled in the connector.
