### ISSUE TITLE
org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid

### ISSUE THREAD

**Issue by ktlim86** [confluentinc/kafka-connect-jdbc#206]
Hi,

I am using the JDBC Connector to connect MSSQL to Kafka using standalone connector. I have encountered the following error below. I have placed the SQL JDBC jar in `/etc/kafka-connect-jdbc`. Please advice. Thanks.

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/share/java/kafka-serde-tools/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/java/kafka-connect-elasticsearch/slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/java/kafka-connect-hdfs/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/java/kafka/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
[2017-03-31 14:42:38,761] INFO StandaloneConfig values:
        access.control.allow.methods =
        access.control.allow.origin =
        bootstrap.servers = [localhost:9092]
        internal.key.converter = class org.apache.kafka.connect.json.JsonConverter
        internal.value.converter = class org.apache.kafka.connect.json.JsonConverter
        key.converter = class io.confluent.connect.avro.AvroConverter
        offset.flush.interval.ms = 60000
        offset.flush.timeout.ms = 5000
        offset.storage.file.filename = /tmp/connect.offsets
        rest.advertised.host.name = null
        rest.advertised.port = null
        rest.host.name = null
        rest.port = 8083
        task.shutdown.graceful.timeout.ms = 5000
        value.converter = class io.confluent.connect.avro.AvroConverter
 (org.apache.kafka.connect.runtime.standalone.StandaloneConfig:180)
[2017-03-31 14:42:39,060] INFO Logging initialized @1202ms (org.eclipse.jetty.util.log:186)
[2017-03-31 14:42:39,360] INFO AvroConverterConfig values:
        schema.registry.url = [http://localhost:8081]
        max.schemas.per.subject = 1000
 (io.confluent.connect.avro.AvroConverterConfig:169)
[2017-03-31 14:42:39,534] INFO AvroDataConfig values:
        schemas.cache.config = 1000
        enhanced.avro.schema.support = false
        connect.meta.data = true
 (io.confluent.connect.avro.AvroDataConfig:169)
[2017-03-31 14:42:39,536] INFO AvroConverterConfig values:
        schema.registry.url = [http://localhost:8081]
        max.schemas.per.subject = 1000
 (io.confluent.connect.avro.AvroConverterConfig:169)
[2017-03-31 14:42:39,537] INFO AvroDataConfig values:
        schemas.cache.config = 1000
        enhanced.avro.schema.support = false
        connect.meta.data = true
 (io.confluent.connect.avro.AvroDataConfig:169)
[2017-03-31 14:42:39,551] INFO Kafka Connect starting (org.apache.kafka.connect.runtime.Connect:50)
[2017-03-31 14:42:39,551] INFO Herder starting (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:72)
[2017-03-31 14:42:39,551] INFO Worker starting (org.apache.kafka.connect.runtime.Worker:119)
[2017-03-31 14:42:39,551] INFO Starting FileOffsetBackingStore with file /tmp/connect.offsets (org.apache.kafka.connect.storage.FileOffsetBackingStore:60)
[2017-03-31 14:42:39,557] INFO Worker started (org.apache.kafka.connect.runtime.Worker:124)
[2017-03-31 14:42:39,557] INFO Herder started (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:74)
[2017-03-31 14:42:39,558] INFO Starting REST server (org.apache.kafka.connect.runtime.rest.RestServer:98)
[2017-03-31 14:42:39,704] INFO jetty-9.2.15.v20160210 (org.eclipse.jetty.server.Server:327)
Mar 31, 2017 2:42:40 PM org.glassfish.jersey.internal.Errors logErrors
WARNING: The following warnings have been detected: WARNING: The (sub)resource method listConnectors in org.apache.kafka.connect.runtime.rest.resources.ConnectorsResource contains empty path annotation.
WARNING: The (sub)resource method createConnector in org.apache.kafka.connect.runtime.rest.resources.ConnectorsResource contains empty path annotation.
WARNING: The (sub)resource method listConnectorPlugins in org.apache.kafka.connect.runtime.rest.resources.ConnectorPluginsResource contains empty path annotation.
WARNING: The (sub)resource method serverInfo in org.apache.kafka.connect.runtime.rest.resources.RootResource contains empty path annotation.

[2017-03-31 14:42:40,979] INFO Started o.e.j.s.ServletContextHandler@3af4e0bf{/,null,AVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:744)
[2017-03-31 14:42:40,993] INFO Started ServerConnector@aa22f1c{HTTP/1.1}{0.0.0.0:8083} (org.eclipse.jetty.server.ServerConnector:266)
[2017-03-31 14:42:40,994] INFO Started @3140ms (org.eclipse.jetty.server.Server:379)
[2017-03-31 14:42:40,995] INFO REST server listening at http://127.0.1.1:8083/, advertising URL http://127.0.1.1:8083/ (org.apache.kafka.connect.runtime.rest.RestServer:150)
[2017-03-31 14:42:40,995] INFO Kafka Connect started (org.apache.kafka.connect.runtime.Connect:56)
[2017-03-31 14:42:41,122] ERROR Failed to create job for /etc/kafka-connect-jdbc/source-mssql.properties (org.apache.kafka.connect.cli.ConnectStandalone:88)
[2017-03-31 14:42:41,129] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:99)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid (use the endpoint `/{connectorType}/config/validate` to get a full list of errors)
        at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:80)
        at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:67)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:96)
Caused by: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid (use the endpoint `/{connectorType}/config/validate` to get a full list of errors)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:161)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:93)
[2017-03-31 14:42:41,132] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect:66)
[2017-03-31 14:42:41,132] INFO Stopping REST server (org.apache.kafka.connect.runtime.rest.RestServer:154)
[2017-03-31 14:42:41,137] INFO Stopped ServerConnector@aa22f1c{HTTP/1.1}{0.0.0.0:8083} (org.eclipse.jetty.server.ServerConnector:306)
[2017-03-31 14:42:41,147] INFO Stopped o.e.j.s.ServletContextHandler@3af4e0bf{/,null,UNAVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:865)
[2017-03-31 14:42:41,152] INFO REST server stopped (org.apache.kafka.connect.runtime.rest.RestServer:165)
[2017-03-31 14:42:41,152] INFO Herder stopping (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:78)
[2017-03-31 14:42:41,152] INFO Worker stopping (org.apache.kafka.connect.runtime.Worker:131)
[2017-03-31 14:42:41,153] INFO Stopped FileOffsetBackingStore (org.apache.kafka.connect.storage.FileOffsetBackingStore:68)
[2017-03-31 14:42:41,153] INFO Worker stopped (org.apache.kafka.connect.runtime.Worker:151)
[2017-03-31 14:42:50,014] INFO Reflections took 10357 ms to scan 270 urls, producing 12611 keys and 83412 values  (org.reflections.Reflections:229)
[2017-03-31 14:42:50,062] INFO Herder stopped (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:88)
[2017-03-31 14:42:50,063] INFO Kafka Connect stopped (org.apache.kafka.connect.runtime.Connect:71)
```

Here is my configuration of the source-jdbc-mssql.properties
```
name=test-source-mssql-jdbc
connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
tasks.max=1
connection.url=jdbc:sqlserver://x.x.x.13:1433;database=DATABASE;
connection.user=USER
connection.password=PASSWORD
table.whitelist=TEST_DB
schema.registry=dbo
mode=incrementing+timestamp
timestamp.column.name=UpdateDate
incrementing.column.name=ID
topic.prefix=test-mssql-jdbc-
```

**Comment by ktlim86** [comment]
any advice on this? as the error log above is not very useful to pinpoint exactly what has happened and I wasnt sure what value should I put in '{connectorType}'.

Found an [issue](https://issues.apache.org/jira/browse/KAFKA-4878) but not too sure about the progress.

**Comment by ktlim86** [comment]
manage to solve the problem. I realize that the problem is I put my MSSQL jdbc jar file in the wrong place.

**Comment by puneetjindal** [comment]
@ktlim86 Is it resolved for you as I am still getting the error
`[2017-09-07 16:46:35,570] ERROR Failed to create job for /etc/kafka-connect-jdbc/source-quickstart-sqlserver.properties (org.apache.kafka.connect.cli.ConnectStandalone:89)
[2017-09-07 16:46:35,571] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:100)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid and contains the following 2 error(s):
Invalid value com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'kafka'. ClientConnectionId:cca69c90-dc92-402c-ae82-6c890527b030 for configuration Couldn't open connection to jdbc:sqlserver://35.187.233.231:1433;database=testdb;
Invalid value com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'kafka'. ClientConnectionId:8a1fd987-696e-4f71-8ee2-f1310f15f2eb for configuration Couldn't open connection to jdbc:sqlserver://35.187.233.231:1433;database=testdb;
You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
        at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:79)
        at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:66)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:97)
Caused by: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid and contains the following 2 error(s):
Invalid value com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'kafka'. ClientConnectionId:cca69c90-dc92-402c-ae82-6c890527b030 for configuration Couldn't open connection to jdbc:sqlserver://35.187.233.231:1433;database=testdb;
Invalid value com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'kafka'. ClientConnectionId:8a1fd987-696e-4f71-8ee2-f1310f15f2eb for configuration Couldn't open connection to jdbc:sqlserver://35.187.233.231:1433;database=testdb;
You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
        at org.apache.kafka.connect.runtime.AbstractHerder.maybeAddConfigErrors(AbstractHerder.java:370)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:157)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:94)`

**Comment by cricket007** [comment]
@puneetjindal 

> Login failed for user 'kafka'

You need to add a `kafka` user to your MSSQL server, it would seem

**Comment by riverchou** [comment]
I encountered this problem due to wrong MySQL password! there is no need to create Kafka user as long as you set correct id/pwd to access MySQL. BTW also check your IP & port, I am using VirtualBox NAT so my IP is 127.0.0.1. Here is my setting 

connection.url=jdbc:mysql://127.0.0.1:3306/jdbctest?user=cloudera&password=!Cloudera123

**Comment by unixbps** [comment]
Can some one provide installation document & kafka connector for mysql.

FYI:
Configured kafka/confluent & mysql in RHEL 7, while executing below command i'm getting below error while executing this command
#/usr/bin/connect-standalone /etc/schema-registry/connect-avro-standalone.properties /etc/kafka-connect-jdbc/source-quickstart-mysql.properties 

ERROR:
---------
[2018-12-21 07:04:29,083] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:113)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid and contains the following 2 error(s):

Invalid value com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 548 milliseconds ago.  The last packet sent successfully to the server was 542 milliseconds ago. for configuration Couldn't open connection to jdbc:mysql://127.0.0.1:3306/demo?user=pbhupathi&password=P@ssword123&useSSL=true
Invalid value com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 47 milliseconds ago.  The last packet sent successfully to the server was 47 milliseconds ago. for configuration Couldn't open connection to jdbc:mysql://127.0.0.1:3306/demo?user=pbhupathi&password=P@ssword123&useSSL=true
You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
        at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:79)
        at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:66)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:110)
Caused by: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid and contains the following 2 error(s):
Invalid value com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 548 milliseconds ago.  The last packet sent successfully to the server was 542 milliseconds ago. for configuration Couldn't open connection to jdbc:mysql://127.0.0.1:3306/demo?user=pbhupathi&password=P@ssword123&useSSL=true
Invalid value com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 47 milliseconds ago.  The last packet sent successfully to the server was 47 milliseconds ago. for configuration Couldn't open connection to jdbc:mysql://127.0.0.1:3306/demo?user=pbhupathi&password=P@ssword123&useSSL=true
You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
        at org.apache.kafka.connect.runtime.AbstractHerder.maybeAddConfigErrors(AbstractHerder.java:423)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:189)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:107)
[2018-12-21 07:04:29,083] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect:65)
[2018-12-21 07:04:29,084] INFO Stopping REST server (org.apache.kafka.connect.runtime.rest.RestServer:223)
[2018-12-21 07:04:29,090] INFO Stopped http_8083@2ffe243f{HTTP/1.1,[http/1.1]}{0.0.0.0:8083} (org.eclipse.jetty.server.AbstractConnector:341)
[2018-12-21 07:04:29,090] INFO node0 Stopped scavenging (org.eclipse.jetty.server.session:167)
[2018-12-21 07:04:29,097] INFO Stopped o.e.j.s.ServletContextHandler@54336976{/,null,UNAVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:1040)
[2018-12-21 07:04:29,119] INFO REST server stopped (org.apache.kafka.connect.runtime.rest.RestServer:241)
[2018-12-21 07:04:29,119] INFO Herder stopping (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:95)
[2018-12-21 07:04:29,119] INFO Worker stopping (org.apache.kafka.connect.runtime.Worker:184)
[2018-12-21 07:04:29,119] INFO Stopped FileOffsetBackingStore (org.apache.kafka.connect.storage.FileOffsetBackingStore:66)
[2018-12-21 07:04:29,120] INFO Worker stopped (org.apache.kafka.connect.runtime.Worker:205)
[2018-12-21 07:04:29,120] INFO Herder stopped (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:112)
[2018-12-21 07:04:29,120] INFO Kafka Connect stopped (org.apache.kafka.connect.runtime.Connect:70)

**Comment by cricket007** [comment]
@unixbps

That error suggests a network issue, not necessarily a software installation issue 

https://stackoverflow.com/questions/2983248/com-mysql-jdbc-exceptions-jdbc4-communicationsexception-communications-link-fai

In particular, is mysql actually running? If possible, could you write a small JDBC app on your own with the same url and do a simple select statement? E.g. there are ways to debug the issue, but it's only possible within your network to do so
