### ISSUE TITLE
SQL Syntax error when current time is retrieved on DB2 UDB for AS/400

### ISSUE THREAD

**Issue by Protoss78** [confluentinc/kafka-connect-jdbc#211]
The error happens when using mode=timestamp+incrementing or mode=timestamp on a connected DB2 UDB for AS/400 database.
The exception is:
`[2017-04-19 16:09:11,379] DEBUG executing query select CURRENT_TIMESTAMP; to get current time from database (io.confluent.connect.jdbc.util.JdbcUtils:198)
[2017-04-19 16:09:11,388] ERROR Failed to get current time from DB using query select CURRENT_TIMESTAMP; on database DB2 UDB for AS/400 (io.confluent.connect.jdbc.util.JdbcUtils:205)
com.ibm.as400.access.AS400JDBCSQLSyntaxErrorException: [SQL0104] Token ; ungültig. Gültige Token: + - AS <IDENTIFIER>.
	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:891)
	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:692)
	at com.ibm.as400.access.AS400JDBCStatement.commonPrepare(AS400JDBCStatement.java:1836)
	at com.ibm.as400.access.AS400JDBCStatement.executeQuery(AS400JDBCStatement.java:2459)
	at io.confluent.connect.jdbc.util.JdbcUtils.getCurrentTimeOnDB(JdbcUtils.java:199)
	at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.executeQuery(TimestampIncrementingTableQuerier.java:154)
	at io.confluent.connect.jdbc.source.TableQuerier.maybeStartQuery(TableQuerier.java:84)
	at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.maybeStartQuery(TimestampIncrementingTableQuerier.java:55)
	at io.confluent.connect.jdbc.source.JdbcSourceTask.poll(JdbcSourceTask.java:200)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:162)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

The problem is caused by the 'select CURRENT_TIMESTAMP;' query.
A syntactical correct statement for DB2 UDB for AS/400 would either be:
* select CURRENT_TIMESTAMP from SYSIBM.SYSDUMMY1;
* values(CURRENT_TIMESTAMP);

**Comment by jeff-odum** [comment]
FYI the same error happens for "database DB2/LINUXZ64" - it isn't specific to AS/400:
>>>
ERROR Failed to get current time from DB using query select CURRENT_TIMESTAMP; on database DB2/LINUXZ64 (io.confluent.connect.jdbc.util.JdbcUtils:205)
com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=;;ct CURRENT_TIMESTAMP;END-OF-STATEMENT, DRIVER=4.14.113
<<<

**Comment by Protoss78** [comment]
Thanks for testing that. I'll rework the DB2 check into a platform independent one then.

**Comment by k1th** [comment]
Changed this to different match, as we're on Linux DB2 here.
https://github.com/confluentinc/kafka-connect-jdbc/pull/289

**Comment by ozzmaster** [comment]
I am also getting this error:

ERROR Failed to run query for table TimestampIncrementingTableQuerier{name='DATA_LOG', query='null', topicPrefix='test_jdbc_', timestampColumn='MODIFIED_TIME', incrementingColumn='ID'}: com.ibm.db2.jcc.am.SqlSyntax ErrorException: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=;;ct CURRENT_TIMESTAMP;END-OF-STATEMENT, DRIVER=3.69.71 (io.confluent.connect.jdbc.JdbcSourceTask:239)

This is my db2 connector properties:
name=test-db2-jdbc
connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
tasks.max=1
connection.url=jdbc:db2://db2-server:50000/TEST_BPM:schema=BPMS;user=db2admin;password=****;
connection.user=db2admin
connection.password=gertygert7#
mode=timestamp+incrementing
incrementing.column.name=ID
timestamp.column.name=MODIFIED_TIME
topic.prefix=test_jdbc_
table.whitelist=DATA_LOG

**Comment by k1th** [comment]
what's your db2 version and can you do a 
`select current_timestamp from SYSIBM.SYSDUMMY1;`
?

**Comment by raidentrance** [comment]
I tried and I'm getting:

SQL Error [42612]: DB2 SQL Error: SQLCODE=-142, SQLSTATE=42612, SQLERRMC=null, DRIVER=3.71.22
  com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-142, SQLSTATE=42612, SQLERRMC=null, DRIVER=3.71.22

I'm using dbeaver to connect to db2

**Comment by k1th** [comment]
you are using the jdbc 3.0 driver. did you try the 4.0 driver (version numbers starting with 4.).
We only tested with JDBC 4.0 drivers.

**Comment by leubedane** [comment]
This Error also happens with DB2 Version 11.1 driver and jdbc4.

**Comment by leubedane** [comment]
I created a pull request https://github.com/confluentinc/kafka-connect-jdbc/pull/463 for this issue.

**Comment by wicknicks** [comment]
Closing this since we this addressed in the Db2DatabaseDialect: https://github.com/confluentinc/kafka-connect-jdbc/commit/3f5744e0d4c105f2d6e049d71bfbea4b7e19a8dd.

**Comment by hotcoder** [comment]
do we need to take new version kafka-connect-jdbc jar ? to resolve the issue , as am also getting the same issue ? if it requires to take new version , which version we need to take 

https://stackoverflow.com/questions/56218720/getting-exception-failed-to-get-current-time-from-db-using-query-valuescurrent
