### ISSUE TITLE
ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:99)

### ISSUE THREAD

**Issue by gitime** [confluentinc/kafka-connect-jdbc#216]
Hi all,

I am trying to fetch some rows from my db table, and insert them to Kafka topic. But I am getting the following error;

```
[2017-05-03 10:51:00,099] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:99)
java.lang.NoSuchMethodError: org.apache.kafka.connect.connector.Connector.validate(Ljava/util/Map;)Lorg/apache/kafka/common/config/Config;
        at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:252)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:159)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:93)
```

I am using cent OS. Kafka version 0.10.0.1. Confluent 3.2.0. Below are my configurations;

Connector configuration

```
name=test-jdbc
connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
tasks.max=1
connection.url=jdbc:oracle:thin:@192.168.0.1:1521:user01
connection.user=account1
connection.password=account1
mode=bulk
topic.prefix=cachetest2
query=select name from students where rownum <= 2
```

Worker Configuration

```
bootstrap.servers=localhost:9092

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false

internal.key.converter=org.apache.kafka.connect.storage.StringConverter
internal.value.converter=org.apache.kafka.connect.storage.StringConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false

offset.storage.file.filename=/tmp/connect.offsets
offset.flush.interval.ms=10000
```

**Comment by dbranscombe** [comment]
Any luck with this? I'm new to KafkaConnect trying to get JDBCSourceConnector working and getting same error...

**Comment by wicknicks** [comment]
this looks like you are running an incompatible version of Connect with the JDBC connector. Take a look at this matrix to find the appropriate version of Connect for the version of connector you want to run: https://docs.confluent.io/current/installation/versions-interoperability.html#connectors.
