### ISSUE TITLE
unparsable date format

### ISSUE THREAD

**Issue by sunnn** [confluentinc/kafka-connect-jdbc#219]
ERROR Failed to get current time from DB using query select CURRENT_TIMESTAMP; on database SQLite (io.confluent.connect.jdbc.util.JdbcUtils:205) 
Unparseable date: "2017-05-15 10:25:12" does not match (\p{Nd}++)\Q-\E(\p{Nd}++)\Q-\E(\p{Nd}++)\Q \E(\p{Nd}++)\Q:\E(\p{Nd}++)\Q:\E(\p{Nd}++)\Q.\E(\p{Nd}++) 
@willyhoang

**Comment by aplamada** [comment]
I experienced the same issue.
Is this a limitation of sqlite? Can one use a timestamp / timestamp+incrementing [mode ](https://docs.confluent.io/current/connect/connect-jdbc/docs/source_config_options.html#mode) sqlite?

**Comment by wicknicks** [comment]
@sunnn, @aplamada can you paste the entire exception here? also: could you try using the latest version of the connector. that might resolve db specific issues. thanks!

**Comment by aplamada** [comment]
@wicknicks unfortunately I am no longer working on the project. As I mentioned previously I tried to use `mode=timestamp+incrementing` with a sqlite [example](https://docs.confluent.io/current/connect/kafka-connect-jdbc/source-connector/index.html#examples).  

*Just A Thought*: Keeping in mind that the [quick start](https://docs.confluent.io/current/connect/kafka-connect-jdbc/source-connector/index.html#quick-start) is done with a sqlite database, it might be helpful to continue with a sqlite database also in the [example](https://docs.confluent.io/current/connect/kafka-connect-jdbc/source-connector/index.html#examples) section.

**Comment by a-titorenko** [comment]
same issue: 
`[2018-12-27 12:13:36,137] ERROR Failed to run query for table TimestampIncrementingTableQuerier{table="order_events", query='null', topicPrefix='raw-', incrementingColumn='seq_num', timestampColumns=[updated]}: {} (io.confluent.connect.jdbc.source.JdbcSourceTask:326)
java.sql.SQLException: Error parsing time stamp
        at org.sqlite.jdbc3.JDBC3ResultSet.getTimestamp(JDBC3ResultSet.java:576)
        at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.currentTimeOnDB(GenericDatabaseDialect.java:463)
        at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.endTimetampValue(TimestampIncrementingTableQuerier.java:196)
        at io.confluent.connect.jdbc.source.TimestampIncrementingCriteria.setQueryParametersTimestampIncrementing(TimestampIncrementingCriteria.java:132)
        at io.confluent.connect.jdbc.source.TimestampIncrementingCriteria.setQueryParameters(TimestampIncrementingCriteria.java:119)
        at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.executeQuery(TimestampIncrementingTableQuerier.java:169)
        at io.confluent.connect.jdbc.source.TableQuerier.maybeStartQuery(TableQuerier.java:86)
        at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.maybeStartQuery(TimestampIncrementingTableQuerier.java:58)
        at io.confluent.connect.jdbc.source.JdbcSourceTask.poll(JdbcSourceTask.java:304)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:244)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:220)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.text.ParseException: Unparseable date: "2018-12-27 09:13:36" does not match (\p{Nd}++)\Q-\E(\p{Nd}++)\Q-\E(\p{Nd}++)\Q \E(\p{Nd}++)\Q:\E(\p{Nd}++)\Q:\E(\p{Nd}++)\Q.\E(\p{Nd}++)
        at org.sqlite.date.FastDateParser.parse(FastDateParser.java:299)
        at org.sqlite.date.FastDateFormat.parse(FastDateFormat.java:490)
        at org.sqlite.jdbc3.JDBC3ResultSet.getTimestamp(JDBC3ResultSet.java:573)
        ... 17 more
`

**Comment by rmoff** [comment]
Reproduced using SQLite 3. 

```
$ sqlite3 /tmp/test.db
SQLite version 3.19.3 2017-06-27 16:48:08
Enter ".help" for usage hints.
sqlite>
```

Create table and insert dummy row:

```
CREATE TABLE transactions_2(id integer primary key not null,
                  payment_type text not null,
                  Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
                  user_id int not null);
INSERT INTO TRANSACTIONS_2 (ID, PAYMENT_TYPE, USER_ID) VALUES (3,'FOO',1);
```

Verify data:

```
sqlite> select * from transactions_2;
3|FOO|2019-02-05 11:20:00|1
```

JDBC connector (Confluent Platform 5.1):

```
$ curl -s "http://localhost:8083/connectors/jdbc-source/config"|jq '.'
{
  "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
  "mode": "timestamp ",
  "timestamp.column.name": "timestamp ",
  "topic.prefix": "test-sqlite",
  "validate.non.null": "false",
  "tasks.max": "1 ",
  "name": "jdbc-source",
  "connection.url": "jdbc:sqlite:/tmp/test.db "
}
```

Fails: 

```
[2019-02-05 11:28:08,374] ERROR Failed to run query for table TimestampIncrementingTableQuerier{table="transactions_2", query='null', topicPrefix='test-sqlite', incrementingColumn='', timestampColumns=[timestamp]}: {} (io.confluent.connect.jdbc.source.JdbcSourceTask:326)
java.sql.SQLException: Error parsing time stamp
        at org.sqlite.jdbc3.JDBC3ResultSet.getTimestamp(JDBC3ResultSet.java:576)
        at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.currentTimeOnDB(GenericDatabaseDialect.java:463)
        at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.endTimetampValue(TimestampIncrementingTableQuerier.java:196)
        at io.confluent.connect.jdbc.source.TimestampIncrementingCriteria.setQueryParametersTimestamp(TimestampIncrementingCriteria.java:159)
        at io.confluent.connect.jdbc.source.TimestampIncrementingCriteria.setQueryParameters(TimestampIncrementingCriteria.java:121)
        at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.executeQuery(TimestampIncrementingTableQuerier.java:169)
        at io.confluent.connect.jdbc.source.TableQuerier.maybeStartQuery(TableQuerier.java:86)
        at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.maybeStartQuery(TimestampIncrementingTableQuerier.java:58)
        at io.confluent.connect.jdbc.source.JdbcSourceTask.poll(JdbcSourceTask.java:304)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:244)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:220)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.text.ParseException: Unparseable date: "2019-02-05 11:28:08" does not match (\p{Nd}++)\Q-\E(\p{Nd}++)\Q-\E(\p{Nd}++)\Q \E(\p{Nd}++)\Q:\E(\p{Nd}++)\Q:\E(\p{Nd}++)\Q.\E(\p{Nd}++)
        at org.sqlite.date.FastDateParser.parse(FastDateParser.java:299)
        at org.sqlite.date.FastDateFormat.parse(FastDateFormat.java:490)
        at org.sqlite.jdbc3.JDBC3ResultSet.getTimestamp(JDBC3ResultSet.java:573)
        ... 17 more
```

**Comment by OneCricketeer** [comment]
As far as I can tell, the last `\Q.\E(\p{Nd}++)` grouping (milliseconds separated from seconds with a period) should be optional (if supported at all)
