### ISSUE TITLE
JDBC source (Oracle) - Simultaneously selecting SOME_COLUMN as "some_column" in query mode if SOME_COLUMN is also used as the timestamp.column.name

### ISSUE THREAD

**Issue by mancini77** [confluentinc/kafka-connect-jdbc#274]
Background:
I am using Kafka-Connect in timestamp / query mode to dump Oracle data into a Postgresql database. Postgres is picky about capitilization, if you "SELECT teSt_cOl1, TEST_COL2, "TEST_col3" from test_table;"  postgres will convert  any unquoted column names to lowercase automatically - so the query hits the db as "select test_col1, test_col2, TEST_col3 from test_table" .. In general it is a best practice to create tables in postgresql with lower-cased column names, so that users can query the table in a case-insensitive manner, since postgres will automatically lowercase any unquoted column names present in a user's query. Note that postgresql will automatically lower-case the column names for you if you create the table with un-quoted column names:

create table test_caps(UPPER_CASE_TEST varchar(10), mixed_CASE varchar(10), lower_case varchar(10));

The following queries are valid:
select upper_case_test from test_caps; 
select UpPeR_cAsE_tEsT from test_caps; --valid, automatically lower-cased
select LOWER_CASE from test_caps; --valid, automatically lower-cased
etc.

ISSUE:

It seems that the kafka-connect sink table creation ddl hits postgres with explicity quoted column names in the table creation ddl. For example, if my source conenctor runs "select * from oracle_test_table",

Assuming oracle_test_table contains columns col1, col2, the postgresql sink will create table postgres_test_table ("COL1" varchar(10), "COL2" varchar(10) ) .

This means that the users must user explicity quoted, upper-cased column names when querying postgresql.

To get around this, in my source connector, I explicity cast my columns to quoted lower case :

"select col1 as "col1", col2 as "col2", maint_ts as "maint_ts" from oracle_test_table";

This seems to make the jdbc postgres sink  create my postgres table with lower-case columns.

However if  I select maint_ts as "maint_ts"  inside the source connector query and set the timestamp.column.name=maint_ts, I get the following (ORACLE) error:
java.sql.SQLSyntaxErrorException: ORA-00904: "maint_ts": invalid identifier 

If  I select maint_ts as "maint_ts" inside the source connector query and set the timestamp.column.name="maint_ts" (with quotes),  I get the following  error:
java.sql.SQLSyntaxErrorException: ORA-01741: illegal zero-length identifier

        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:440)
        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:837)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:445)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:191)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:523)
        at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
        at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:863)
        at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1153)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1275)
        at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3576)
        at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3620)
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1491)
        at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.executeQuery(TimestampIncrementingTableQuerier.java:176)
        at io.confluent.connect.jdbc.source.TableQuerier.maybeStartQuery(TableQuerier.java:84)
        at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.maybeStartQuery(TimestampIncrementingTableQuerier.java:55)
        at io.confluent.connect.jdbc.source.JdbcSourceTask.poll(JdbcSourceTask.java:200)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:163)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

If I select maint_ts as "maint_ts" inside the source connector query, and set the timestamp.column.name=MAINT_TS , I get the following (DataException) error:

ERROR Task product-source-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:148)
org.apache.kafka.connect.errors.DataException: MAINT_TS is not a valid field name.

It seems there is no way to simultaneously select SOME_COLUMN as "some_column" inside the query, and use some_column as the timestamp column.

**Comment by jsteggink** [comment]
Hi,
I have a similar issue with an Oracle database. When specifying a column name for a timestampColumn I get the following error:
`Caused by: Error : 904, Position : 104, Sql = SELECT * FROM "TEST_VIEW" WHERE "test_date" > :1  AND "test_date" < :2  ORDER BY "test_date" ASC, OriginalSql = SELECT * FROM "TEST_VIEW" WHERE "test_date" > ? AND "test_date" < ? ORDER BY "test_date" ASC, Error Msg = ORA-00904: "test_date": invalid identifier
`

Could this be because of the double quotes in the query?

Cheers,
Jeroen

**Comment by rhauch** [comment]
It is possible to bypass these quotes with #572, which was recently made and has not yet been released, though it will be in the 5.0.2, 5.1.1, and 5.2.0 releases whenever they occur. In the meantime, you can build the connector locally and try the new feature to disable quoting.

I'll mark this as closed, but feel free to reopen if you try the feature and it does not work for you.
