### ISSUE TITLE
MySQL incorrect detects table as present

### ISSUE THREAD

**Issue by rmoff** [confluentinc/kafka-connect-jdbc#276]
Tables present - note `sink-foobar2`: 

```
mysql> show tables;
+---------------------+
| Tables_in_demo      |
+---------------------+
| foobar              |
| foobar2             |
| sink-foobar2        |
| sink_mysql-foobar   |
| sink_mysql-foobar2  |
| sink_mysql__foobar  |
| sink_mysql__foobar2 |
+---------------------+
7 rows in set (0.00 sec)

mysql>
```

Sink config: 

```
{
        "name": "jdbc_sink_jdbc_foobar_04",
        "config": {
            "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
            "connection.url": "jdbc:mysql://localhost:3306/demo?user=rmoff&password=pw",
            "auto.create":"true",
            "topics":"mysql-avro-foobar2",
                  "transforms":"dropPrefix",
            "transforms.dropPrefix.type":"org.apache.kafka.connect.transforms.RegexRouter",
            "transforms.dropPrefix.regex":"mysql-avro-(.*)",
            "transforms.dropPrefix.replacement":"sink_$1"
        }
}
```

Resulting target table as result of transform is `sink_foobar2` (N.B. **underscore**, not hyphen). The connector detects this table as being present, even though it is not. As a result it is not created and thus the `INSERT` fails.

```
[2017-08-30 11:37:26,898] INFO Checking table:sink_foobar2 exists for product:MySQL schema:null catalog: (io.confluent.connect.jdbc.sink.DbMetadataQueries:47)
[2017-08-30 11:37:26,899] INFO product:MySQL schema:null catalog:demo -- table:sink_foobar2 is present (io.confluent.connect.jdbc.sink.DbMetadataQueries:51)
[2017-08-30 11:37:26,899] INFO Querying column metadata for product:MySQL schema:null catalog:demo table:sink_foobar2 (io.confluent.connect.jdbc.sink.DbMetadataQueries:64)
[2017-08-30 11:37:26,900] WARN Write of 5 records failed, remainingRetries=9 (io.confluent.connect.jdbc.sink.JdbcSinkTask:68)
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'demo.sink_foobar2' doesn't exist
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.Util.getInstance(Util.java:387)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:942)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503)
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1369)
        at com.mysql.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3739)
        at com.mysql.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3729)
        at com.mysql.jdbc.IterateBlock.doForAll(IterateBlock.java:50)
        at com.mysql.jdbc.DatabaseMetaData.getPrimaryKeys(DatabaseMetaData.java:3727)
        at io.confluent.connect.jdbc.sink.DbMetadataQueries.getTableMetadata(DbMetadataQueries.java:67)
        at io.confluent.connect.jdbc.sink.metadata.TableMetadataLoadingCache.get(TableMetadataLoadingCache.java:38)
        at io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:60)
        at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:66)
        at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:62)
        at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:66)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:435)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:251)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:180)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by gmyrianthous** [comment]
Any updates on this issue?

**Comment by dacoolbaby** [comment]
running into the same issue..
