### ISSUE TITLE
Docs should mention incrementing column must be returned by query

### ISSUE THREAD

**Issue by mihbor** [confluentinc/kafka-connect-jdbc#296]
Docs for the query config item (https://docs.confluent.io/current/connect/connect-jdbc/docs/source_config_options.html) currently don't mention this but the column defined by incrementing.column.name must be returned from the query, otherwise a NullPointerException is thrown here:
https://github.com/confluentinc/kafka-connect-jdbc/blob/v3.3.0/src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java#L215

```
[2017-10-06 12:33:26,550] ERROR Task tickers-admins-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:141)
java.lang.NullPointerException
	at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.extractOffset(TimestampIncrementingTableQuerier.java:215)
	at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.extractRecord(TimestampIncrementingTableQuerier.java:182)
	at io.confluent.connect.jdbc.source.JdbcSourceTask.poll(JdbcSourceTask.java:205)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:162)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Having to return that column is kind of obvious when you think about it, but if you don't think about how the connector is implemented it's easy to omit this column if not documented.

**Comment by premjitsingh** [comment]
Also I found that the increment column name has to be the first column. I was having the column name at the last and it kept on failing.
