### ISSUE TITLE
Classname "io.confluent.connect.jdbc.JdbcSourceConnector" is not defined

### ISSUE THREAD

**Issue by PiotrBB** [confluentinc/kafka-connect-jdbc#301]
Hello,

I'm trying to create jabc oracle connector. Upon creating new one with Connect UI i got the following error:
`Classname "io.confluent.connect.jdbc.JdbcSourceConnector" is not defined`

Here's my connector:
```
name=source-oracle-test
connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
tasks.max=1
connection.password=PASSWORD
connection.url=jdbc:oracle:thin:@oraclehost:1572/SERVICE
connection.user=USER
table.whitelist=TABLE
mode=timestamp
timestamp.column.name=TRANSACTIONDATE
topic.prefix=source-oracle-test
```
Any ideas how to handle this?

**Comment by rhauch** [comment]
I just downloaded and installed CP 3.3.0, cd-ed into the installation directory, added a `etc/kafka-connect-jdbc/source-oracle-test.properties` file with the contents you listed above, and then ran:

    bin/connect-standalone etc/schema-registry/connect-avro-standalone.properties /etc/kafka-connect-jdbc/source-oracle-test.properties

I get the following in the log:

```
...
[2017-11-09 09:12:11,139] INFO Kafka Connect started (org.apache.kafka.connect.runtime.Connect:55)
[2017-11-09 09:12:11,190] ERROR Failed to create job for etc/kafka-connect-jdbc/source-oracle-test.properties (org.apache.kafka.connect.cli.ConnectStandalone:89)
[2017-11-09 09:12:11,190] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:100)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid and contains the following 2 error(s):
Invalid value java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@oraclehost:1572/SERVICE for configuration Couldn't open connection to jdbc:oracle:thin:@oraclehost:1572/SERVICE
Invalid value java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@oraclehost:1572/SERVICE for configuration Couldn't open connection to jdbc:oracle:thin:@oraclehost:1572/SERVICE
You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
	at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:79)
	at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:66)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:97)
Caused by: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid and contains the following 2 error(s):
Invalid value java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@oraclehost:1572/SERVICE for configuration Couldn't open connection to jdbc:oracle:thin:@oraclehost:1572/SERVICE
Invalid value java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@oraclehost:1572/SERVICE for configuration Couldn't open connection to jdbc:oracle:thin:@oraclehost:1572/SERVICE
You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
	at org.apache.kafka.connect.runtime.AbstractHerder.maybeAddConfigErrors(AbstractHerder.java:370)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:157)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:94)
[2017-11-09 09:12:11,191] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect:65)
...
```

I wonder if you've not properly installed the JDBC connector into your Connect installation, either via classpath or plugin.path mechanism.

**Comment by PiotrBB** [comment]
When i tried to launch my oracle connector at first. i got an error that there is no suitable driver found, same as you. So i downloaded ojdbc8.jar and placed it in `/usr/share/java/kafka-connect-jdbc/`. Mentioned error no longer occurred but still the connector does not work.
