### ISSUE TITLE
NullpointerException at JdbcUtils.getAutoincrementColumn(JdbcUtils.java:158) with microsoft sqlserver connection

### ISSUE THREAD

**Issue by onkeltom2014** [confluentinc/kafka-connect-jdbc#323]
Using mode timestamp+incrementing with sqlserver connection leads to an NullpointerException:

java.lang.NullPointerException at io.confluent.connect.jdbc.util.JdbcUtils.getAutoincrementColumn(JdbcUtils.java:158) at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.createPreparedStatement(TimestampIncrementingTableQuerier.java:82) at io.confluent.connect.jdbc.source.TableQuerier.getOrCreatePreparedStatement(TableQuerier.java:71) at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.getOrCreatePreparedStatement(TimestampIncrementingTableQuerier.java:55) at io.confluent.connect.jdbc.source.TableQuerier.maybeStartQuery(TableQuerier.java:83) at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.maybeStartQuery(TimestampIncrementingTableQuerier.java:55) at io.confluent.connect.jdbc.source.JdbcSourceTask.poll(JdbcSourceTask.java:225) at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:179) at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170) at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

I have create a test and find out, that the mssql server driver unlike the oracle interface description returns the autoincrement information on column 22. Based on this informations i have create a patch to avoid this issue.
[kafka-connect-jdbc-JdbcUtils.patch.txt](https://github.com/confluentinc/kafka-connect-jdbc/files/1517445/kafka-connect-jdbc-JdbcUtils.patch.txt)

**Comment by onkeltom2014** [comment]
Unfortunately the original patch did not match the formation rules. Here is the corrected patch.
[kafka-connect-jdbc-JdbcUtils.patch.txt](https://github.com/confluentinc/kafka-connect-jdbc/files/1517472/kafka-connect-jdbc-JdbcUtils.patch.txt)
