### ISSUE TITLE
Oracle NUMBER not converting properly

### ISSUE THREAD

**Issue by jheckel123** [confluentinc/kafka-connect-jdbc#326]
I have seen the other issues related to Oracle NUMBER of type NUMBER(38,0) and references to DataConverter. Producing with the JDBC source and then viewing with kafka consumer still is not returning correct values. I have added debug statements to DataConverter and appears it is properly getting the correct value (the columns are ID and BANNER_PIDM):

[2017-12-08 18:45:58,428] DEBUG DataConverter.convertRecord: Schema=>Schema{T_EMPLOYEE_PIDM_DELTA:STRUCT} (io.confluent.connect.jdbc.source.JdbcSourceTask)
[2017-12-08 18:45:58,428] DEBUG DataConverter.convertRecord: mapNumerics=>false (io.confluent.connect.jdbc.source.JdbcSourceTask)
[2017-12-08 18:45:58,429] DEBUG DataConverter.convertFieldValue: colType=>2 (io.confluent.connect.jdbc.source.JdbcSourceTask)
[2017-12-08 18:45:58,429] DEBUG DataConverter.convertFieldValue: colValue=>402 (io.confluent.connect.jdbc.source.JdbcSourceTask)
[2017-12-08 18:45:58,430] DEBUG DataConverter.convertFieldValue: colType=>2 (io.confluent.connect.jdbc.source.JdbcSourceTask)
[2017-12-08 18:45:58,430] DEBUG DataConverter.convertFieldValue: colValue=>44114 (io.confluent.connect.jdbc.source.JdbcSourceTask)
[2017-12-08 18:45:58,430] DEBUG DataConverter.convertFieldValue: colType=>12 (io.confluent.connect.jdbc.source.JdbcSourceTask)
[2017-12-08 18:45:58,430] DEBUG DataConverter.convertFieldValue: colValue=>test (io.confluent.connect.jdbc.source.JdbcSourceTask)
[2017-12-08 18:45:58,431] DEBUG DataConverter.convertFieldValue: colType=>12 (io.confluent.connect.jdbc.source.JdbcSourceTask)
[2017-12-08 18:45:58,432] DEBUG DataConverter.convertFieldValue: colValue=>test (io.confluent.connect.jdbc.source.JdbcSourceTask)
[2017-12-08 18:45:58,432] DEBUG DataConverter.convertFieldValue: colType=>12 (io.confluent.connect.jdbc.source.JdbcSourceTask)
[2017-12-08 18:45:58,432] DEBUG DataConverter.convertFieldValue: colValue=>null (io.confluent.connect.jdbc.source.JdbcSourceTask)
[2017-12-08 18:45:58,432] DEBUG DataConverter.convertFieldValue: colType=>93 (io.confluent.connect.jdbc.source.JdbcSourceTask)
[2017-12-08 18:45:58,438] DEBUG DataConverter.convertFieldValue: colValue=>2017-12-08 18:45:48.0 (io.confluent.connect.jdbc.source.JdbcSourceTask)
[2017-12-08 18:45:58,438] DEBUG DataConverter.convertFieldValue: colType=>12 (io.confluent.connect.jdbc.source.JdbcSourceTask)
[2017-12-08 18:45:58,438] DEBUG DataConverter.convertFieldValue: colValue=>jheckel (io.confluent.connect.jdbc.source.JdbcSourceTask)
[2017-12-08 18:45:58,439] DEBUG DataConverter.convertRecord: Struct=>Struct{ID=402,BANNER_PIDM=44114,CHANGE_TABLE=test,CHANGE_ACTION=test,ACTV_DT=2017-12-08 18:45:48.0,USER_ID=jheckel} (io.confluent.connect.jdbc.source.JdbcSourceTask)

You can see they have 402 and 44114 correctly. But when viewing with console consumer do not see these values:

{"schema":{"type":"struct","fields":[{"type":"bytes","optional":false,"name":"org.apache.kafka.connect.data.Decimal","version":1,"parameters":{"scale":"0"},"field":"ID"},{"type":"bytes","optional":false,"name":"org.apache.kafka.connect.data.Decimal","version":1,"parameters":{"scale":"0"},"field":"BANNER_PIDM"},{"type":"string","optional":false,"field":"CHANGE_TABLE"},{"type":"string","optional":false,"field":"CHANGE_ACTION"},{"type":"string","optional":true,"field":"PROCESSED_FLAG"},{"type":"int64","optional":false,"name":"org.apache.kafka.connect.data.Timestamp","version":1,"field":"ACTV_DT"},{"type":"string","optional":false,"field":"USER_ID"}],"optional":false,"name":"T_EMPLOYEE_PIDM_DELTA"},"payload":{"ID":"AZI=","BANNER_PIDM":"AKxS","CHANGE_TABLE":"test","CHANGE_ACTION":"test","PROCESSED_FLAG":null,"ACTV_DT":1512758748000,"USER_ID":"jheckel"}}

Here are the relevant worker settings (I am running from Docker):

  -e CONNECT_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter" \
  -e CONNECT_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter" \
  -e CONNECT_INTERNAL_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter" \
  -e CONNECT_INTERNAL_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter" \

So I am unclear if the error is in the converter and should pursue that.

Thanks for any help.

**Comment by jheckel123** [comment]
More on this, I switched to trying Avro converter with no better luck. I then decided to try and manually load the schema into the registry before running for source for the first time. The schema loaded fine. But when ran the source got this error in the worker:

[2017-12-08 20:59:22,326] ERROR WorkerSourceTask{id=employee-oracle-jdbc-autoincrement-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.DataException: employee-oracle-jdbc-T_EMPLOYEE_PIDM_DELTA
	at io.confluent.connect.avro.AvroConverter.fromConnectData(AvroConverter.java:77)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:220)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:187)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.kafka.common.errors.SerializationException: Error registering Avro schema: {"type":"record","name":"T_EMPLOYEE_PIDM_DELTA","fields":[{"name":"ID","type":{"type":"bytes","scale":0,"precision":64,"connect.version":1,"connect.parameters":{"scale":"0"},"connect.name":"org.apache.kafka.connect.data.Decimal","logicalType":"decimal"}},{"name":"BANNER_PIDM","type":{"type":"bytes","scale":0,"precision":64,"connect.version":1,"connect.parameters":{"scale":"0"},"connect.name":"org.apache.kafka.connect.data.Decimal","logicalType":"decimal"}},{"name":"CHANGE_TABLE","type":"string"},{"name":"CHANGE_ACTION","type":"string"},{"name":"PROCESSED_FLAG","type":["null","string"],"default":null},{"name":"ACTV_DT","type":{"type":"long","connect.version":1,"connect.name":"org.apache.kafka.connect.data.Timestamp","logicalType":"timestamp-millis"}},{"name":"USER_ID","type":"string"}],"connect.name":"T_EMPLOYEE_PIDM_DELTA"}
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Schema being registered is incompatible with an earlier schema; error code: 409
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:191)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:218)

So something in both the JSON and AVRO converters appear to not be generating the schema correctly for these NUMERIC column types.

**Comment by jheckel123** [comment]
I found the issue. It was related to DataConverter. I am going against Oracle 12.2. It's integer data type is this:
subtype INTEGER  is NUMBER(38,0);
subtype INT      is INTEGER;
subtype SMALLINT is NUMBER(38,0);
Looking at code from DataConverter there is this:
      ```
case Types.NUMERIC:
        if (mapNumerics) {
          int precision = metadata.getPrecision(col);
          if (metadata.getScale(col) == 0 && precision < 19) { // integer
            Schema schema;
            if (precision > 9) {
              schema = (optional) ? Schema.OPTIONAL_INT64_SCHEMA :
                      Schema.INT64_SCHEMA;
            } else if (precision > 4) {
              schema = (optional) ? Schema.OPTIONAL_INT32_SCHEMA :
                      Schema.INT32_SCHEMA;
            } else if (precision > 2) {
              schema = (optional) ? Schema.OPTIONAL_INT16_SCHEMA :
                      Schema.INT16_SCHEMA;
            } else {
              schema = (optional) ? Schema.OPTIONAL_INT8_SCHEMA :
                      Schema.INT8_SCHEMA;
            }
            builder.field(fieldName, schema);
            break;
          }
        }
        // fallthrough

      case Types.DECIMAL: {
        int scale = metadata.getScale(col);
        if (scale == -127) { //NUMBER without precision defined for OracleDB
          scale = 127;
        }
        SchemaBuilder fieldBuilder = Decimal.builder(scale);
        if (optional) {
          fieldBuilder.optional();
        }
        builder.field(fieldName, fieldBuilder.build());
        break;
      }
```
So even if map numerics it will fall through to decimal if precision is this large.
