### ISSUE TITLE
JDBC Sink fails on duplicate violation

### ISSUE THREAD

**Issue by iMajna** [confluentinc/kafka-connect-jdbc#327]
Hi guys,
Have a question about JDBCSinker of yours. The problem I’m meeting with is *duplicates*. So, with index for ignoring duplicates on SQLServer sinker is *CRASHING*. Every time he tries to write in table with that index and he cant (because of index) sinker is stopping working.ž

DISCLAIMER!
SInker is working perfectly when there is no index.
We are using *insert* as type of inserting and whole other configuration parameters are common, nothing is special

Our next idea is implementing excatly once semantic, but thats not the case, I'm interested how to workaround this on sinker side. Thank you :slightly_smiling_face:

+ "Try with UPSERT" is not the answer on this issue :)

```
Dec 19 10:48:07 bigdata1.int.ch connect-distributed[27631]: org.apache.kafka.connect.errors.ConnectException: Update count (166) did not sum up to total number of records inserted (173)
Dec 19 10:48:07 bigdata1.int.ch connect-distributed[27631]: at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:111)
Dec 19 10:48:07 bigdata1.int.ch connect-distributed[27631]: at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:65)
Dec 19 10:48:07 bigdata1.int.ch connect-distributed[27631]: at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:66)
Dec 19 10:48:07 bigdata1.int.ch connect-distributed[27631]: at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:435)
Dec 19 10:48:07 bigdata1.int.ch connect-distributed[27631]: at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:251)
Dec 19 10:48:07 bigdata1.int.ch connect-distributed[27631]: at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:180)
Dec 19 10:48:07 bigdata1.int.ch connect-distributed[27631]: at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
Dec 19 10:48:07 bigdata1.int.ch connect-distributed[27631]: at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
Dec 19 10:48:07 bigdata1.int.ch connect-distributed[27631]: at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
Dec 19 10:48:07 bigdata1.int.ch connect-distributed[27631]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Dec 19 10:48:07 bigdata1.int.ch connect-distributed[27631]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Dec 19 10:48:07 bigdata1.int.ch connect-distributed[27631]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
Dec 19 10:48:07 bigdata1.int.ch connect-distributed[27631]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
Dec 19 10:48:07 bigdata1.int.ch connect-distributed[27631]: at java.lang.Thread.run(Thread.java:748)
Dec 19 10:48:07 bigdata1.int.ch connect-distributed[27631]: [2017-12-19 10:48:07,174] ERROR Task is being killed and will not recover until manually restarted
```

**Comment by rhauch** [comment]
Can you please provide an example of the kind of index you're creating on the table, and some sample messages showing some of the duplicates?

**Comment by iMajna** [comment]
@rhauch 
When we generally speak, I created this kind of index: 
`CREATE UNIQUE CLUSTERED INDEX T_DST_A ON T_DST(A) WITH IGNORE_DUP_KEY`

I cannot unfortunately provide you messages, but I think you know what is happening. Basically, that key is there if connector fails, message is written to database but offset is not commited and the same message is trying to be written again.

**Comment by iMajna** [comment]
@rhauch any news? We are still pushed to use UPSERT instead INSERT because of this

**Comment by rhauch** [comment]
@iMajna, Connect guarantees "at least once" delivery. Usually, the JDBC sink processes records, inserts them into the backend database, and asynchronously and periodically commits offsets (via normal consumer offset mechanism). However, if anything happens to the Connect worker after records have been inserted into the database but before the offsets are committed, Connect has no knowledge that those records were indeed inserted, and it restarts processing records at the most recently committed offsets. The net effect is that in your case a small number of records will be reprocessed.

This is usually the reason why records are processed more than once. Other reasons might be that Connect has problems committing offsets (should be warnings or errors in the log). Can you identify why the connector is reprocessing some records? If records are not being processed more than once, then perhaps it is possible that the topic being consumed by the JDBC sink connector has duplicate records (w/r/t the unique index column values).

As you know, `INSERT` does not work when processing a record more than once, and this is why the connector has the `UPSERT` mode. Given the duplicate records, I'm wondering why you don't believe that is the correct thing to do in these cases. What do believe should be the behavior of the sink connector?

If the problem is that the topic contains duplicates, then you can try to eliminate that with the upstream application by using EOS or de-duplicating the topic (e.g., using KStreams or KSQL) before the JDBC sink connector.

**Comment by RajKumarMondol** [comment]
I also faced this issue. The only option was to use `UPSERT`. In our case, we were using the DB2 Database. We had a trigger which was processing on each inserted records and updates the record's status column to **processed**. While `kafka-connect-jdbc` retries with `upsert` it updates that status column back to **pending**;
This was because DB2DatabaseDialect by default supports `INSERT OR UPDATE` but we required `INSERT OR IGNORE`. We have made a modification to forked `kafka-connect-jdbc` to achieve this.

I have created the following issue and planning to create a pull request with different upsert styles and implementing `INSERT OR IGNORE` for DB2DatabaseDialect.
[https://github.com/confluentinc/kafka-connect-jdbc/issues/874](url)

**Comment by yuyinrao** [comment]
I found that. when the table have some rules and when I execute insert sql, the programe return "Affected rows: 0", appear this bug. but the insert sql execute success and the date append to table.

[2020-12-12 07:07:01,290] ERROR WorkerSinkTask{id=sink-beijing-metrics-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: Update count (0) did not sum up to total number of records inserted (2) (org.apache.kafka.connect.runtime.WorkerSinkTask)
org.apache.kafka.connect.errors.ConnectException: Update count (0) did not sum up to total number of records inserted (2)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:194)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:72)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:545)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:325)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:228)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:200)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-12 07:07:01,291] ERROR WorkerSinkTask{id=sink-beijing-metrics-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:567)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:325)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:228)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:200)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.ConnectException: Update count (0) did not sum up to total number of records inserted (2)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:194)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:72)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:545)
	... 10 more
[2020-12-12 07:07:01,292] ERROR WorkerSinkTask{id=sink-beijing-metrics-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)

![微信截图_20201212151756](https://user-images.githubusercontent.com/22970441/101978207-38bf0f00-3c8e-11eb-809b-f74375651f81.png)
