### ISSUE TITLE
JTDS Sybase Plugin throws "Tables could not be updated quickly enough"

### ISSUE THREAD

**Issue by keisenb** [confluentinc/kafka-connect-jdbc#343]
Here is my configuration for the connector.

```{
  "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
  "mode": "timestamp+incrementing",
  "timestamp.column.name": "updated_at",
  "incrementing.column.name": "id",
  "topic.prefix": "test-sybase-",
  "tasks.max": "1",
  "name": "SybaseConnector123",
  "connection.url": "jdbc:jtds:sybase://example.com:5000/kafkadb;user=username;password=password",
  "table.whitelist": "table_name"
} 
```

Here is the error message in the connect logs. 
```
kafka-connect_1          | 2018-01-05T19:18:23.394215141Z org.apache.kafka.connect.errors.ConnectException: Tables could not be updated quickly enough.
kafka-connect_1          | 2018-01-05T19:18:23.394217223Z       at io.confluent.connect.jdbc.source.TableMonitorThread.tables(TableMonitorThread.java:110)
kafka-connect_1          | 2018-01-05T19:18:23.394219808Z       at io.confluent.connect.jdbc.JdbcSourceConnector.taskConfigs(JdbcSourceConnector.java:150)
kafka-connect_1          | 2018-01-05T19:18:23.394221613Z       at org.apache.kafka.connect.runtime.Worker.connectorTaskConfigs(Worker.java:271)
kafka-connect_1          | 2018-01-05T19:18:23.394223743Z       at org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnector(DistributedHerder.java:963)
kafka-connect_1          | 2018-01-05T19:18:23.394225685Z       at org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnectorTasksWithRetry(DistributedHerder.java:914)
kafka-connect_1          | 2018-01-05T19:18:23.394227751Z       at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$900(DistributedHerder.java:100)
kafka-connect_1          | 2018-01-05T19:18:23.394229618Z       at org.apache.kafka.connect.runtime.distributed.DistributedHerder$17$1.call(DistributedHerder.java:927)
kafka-connect_1          | 2018-01-05T19:18:23.394231613Z       at org.apache.kafka.connect.runtime.distributed.DistributedHerder$17$1.call(DistributedHerder.java:924)
kafka-connect_1          | 2018-01-05T19:18:23.394233463Z       at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:249)
kafka-connect_1          | 2018-01-05T19:18:23.394240598Z       at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:199)
kafka-connect_1          | 2018-01-05T19:18:23.394242553Z       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
kafka-connect_1          | 2018-01-05T19:18:23.394244396Z       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
kafka-connect_1          | 2018-01-05T19:18:23.394246302Z       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
kafka-connect_1          | 2018-01-05T19:18:23.394248278Z       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
kafka-connect_1          | 2018-01-05T19:18:23.394250322Z       at java.lang.Thread.run(Thread.java:745)
```

Things I have tried: 

- I have tried using the jconn4 sybase driver instead of the jtds open source one. I get a different error message with that I haven't been able to resolve. That error message is `Invalid value com.sybase.jdbc4.jdbc.SybSQLException: '""' is not a valid type name. for configuration Couldn't open connection to...`
- Using bulk mode instead of timestamp or incrementing. This will work. I can write a query and return rows successfully however this is not ideal as I would like to only get changes/additions.
- Monitored the connection on the DB side to look to see if the connection is happening, it looks like the connection is succesfully established and then it just sits there. Doesn't try to do anything.
- Forked the repo and increased the timeout from 10 seconds to 60 seconds, same issue.
- Added an else if to the getCurrentTimeOnDB method to handle the gettime() sybase uses to get the current time. See issue #299 however I still get the same error message.

If you need any other information or help testing/debugging please let me know I'm happy to help. Thanks.

**Comment by rhauch** [comment]
Please see #333 for adding explicit DBMS-specific dialects for the source connector, and incorporates/refactors the existing sink dialects. I'm currently adding a Sybase dialect to that PR.

**Comment by rhauch** [comment]
> `Invalid value com.sybase.jdbc4.jdbc.SybSQLException: '""' is not a valid type name. for configuration `

this is actually a problem with the current connector that assumes no JDBC catalog and a JDBC schema. Sybase and SQL Server both need the JDBC catalog and schema. #333 attempts to fix this by always using the fully-qualified table name when querying, but it still needs lots of testing.

**Comment by keisenb** [comment]
Thanks for the info. I'll monitor that PR and test once you've added the Sybase dialect.

**Comment by giampaolotrapasso** [comment]
I did a quick test with Sybase (https://hub.docker.com/r/nguoianphu/docker-sybase/) and https://github.com/confluentinc/kafka-connect-jdbc/pull/333. Worked fine for me with timestamp property.
