### ISSUE TITLE
Deadlock with big resultset in Ms Sql Server 

### ISSUE THREAD

**Issue by caiooliveiraeti** [confluentinc/kafka-connect-jdbc#361]
When I try use a query mode with Ms Sql Server and this query return a large resultset a connector stop work.

```
java.lang.Thread.State: RUNNABLE
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:171)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:1981)
    at com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6310)
    - locked <0x00000000f07a3f80> (a com.microsoft.sqlserver.jdbc.TDSReader)
    at com.microsoft.sqlserver.jdbc.TDSCommand.detach(IOBuffer.java:7207)
    at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2468)
    - locked <0x00000000f1600090> (a java.lang.Object)
    at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:219)
    at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:199)
    at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeQueryInternal(SQLServerStatement.java:661)
    at com.microsoft.sqlserver.jdbc.SQLServerConnection.isValid(SQLServerConnection.java:4998)
    at io.confluent.connect.jdbc.util.CachedConnectionProvider.getValidConnection(CachedConnectionProvider.java:69)
    - locked <0x00000000f07a40f0> (a io.confluent.connect.jdbc.util.CachedConnectionProvider)
    at io.confluent.connect.jdbc.source.JdbcSourceTask.poll(JdbcSourceTask.java:230)
    at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:179)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by gzeureka** [comment]
can addding "selectMethod" connection property to jdbc url help?

https://github.com/confluentinc/kafka-connect-jdbc/issues/375
