### ISSUE TITLE
com.microsoft.sqlserver.jdbc.SQLServerException: Column in table is of a type that is invalid for use as a key column in an index.

### ISSUE THREAD

**Issue by gmyrianthous** [confluentinc/kafka-connect-jdbc#379]
I am trying to run a sink in order to send data from a kafka topic to a Microsoft SQL Server however I get the following error: 

```
org.apache.kafka.connect.errors.RetriableException: com.microsoft.sqlserver.jdbc.SQLServerException: Column 'AC_NO' in table 'CUSTOMERS' is of a type that is invalid for use as a key column in an index.
        at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:84)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:495)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Column 'AC_NO' in table 'CUSTOMERS' is of a type that is invalid for use as a key column in an index.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:258)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1535)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:845)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:752)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7151)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2478)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:219)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:199)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeUpdate(SQLServerStatement.java:680)
        at io.confluent.connect.jdbc.sink.DbStructure.create(DbStructure.java:93)
        at io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:63)
        at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:78)
        at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:66)
        at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:69)
        ... 11 more

^C[2018-03-12 12:33:35,418] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect:65)
[2018-03-12 12:33:35,422] INFO Stopping REST server (org.apache.kafka.connect.runtime.rest.RestServer:154)
[2018-03-12 12:33:35,424] INFO Stopped ServerConnector@28ee0a2{HTTP/1.1}{0.0.0.0:9990} (org.eclipse.jetty.server.ServerConnector:306)
[2018-03-12 12:33:35,443] INFO Stopped o.e.j.s.ServletContextHandler@30233f0b{/,null,UNAVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:865)
[2018-03-12 12:33:35,445] INFO REST server stopped (org.apache.kafka.connect.runtime.rest.RestServer:165)
[2018-03-12 12:33:35,445] INFO Herder stopping (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:76)
[2018-03-12 12:33:35,446] INFO Stopping task sink-oracle-msql-0 (org.apache.kafka.connect.runtime.Worker:464)
[2018-03-12 12:33:35,447] INFO Stopping task (io.confluent.connect.jdbc.sink.JdbcSinkTask:96)
[2018-03-12 12:33:35,457] INFO Stopping connector sink-oracle-msql (org.apache.kafka.connect.runtime.Worker:304)
[2018-03-12 12:33:35,459] INFO Stopped connector sink-oracle-msql (org.apache.kafka.connect.runtime.Worker:320)
[2018-03-12 12:33:35,459] INFO Worker stopping (org.apache.kafka.connect.runtime.Worker:154)
[2018-03-12 12:33:35,459] INFO Stopped FileOffsetBackingStore (org.apache.kafka.connect.storage.FileOffsetBackingStore:67)
[2018-03-12 12:33:35,463] INFO Worker stopped (org.apache.kafka.connect.runtime.Worker:175)
[2018-03-12 12:33:35,465] INFO Herder stopped (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:86)
[2018-03-12 12:33:35,465] INFO Kafka Connect stopped (org.apache.kafka.connect.runtime.Connect:70)
```

And here's my sink file: 

```
name=sink-oracle-msql
connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
tasks.max=1
topics=CUSTOMERS
connection.url=jdbc:sqlserver://127.0.0.1:1234;DatabaseName=Giorgos;user=admin;password=admin
auto.create=true
pk.mode=record_value
pk.fields=AC_NO
insert.mode=upsert
transforms=ExtractField
transforms.ExtractField.type=org.apache.kafka.connect.transforms.ExtractField$Value
transforms.ExtractField.field=data

```

Does SQL server attempt to [create a key with type nvarchar(max)](https://stackoverflow.com/questions/2863993/is-of-a-type-that-is-invalid-for-use-as-a-key-column-in-an-index) and therefore this is the cause of the error? And if so, how can I fix this?

**Comment by HungUnicorn** [comment]
The Sybase sink implements such logic that if a string field is set as primary key, use a reasonable length
https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/dialect/SybaseDatabaseDialect.java#L124

Just implement this logic to the SqlServerDialect and it works.

**Comment by cyrusv** [comment]
Resolved with https://github.com/confluentinc/kafka-connect-jdbc/pull/673
