### ISSUE TITLE
java.lang.IllegalArgumentException: Number of groups must be positive

### ISSUE THREAD

**Issue by vinaykasam** [confluentinc/kafka-connect-jdbc#384]
I am getting this exception and not sure what is causing this . any help is appreciated 
Thank you

ERROR Stopping after connector error (org.apache.kafka                                                                                        .connect.cli.ConnectStandalone:108)
java.lang.IllegalArgumentException: Number of groups must be positive.

name=ehub-oracle-jdbc-autoincrement
connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
tasks.max=1
connection.password = XXXXX
connection.url = jdbc:oracle:thin:@va50dx05-scan2.XXxpoint.com:1525/ehu1d
connection.user = EHUB_MBR_SVCID
table.whitelist=EHUB_MBR_DOMN.EHUB_EMAIL
mode=timestamp
timestamp.column.name=LAST_UPDT_DTM
topic.prefix=ehub-oracle-jdbc-

**Comment by anandrajneesh** [comment]
Enable the debug logging, and see what output of tables you are getting from Oracle. Could be this issue : [https://rmoff.net/2016/07/27/kafka-connect-jdbc-number-of-groups-must-be-positive/]

**Comment by anning666** [comment]
Maybe the table does not exist

**Comment by momisabuilder** [comment]
table.whitelist=EHUB_MBR_DOMN.EHUB_EMAIL 改成：table.whitelist=EHUB_EMAIL

**Comment by a-titorenko** [comment]
I have same issue. The table is definitely exist as debug shows that is was found.

2018-12-27 17:02:50,325] DEBUG Got the following tables: ["test"."order_events"] (io.confluent.connect.jdbc.source.TableMonitorThread:141)
[2018-12-27 17:02:50,325] DEBUG Waiting 60000 ms to check for changed. (io.confluent.connect.jdbc.source.TableMonitorThread:84)
[2018-12-27 17:02:50,325] ERROR Failed to reconfigure connector's tasks, retrying after backoff: (org.apache.kafka.connect.runtime.distributed.DistributedHerder:966)
java.lang.IllegalArgumentException: Number of groups must be positive.
	at org.apache.kafka.connect.util.ConnectorUtils.groupPartitions(ConnectorUtils.java:41)
	at io.confluent.connect.jdbc.JdbcSourceConnector.taskConfigs(JdbcSourceConnector.java:148)
	at org.apache.kafka.connect.runtime.Worker.connectorTaskConfigs(Worker.java:305)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnector(DistributedHerder.java:1005)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnectorTasksWithRetry(DistributedHerder.java:958)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$900(DistributedHerder.java:111)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$17$1.call(DistributedHerder.java:971)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$17$1.call(DistributedHerder.java:968)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:271)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:220)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2018-12-27 17:02:50,325] ERROR Unexpected error during connector task reconfiguration:  (org.apache.kafka.connect.runtime.distributed.DistributedHerder:977)
[2018-12-27 17:02:50,325] ERROR Task reconfiguration for order-events-source-pg failed unexpectedly, this connector will not be properly reconfigured unless manually triggered. (org.apache.kafka.connect.runtime.distributed.DistributedHerder:978)
[2018-12-27 17:02:50,577] INFO SourceConnectorConfig values: 
	config.action.reload = RESTART
	connector.class = io.confluent.connect.jdbc.JdbcSourceConnector
	errors.log.enable = false
	errors.log.include.messages = false
	errors.retry.delay.max.ms = 60000
	errors.retry.timeout = 0
	errors.tolerance = none
	header.converter = null
	key.converter = class org.apache.kafka.connect.storage.StringConverter
	name = order-events-source-pg
	tasks.max = 2
	transforms = [InsertKey, ExtractId]
	value.converter = class org.apache.kafka.connect.json.JsonConverter
 (org.apache.kafka.connect.runtime.SourceConnectorConfig:279)
[2018-12-27 17:02:50,577] INFO EnrichedConnectorConfig values: 
	config.action.reload = RESTART
	connector.class = io.confluent.connect.jdbc.JdbcSourceConnector
	errors.log.enable = false
	errors.log.include.messages = false
	errors.retry.delay.max.ms = 60000
	errors.retry.timeout = 0
	errors.tolerance = none
	header.converter = null
	key.converter = class org.apache.kafka.connect.storage.StringConverter
	name = order-events-source-pg
	tasks.max = 2
	transforms = [InsertKey, ExtractId]
	transforms.ExtractId.field = order_id
	transforms.ExtractId.type = class org.apache.kafka.connect.transforms.ExtractField$Key
	transforms.InsertKey.fields = [order_id]
	transforms.InsertKey.type = class org.apache.kafka.connect.transforms.ValueToKey
	value.converter = class org.apache.kafka.connect.json.JsonConverter
 (org.apache.kafka.connect.runtime.ConnectorConfig$EnrichedConnectorConfig:279)

**Comment by sanket9394** [comment]
For me, table.whitelist values were CASE SENSITIVE  , that solved the issue
