### ISSUE TITLE
extend fields's name is not support prefix "@" ?

### ISSUE THREAD

**Issue by lemonl2** [confluentinc/kafka-connect-jdbc#426]
For example:
```java
 builder.field("@message", Schema.STRING_SCHEMA);
```

```
org.apache.avro.SchemaParseException: Illegal initial character: @message
	at org.apache.avro.Schema.validateName(Schema.java:1147)
	at org.apache.avro.Schema.access$200(Schema.java:81)
	at org.apache.avro.Schema$Field.<init>(Schema.java:403)
	at org.apache.avro.SchemaBuilder$FieldBuilder.completeField(SchemaBuilder.java:2124)
	at org.apache.avro.SchemaBuilder$FieldBuilder.completeField(SchemaBuilder.java:2120)
	at org.apache.avro.SchemaBuilder$FieldBuilder.access$5200(SchemaBuilder.java:2034)
	at org.apache.avro.SchemaBuilder$GenericDefault.noDefault(SchemaBuilder.java:2417)
	at io.confluent.connect.avro.AvroData.addAvroRecordField(AvroData.java:933)
	at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:832)
	at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:685)
	at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:680)
	at io.confluent.connect.avro.AvroData.fromConnectData(AvroData.java:325)
	at io.confluent.connect.avro.AvroConverter.fromConnectData(AvroConverter.java:74)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:228)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:194)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rhauch** [comment]
Avro is quite strict in the set of characters allowed in a field. The only way to address this is to avoid these characters, optionally using an SMT to rename columns/fields originating in a source connector.

I'm going to close this for now, since this is an underlying assumption in the original design of Connect schemas and their similarity to Avro.
