### ISSUE TITLE
Unable to connect to database, No suitable driver found for jdbc:postgresql

### ISSUE THREAD

**Issue by junaidrazzaq323** [confluentinc/kafka-connect-jdbc#433]
I am trying Kafka with Postgres Sink using JDBC-sink connector.

**Exception:**

```
INFO Unable to connect to database on attempt 1/3. Will retry in 10000 ms. (io.confluent.connect.jdbc.util.CachedConnectionProvider:91)
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/casb
at java.sql.DriverManager.getConnection(DriverManager.java:689)
    at java.sql.DriverManager.getConnection(DriverManager.java:247)
    at io.confluent.connect.jdbc.util.CachedConnectionProvider.newConnection(CachedConnectionProvider.java:85)
    at io.confluent.connect.jdbc.util.CachedConnectionProvider.getValidConnection(CachedConnectionProvider.java:68)
    at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:56)
    at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:69)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:495)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Sink.properties:**

```
name=test-sink
connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
tasks.max=1
topics=fp_test
connection.url=jdbc:postgresql://localhost:5432/casb
connection.user=admin
connection.password=***
auto.create=true
```

I have set `plugin.path=/usr/share/java/kafka-connect-jdbc`

On **/usr/share/java/kafka-connect-jdbc** I have the following files:

`kafka-connect-jdbc-4.0.0.jar`, `postgresql-9.4-1206-jdbc41.jar`, `sqlite-jdbc-3.8.11.2.jar` and some other jars that basically come packaged along with confluent.

I then downloaded postgres-jdbc driver jar `postgresql-42.2.2.jar`, copied it in the same folder and tried again. Still the same exception.

I have set **CLASSPATH** to `/usr/share/java/kafka-connect-jdbc` as well and I am running connect in distributed mode.

Kindly help me out with this.

**Comment by rhauch** [comment]
Set `plugin.path=/usr/share/java`. See [Installing Plugins](https://docs.confluent.io/current/connect/userguide.html#installing-plugins), where in this case `/usr/share/java/kafka-connect-jdbc` is a _plugin directory_ (i.e., the directory for the JDBC connector plugin) that is _inside_ one of the directories (e.g., `/usr/share/java`) on the plugin path. 

All JDBC-related JARs, including JDBC driver JARs, should be in the `/usr/share/java/kafka-connect-jdbc` directory so the JDBC connector plugin can find them. As you mention, the PG and Sqlite JDBC drivers are already there.

**Comment by junaidrazzaq323** [comment]
Setting `plugin.path=/usr/share/java` gives me the following exception:

```
[2018-06-25 19:08:02,383] ERROR WorkerSinkTask{id=jdbc-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:515)
java.lang.NoClassDefFoundError: Could not initialize class org.apache.calcite.jdbc.Driver
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.sql.DriverManager.isDriverAllowed(DriverManager.java:556)
	at java.sql.DriverManager.getConnection(DriverManager.java:661)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.newConnection(CachedConnectionProvider.java:85)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.getValidConnection(CachedConnectionProvider.java:68)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:56)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:69)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:495)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rhauch** [comment]
Did you put the Calcite JDBC driver inside the `/usr/share/java/kafka-connect-jdbc` directory?

**Comment by Gelassen** [comment]
@rhauch , does it still valid? In many places I noticed it is enough to put it under ```/usr/share/java```, another one subdirectory is not required.
