### ISSUE TITLE
Kafka Connector not working with couchbase - OutOfMemory Error

### ISSUE THREAD

**Issue by ronakpandya7** [confluentinc/kafka-connect-jdbc#468]
Hello All,

We are using kafka connector with couchbase to transfer bulk of the data into kafka.
When we tried with only 5000 couchbase docs it worked fine, but when we increase the documents to 1 million we got below error in kafka-connector aftre getting some of the data (Approx. 5000)). 

Version:
```
kafka-connector version : 3.2.3
couchbase version : 5.0.1
kafka version : 2.12-0.11.0.2
```
  
Kafka-Connector Logs:

```
[2018-08-16 14:33:34,661] ERROR Failed to flush WorkerSourceTask{id=TestConnector-2-3}, timed out while waiting for producer to flush outstanding 3495 messages (org.apache.kafka.connect.runtime.WorkerSourceTask:306)
[2018-08-16 14:34:02,135] ERROR Uncaught exception in kafka-producer-network-thread | producer-2:  (org.apache.kafka.common.utils.KafkaThread:43)
java.lang.OutOfMemoryError: Java heap space
[2018-08-16 14:34:02,135] ERROR Uncaught exception in kafka-producer-network-thread | producer-10:  (org.apache.kafka.common.utils.KafkaThread:43)
java.lang.OutOfMemoryError: Java heap space
 at java.util.HashMap$EntrySet.iterator(HashMap.java:1014)
 at java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$1.<init>(Collections.java:1655)
 at java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.iterator(Collections.java:1654)
 at org.apache.kafka.clients.producer.internals.RecordAccumulator.ready(RecordAccumulator.java:365)
 at org.apache.kafka.clients.producer.internals.Sender.sendProducerData(Sender.java:230)
 at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:223)
 at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:162)
 at java.lang.Thread.run(Thread.java:748)
[2018-08-16 14:34:00,931] ERROR Uncaught exception in kafka-producer-network-thread | producer-7:  (org.apache.kafka.common.utils.KafkaThread:43)
java.lang.OutOfMemoryError: Java heap space
 at java.lang.Integer.valueOf(Integer.java:832)
 at sun.nio.ch.EPollSelectorImpl.updateSelectedKeys(EPollSelectorImpl.java:120)
 at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:98)
 at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
 at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
 at org.apache.kafka.common.network.Selector.select(Selector.java:529)
 at org.apache.kafka.common.network.Selector.poll(Selector.java:321)
 at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:433)
 at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:224)
 at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:162)
 at java.lang.Thread.run(Thread.java:748)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "kafka-producer-network-thread | producer-27"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "kafka-producer-network-thread | producer-18"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "kafka-producer-network-thread | producer-26"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "kafka-producer-network-thread | producer-11"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "kafka-producer-network-thread | producer-21"
```

Kafka-Connector Config:

```
quickstart-couchbase-sink.properties
  tasks.max=2
  topics=couchbase-sink-example 
  connection.timeout.ms=2000
  couchbase.durability.persist_to=NONE
  couchbase.durability.replicate_to=NONE 
  key.converter=org.apache.kafka.connect.storage.StringConverter                                                     
  value.converter=org.apache.kafka.connect.json.JsonConverter                                                        
  value.converter.schemas.enable=false
  
quickstart-couchbase-source.properties
  tasks.max=30
  topic.name=test-topic
  connection.cluster_address=svc-couchbase-test-2.ns-test
  connection.timeout.ms=2000
  use_snapshots=false
  couchbase.stream_from=BEGINNING
  couchbase.compression=DISABLED
```

We followed this [link](https://developer.couchbase.com/documentation/server/5.0/connectors/kafka-3.2/kafka-intro.html) to check compability and config.
 
We have also gone through this [link](https://forums.couchbase.com/t/kafka-connect-couchbase-connector-stops-working/15011/12), and did necessary changes for the snapshots, but still it is not working.

So what we can do in this case?

Thanks in advance :)

**Comment by cricket007** [comment]
`export KAFKA_HEAP_OPTS` to a value higher than the defaults (2g as of latest releases). 

Note: Couchbase has their own connector. Not sure why you would want to use JDBC. https://github.com/couchbase/kafka-connect-couchbase
