### ISSUE TITLE
confluent-5.0.0: Failed to find any class that implements Connector and which name matches io.confluent.connect.jdbc .JdbcSourceConnector

### ISSUE THREAD

**Issue by balareddy** [confluentinc/kafka-connect-jdbc#476]
The connect-standalone.bat fails with the below error. started the zookeeper, kafka and then the standalone connector. even the connect-distributed.bat doesn't work. Could you please help resolve?
It will be helpful if you have a working example.

kafka-connect-jdbc/source-quickstart-oracle_local2.properties contents are below. kafka-connect-jdbc-5.0.0.jar, ojdbc6-12.1.0.2.0.jar are in confluent-5.0.0\share\java\kafka-connect-jdbc folder.

name=test-source-local-oracle-jdbc-local
connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
tasks.max=1
poll.interval.ms=1000
connection.url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=6124)))(CONNECT_DATA=(SERVICE_NAME=LOCAL_localhost)))
connection.user=xxxxx
connection.password=xxxxxx
query=select EVENT_ID, COMPOSE(ID) AS TXN_ID,UPDT_TS from EVENT_LOG
mode=timestamp+incrementing
incrementing.column.name=EVENT_ID
timestamp.column.name=UPDT_TS
topic.prefix=EVENTS
validate.non.null=false

\confluent-5.0.0\bin\windows

zookeeper-server-start.bat ../../etc/kafka/zookeeper.properties
kafka-server-start.bat ../../etc/kafka/server.properties
connect-standalone.bat ../../etc/kafka/connect-standalone.properties ../../etc/kafka-connect-jdbc/source-quickstart-oracle_local2.properties

plugin.path is commented in connect-standalone.properties

1) Getting a lot of Reflections warnings. is there a way to disable these warnings?

[2018-08-28 17:31:10,283] WARN could not get type for name org.osgi.util.tracker.ServiceTracker from any class loader (org.reflections.Reflections)
org.reflections.ReflectionsException: could not get type for name org.osgi.util.tracker.ServiceTracker
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
        at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
        at org.reflections.Reflections.<init>(Reflections.java:126)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader$InternalReflections.<init>(DelegatingClassLoader.java:406)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanPluginPath(DelegatingClassLoader.java:306)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanUrlsAndAddPlugins(DelegatingClassLoader.java:240)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initPluginLoader(DelegatingClassLoader.java:188)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initLoaders(DelegatingClassLoader.java:181)
        at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:61)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:77)
Caused by: java.lang.ClassNotFoundException: org.osgi.util.tracker.ServiceTracker
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
        ... 9 more
[2018-08-28 17:31:10,356] WARN could not get type for name org.eclipse.jetty.npn.NextProtoNego$ServerProvider from any class loader (org.reflections.Reflections
)
org.reflections.ReflectionsException: could not get type for name org.eclipse.jetty.npn.NextProtoNego$ServerProvider
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
        at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
        at org.reflections.Reflections.<init>(Reflections.java:126)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader$InternalReflections.<init>(DelegatingClassLoader.java:406)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanPluginPath(DelegatingClassLoader.java:306)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanUrlsAndAddPlugins(DelegatingClassLoader.java:240)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initPluginLoader(DelegatingClassLoader.java:188)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initLoaders(DelegatingClassLoader.java:181)
        at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:61)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:77)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.npn.NextProtoNego$ServerProvider
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
        ... 9 more

2)  Getting error: Failed to find any class that implements Connector and which name matches io.confluent.connect.jdbc
.JdbcSourceConnector

ss org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='2.0.0-cp1', encodedVersio
n=2.0.0-cp1, type=source, typeName='source', location='classpath'}
        at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:79)
        at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:66)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:110)
Caused by: org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements Connector and which name matches io.confluent.connect.jdbc
.JdbcSourceConnector, available connectors are: PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSinkConnector, name='org.apache.kafka.connect.fil
e.FileStreamSinkConnector', version='2.0.0-cp1', encodedVersion=2.0.0-cp1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.
kafka.connect.file.FileStreamSourceConnector, name='org.apache.kafka.connect.file.FileStreamSourceConnector', version='2.0.0-cp1', encodedVersion=2.0.0-cp1, typ
e=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockConnector, name='org.apache.kafka.connect.tools.Mo
ckConnector', version='2.0.0-cp1', encodedVersion=2.0.0-cp1, type=connector, typeName='connector', location='classpath'}, PluginDesc{klass=class org.apache.kafk
a.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='2.0.0-cp1', encodedVersion=2.0.0-cp1, type=sink, typeName='
sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnecto
r', version='2.0.0-cp1', encodedVersion=2.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.
SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='2.0.0-cp1', encodedVersion=2.0.0-cp1, type=source, typeName='source
', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConn
ector', version='2.0.0-cp1', encodedVersion=2.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.to
ols.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='2.0.0-cp1', encodedVersion=2.0.0-cp1, type=source, type
Name='source', location='classpath'}
        at org.apache.kafka.connect.runtime.isolation.Plugins.newConnector(Plugins.java:179)
        at org.apache.kafka.connect.runtime.AbstractHerder.getConnector(AbstractHerder.java:374)
        at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:253)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:189)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:107)

**Comment by mariusneo** [comment]
do you have the oracle jdbc driver library in the `{confluent.installation.dir}/share/java/kafka-connect-jdbc` directory?

**Comment by aliasbadwolf** [comment]
@balareddy  "plugin.path is commented in connect-standalone.properties" this is the culprit in your case. Uncomment plugin.path as

**plugin.path=/Fully/Qualified/Path/To/confluent-5.0.0\share\java\kafka-connect-jdbc**

Also, you do not need oracle JDBC jar there in the plugin path. Oracle JDBC jar should be in Confluent lib/jar directory.

**Comment by kkonstantine** [comment]
When installing from the archive package it's not easy to make a guess as to where the confluent platform has been installed and therefore guess what the `plugin.path` should be. Setting manually or using confluent-hub-client to install a connector should allow you to set the `plugin.path` in your environment. 

Since this is a configuration issue, I'll go ahead and close it.

**Comment by mbsj6962** [comment]
Failed to find any class that implements Connector and which name matches io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector

When I want to connect to xml file and read some data, I have this problem ! 
Can you guys help ??
