### ISSUE TITLE
NullPointerException when using <table>.<column>

### ISSUE THREAD

**Issue by sajmmon** [confluentinc/kafka-connect-jdbc#500]
Hi,
I get a NullPointerException when I have a query with columns prefixed with table name:
`[2018-10-09 12:54:17,905] ERROR WorkerSourceTask{id=jdbc-source-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
java.lang.NullPointerException
	at io.confluent.connect.jdbc.source.TimestampIncrementingCriteria.extractOffsetIncrementedId(TimestampIncrementingCriteria.java:231)
	at io.confluent.connect.jdbc.source.TimestampIncrementingCriteria.extractValues(TimestampIncrementingCriteria.java:189)
	at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.extractRecord(TimestampIncrementingTableQuerier.java:187)
	at io.confluent.connect.jdbc.source.JdbcSourceTask.poll(JdbcSourceTask.java:297)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:244)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:220)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

This happens for following sqlite database:
`sqlite3 test.db

CREATE TABLE accounts(id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(255));
INSERT INTO accounts(name) VALUES('alice');
INSERT INTO accounts(name) VALUES('bob');
INSERT INTO accounts(name) VALUES('cathy');
INSERT INTO accounts(name) VALUES('foo');`

And following connector configuration:
`name=join
connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
tasks.max=1
query=SELECT accounts.id, accounts.name FROM accounts
connection.url=jdbc:sqlite:test.db
mode=incrementing
incrementing.column.name=accounts.id
topic.prefix=join
`

It seems the problem is triggered in: https://github.com/confluentinc/kafka/blob/5.0.0-post/connect/api/src/main/java/org/apache/kafka/connect/data/ConnectSchema.java#L187

Where Map fieldsByName stores column names without <table>. prefix.

I get the problem with Confluent Platform 5.0.0.

**Comment by viniciusfaleiro** [comment]
Same thing here. Did you solve this?
` [2019-05-25 15:41:41,584] ERROR WorkerSourceTask{id=SQLServerSource-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
connect            | java.lang.NullPointerException
connect            | 	at io.confluent.connect.jdbc.source.TimestampIncrementingCriteria.extractOffsetIncrementedId(TimestampIncrementingCriteria.java:237)
connect            | 	at io.confluent.connect.jdbc.source.TimestampIncrementingCriteria.extractValues(TimestampIncrementingCriteria.java:195)
connect            | 	at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.extractRecord(TimestampIncrementingTableQuerier.java:192)
connect            | 	at io.confluent.connect.jdbc.source.JdbcSourceTask.poll(JdbcSourceTask.java:315)
connect            | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:245)
connect            | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:221)
connect            | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
connect            | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
connect            | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
connect            | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
connect            | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
connect            | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
connect            | 	at java.lang.Thread.run(Thread.java:748)
`

`INFO JdbcSourceTaskConfig values: 
connect            | 	batch.max.rows = 100
connect            | 	catalog.pattern = null
connect            | 	connection.attempts = 3
connect            | 	connection.backoff.ms = 10000
connect            | 	connection.password = [hidden]
connect            | 	connection.url = [hidden]
connect            | 	connection.user = admin
connect            | 	db.timezone = UTC
connect            | 	dialect.name = 
connect            | 	incrementing.column.name = mse.ID_Mensagem
connect            | 	mode = incrementing
connect            | 	numeric.mapping = null
connect            | 	numeric.precision.mapping = false
connect            | 	poll.interval.ms = 5000
connect            | 	query = select  mse.ID_Mensagem, mse.NsuOrigem, cto.cartao from MensagensEntrada mse inner join MensagensSaida mss on  mse.ID_Mensagem = mss.id_Mensagem inner join Cartoes cto on  mse.Cartao = cto.Cartao
connect            | 	quote.sql.identifiers = NEVER
connect            | 	schema.pattern = null
connect            | 	table.blacklist = []
connect            | 	table.poll.interval.ms = 60000
connect            | 	table.types = [TABLE]
connect            | 	table.whitelist = []
connect            | 	tables = []
connect            | 	timestamp.column.name = []
connect            | 	timestamp.delay.interval.ms = 0
connect            | 	topic.prefix = autorizacao
connect            | 	validate.non.null = true
connect            |  (io.confluent.connect.jdbc.source.JdbcSourceTaskConfig)
`
