### ISSUE TITLE
Kafka Connector stop if connection with database break with Sink Connector 

### ISSUE THREAD

**Issue by ukotdiya** [confluentinc/kafka-connect-jdbc#515]
Kafka Connector stop if connection with database break with Sink Connector. There should be retry in Sink connector as well. This is available in source connector

**Comment by mariusneo** [comment]
I've tried to execute the following scenario:

- started sqlite (accounts example from kafka-connect-jdbc) as source
- started postgres as sink

After successfully filling the sink database table, i've stopped postgresql for a few minutes.

Via  
```
./confluent log connect
````

the following information was provided:

```
ERROR WorkerSinkTask{id=test-posgtres-sink-0} Task thr
ew an uncaught and unrecoverable exception. Task is being killed and will not re
cover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask
:584)
```

After restarting postgresql service on my machine, I still see both jdbc connectors (sqlite source and postgres sink):

```
➜  curl localhost:8083/connectors | jq
[
  "test-source-sqlite-jdbc-autoincrement",
  "test-posgtres-sink"
]
```

but the postgres sink connector has no status

```
➜  curl -s localhost:8083/connectors/test-postgres-sink/status | jq 
{
  "error_code": 404,
  "message": "No status found for connector test-postgres-sink"
}
```

and restarting the connector via 

```
➜  bin curl -s -X POST localhost:8083/connectors/test-postgres-sink/restart | jq
{
  "error_code": 404,
  "message": "Unknown connector: test-postgres-sink"
}
```

is also not working.


@ukotdiya  : Having a rather big number (by default is 3, and `connection.backoff.ms` is set by default to 10 seconds - so after 30 seconds of db outage the connector stops) for `connection.attempts` configuration of the jdbc connector could help out to overcome a db outage


@rhauch what is the common procedure in dealing with db outages. Say that the db goes down for a few minutes and the db admin then gets it running again. How can the connector be restarted without human intervention (relying on the fact that a sysadmin will restart kafka-connect after restarting the database is not always going to work) ?

**Comment by avocader** [comment]
Hi @ukotdiya ,

As @mariusneo mentioned - JDBC *Source* has two configuration properties(`connection.backoff.ms` and `connection.attempts`), which you want to tune in order to tolerate relatively long database outages.

However, JDBC *Sink* has different retry configuration parameters(`max.retries` and `retry.backoff.ms`) - please refer to [documentation](https://docs.confluent.io/3.1.1/connect/connect-jdbc/docs/sink_config_options.html#retries).
JDBC Sink does have connection retry logic, but it uses defaults as `connection.attempts=3` and `connection.backoff.ms=10000`.
Put it all together, the total number of attempts is a product of `max.retries` and `connection.attempts`.

I am marking this as an enhancement, but meanwhile - you can increase `max.retries` and `retry.backoff.ms` to accomplish a desired outage toleration window.

Thanks.

**Comment by cobolbaby** [comment]
```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.ConnectException: org.postgresql.util.PSQLException: The connection attempt failed.
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:69)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:56)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)
	... 10 more
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:272)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:52)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:216)
	at org.postgresql.Driver.makeConnection(Driver.java:404)
	at org.postgresql.Driver.connect(Driver.java:272)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.getConnection(GenericDatabaseDialect.java:211)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.newConnection(CachedConnectionProvider.java:88)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:62)
	... 13 more
Caused by: java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.postgresql.core.PGStream.<init>(PGStream.java:61)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:144)
```
