### ISSUE TITLE
mysql connect-jdbc issue

### ISSUE THREAD

**Issue by dreamcatchernick** [confluentinc/kafka-connect-jdbc#523]
Hi , I am trying to move source data in mysql 5.7 to target database  mysql 5.7.  i am using debezium as my source connector.  
When i insert data to source database table , the sink connector(kafka-connect-jdbc) threw exception below:

```
ERROR WorkerSinkTask{id=sink-jdbc-connector-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:586)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.ConnectException: java.sql.SQLException: java.sql.BatchUpdateException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`table_a`(`name`) VALUES('abc')' at line 1
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`table_a`(`name`) VALUES('abc')' at line 1
        at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:88)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
        ... 10 more

```

my debezium config is:
```
{
	"name": "source-mysql-connector",
	"config": {
		"connector.class": "io.debezium.connector.mysql.MySqlConnector",
		"database.hostname": "source-mysql",
		"database.port": "3306",
		"database.user": "root",
		"database.password": "xxxxx",
		"database.server.id": "2",
		"database.server.name": "nick",
		"database.history.kafka.bootstrap.servers": "localhost:9092",
		"database.history.kafka.topic": "dbhistory.nick" ,
		"database.whitelist": "nick",
		"include.schema.changes": "true",
		"transforms": "unwrap",
		"transforms.unwrap.type": "io.debezium.transforms.UnwrapFromEnvelope",
		"transforms.unwrap.drop.tombstones":"false",
		"transforms.unwrap.drop.deletes":"false"
	}
}

```

jdbc connector config is:

```
{
  "name": "sink-jdbc-connector",
  "config": {
    "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
    "tasks.max": "1",
    "topics": "nick.nick.table_a",
    "connection.url": "jdbc:mysql://mysql-target:3306/nick",
    "connection.user": "root",
    "connection.password": "xxxxx",
    "insert.mode": "insert",
	"auto.evolve": "false",
	"auto.create": "false"
  }
}
```
Please help..

**Comment by dreamcatchernick** [comment]
problem solved by adding "table.name.format" to sink-jdbc-connect config, the value should be "[database].[tablename]"
