### ISSUE TITLE
When Mode=Bulk : Unhandled exception when committing WorkerSourceTask{id=***}:  (org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter:118) java.lang.NullPointerException

### ISSUE THREAD

**Issue by Astn** [confluentinc/kafka-connect-jdbc#54]
I'm using Confluent 2.0.1-2.11.7 from: http://packages.confluent.io/archive/2.0/confluent-2.0.1-2.11.7.tar.gz

Here is the environment of each of my nodes. I'm running in docker.
```
/opt/confluent-2.0.1 # export
export ALPINE_GLIBC_URL='https://circle-artifacts.com/gh/andyshinn/alpine-pkg-glibc/6/artifacts/0/home/ubuntu/alpine-pkg-glibc/packages/x86_64/'
export CONFLUENT_VERSION='2.0.1-2.11.7'
export DOCKERIZE_VERSION='0.2.0'
export GLIBC_BIN_PKG='glibc-bin-2.21-r2.apk'
export GLIBC_PKG='glibc-2.21-r2.apk'
export HOME='/root'
export HOSTNAME='bf08d841be2d'
export JAVA_HOME='/opt/jdk'
export JAVA_PACKAGE='jdk'
export JAVA_VERSION_BUILD='14'
export JAVA_VERSION_MAJOR='8'
export JAVA_VERSION_MINOR='45'
export PATH='/opt/confluent-2.0.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/jdk/bin'
export PWD='/opt/confluent-2.0.1'
export SHLVL='1'
export TERM='xterm'
/opt/confluent-2.0.1 # 
```
Here is the dockerfile I base it all off of.
```
FROM java-oracle8-alpine #if you need these base images as well I can post them.

RUN apk add --update bash unzip wget curl git jq # good

ENV CONFLUENT_VERSION="2.0.1-2.11.7"
# ENV KAFKA_VERSION="0.8.2.2" SCALA_VERSION="2.11"

RUN cd /opt && \
    mirror="http://packages.confluent.io/archive/2.0/" && \
    url="${mirror}confluent-${CONFLUENT_VERSION}.tar.gz" && \
    curl "${url}" | tar xzf - && \
    curl "http://cdn.mysql.com/Downloads/Connector-J/mysql-connector-java-5.1.38.tar.gz" | tar xzf - && \
    cp ./mysql-connector-java-5.1.38/*.jar ./confluent-2.0.1/share/java/kafka-connect-jdbc/ && \
    curl "https://download.microsoft.com/download/0/2/A/02AAE597-3865-456C-AE7F-613F99F850A8/sqljdbc_6.0.6629.101_enu.tar.gz" | tar xzf - && \
    cp sqljdbc_6.0/enu/sqljdbc42.jar ./confluent-2.0.1/share/java/kafka-connect-jdbc/
    # cd confluent-2.0.1 && \

ENV PATH="/opt/confluent-2.0.1/bin:$PATH"
WORKDIR "/opt/confluent-2.0.1"

ENTRYPOINT ["sh"]
```

I'm getting the following error while running a single table import test against a distributed setup:
```
[2016-03-17 20:50:28,093] INFO Joined group and got assignment: Assignment{error=0, leader='connect-1-f84f1dc6-4aab-4af3-ae8b-ae3d1a9d6a24', leaderUrl='http://172.24.0.4:8083/', offset=7, connectorIds=[], taskIds=[test-mysql-jdbc-source-0]} (org.apache.kafka.connect.runtime.distributed.DistributedHerder:868)
[2016-03-17 20:50:28,093] INFO Starting connectors and tasks using config offset 7 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:639)
[2016-03-17 20:50:28,093] INFO Starting task test-mysql-jdbc-source-0 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:650)
[2016-03-17 20:50:28,093] INFO TaskConfig values: 
	task.class = class io.confluent.connect.jdbc.JdbcSourceTask
 (org.apache.kafka.connect.runtime.TaskConfig:165)
[2016-03-17 20:50:28,093] INFO Creating task test-mysql-jdbc-source-0 (org.apache.kafka.connect.runtime.Worker:256)
[2016-03-17 20:50:28,094] INFO Instantiated task test-mysql-jdbc-source-0 with version 2.0.1 of type io.confluent.connect.jdbc.JdbcSourceTask (org.apache.kafka.connect.runtime.Worker:267)
[2016-03-17 20:50:28,094] INFO Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:659)
[2016-03-17 20:50:28,094] INFO JdbcSourceTaskConfig values: 
	mode = bulk
	timestamp.column.name = 
	incrementing.column.name = id
	topic.prefix = mysql-jdbc-
	tables = [country]
	poll.interval.ms = 300000
	query = 
	batch.max.rows = 100
	connection.url = jdbc:mysql://mysql:3306/ctliveimport2?useSSL=false&user=****&password=****
	table.blacklist = []
	table.poll.interval.ms = 60000
	table.whitelist = [****]
 (io.confluent.connect.jdbc.JdbcSourceTaskConfig:135)
[2016-03-17 20:50:28,097] INFO Source task Thread[WorkerSourceTask-test-mysql-jdbc-source-0,5,main] finished initialization and start (org.apache.kafka.connect.runtime.WorkerSourceTask:342)
[2016-03-17 20:51:28,095] ERROR Unhandled exception when committing WorkerSourceTask{id=test-mysql-jdbc-source-0}:  (org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter:118)
java.lang.NullPointerException
	at org.apache.kafka.connect.storage.KafkaOffsetBackingStore.set(KafkaOffsetBackingStore.java:121)
	at org.apache.kafka.connect.storage.OffsetStorageWriter.doFlush(OffsetStorageWriter.java:162)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.commitOffsets(WorkerSourceTask.java:267)
	at org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter.commit(SourceTaskOffsetCommitter.java:110)
	at org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter$1.run(SourceTaskOffsetCommitter.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-03-17 20:52:28,095] ERROR Invalid call to OffsetStorageWriter flush() while already flushing, the framework should not allow this (org.apache.kafka.connect.storage.OffsetStorageWriter:108)
[2016-03-17 20:52:28,095] ERROR Unhandled exception when committing WorkerSourceTask{id=test-mysql-jdbc-source-0}:  (org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter:118)
org.apache.kafka.connect.errors.ConnectException: OffsetStorageWriter is already flushing
	at org.apache.kafka.connect.storage.OffsetStorageWriter.beginFlush(OffsetStorageWriter.java:110)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.commitOffsets(WorkerSourceTask.java:227)
	at org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter.commit(SourceTaskOffsetCommitter.java:110)
	at org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter$1.run(SourceTaskOffsetCommitter.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

Here is my setup:

```
#topics
./bin/kafka-topics --zookeeper $ZOOKEEPER_NODES_DNS --create --topic "connect-configs" --replication-factor 1 --partitions 1 \
./bin/kafka-topics --zookeeper $ZOOKEEPER_NODES_DNS --create --topic "connect-offsets" --replication-factor 1 --partitions 16 \
```

Env

```
ENV CONSUMER_SCHEMA_REGISTRY_URL="http://schema-registry:8081"
ENV ZOOKEEPER_NODES_DNS="zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
ENV KAFKA_BROKER_LIST="kafka1:9092,kafka2:9092,kafka3:9092"
```

Using Connect-Avro-Distributed with:

```
# Bootstrap Kafka servers. If multiple servers are specified, they should be comma-separated.
bootstrap.servers=kafka1:9092,kafka2:9092,kafka3:9092

# The group ID is a unique identifier for the set of workers that form a single Kafka Connect
# cluster
group.id=connect-cluster

# The converters specify the format of data in Kafka and how to translate it into Connect data.
# Every Connect user will need to configure these based on the format they want their data in
# when loaded from or stored into Kafka
key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://schema-registry:8081
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=http://schema-registry:8081

# The internal converter used for offsets and config data is configurable and must be specified,
# but most users will always want to use the built-in default. Offset and config data is never
# visible outside of Connect in this format.
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false

# Kafka topic where connector configuration will be persisted. You should create this topic with a
# single partition and high replication factor (e.g. 3)
config.storage.topic=connect-configs

# Kafka topic where connector offset data will be persisted. You should create this topic with many
# partitions (e.g. 25) and high replication factor (e.g. 3)
offset.storage.topic=connect-offsets
```

I've made the mysqlJDBC available on the classpath, and am submitting the job to a 3 worker connect setup.
Here is the job I'm submitting.

```
{
                        "name": "test-mysql-jdbc-source",
                        "config": {
                            "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
                            "tasks.max": "10",
                            "topic.prefix": "mysql-jdbc-",
                            "connection.url":"jdbc:mysql://mysql:3306/ctliveimport2?useSSL=false&user=$user&password=$password",
                            "table.whitelist":"smalltable",
                            "poll.interval.ms":300000,
                            "mode":"bulk",
                            "incrementing.column.name":"id"
                        }
                    }
```

It appears to be related to the OffsetStorageWriter as that is also in the call stack for both errors in the log. It made me think that I had my topics set-up incorrectly. Here is the results of kafka-topic list

```
-------Listing Topics in Kafka...
./bin/kafka-topics --zookeeper zookeeper1:2181,zookeeper2:2181,zookeeper3:2181 --describe --topic connect-configs
Topic:connect-configs	PartitionCount:1	ReplicationFactor:1	Configs:
	Topic: connect-configs	Partition: 0	Leader: 3	Replicas: 3	Isr: 3
./bin/kafka-topics --zookeeper zookeeper1:2181,zookeeper2:2181,zookeeper3:2181 --describe --topic connect-offsets
Topic:connect-offsets	PartitionCount:16	ReplicationFactor:1	Configs:
	Topic: connect-offsets	Partition: 0	Leader: 1	Replicas: 1	Isr: 1
	Topic: connect-offsets	Partition: 1	Leader: 2	Replicas: 2	Isr: 2
	Topic: connect-offsets	Partition: 2	Leader: 3	Replicas: 3	Isr: 3
	Topic: connect-offsets	Partition: 3	Leader: 1	Replicas: 1	Isr: 1
	Topic: connect-offsets	Partition: 4	Leader: 2	Replicas: 2	Isr: 2
	Topic: connect-offsets	Partition: 5	Leader: 3	Replicas: 3	Isr: 3
	Topic: connect-offsets	Partition: 6	Leader: 1	Replicas: 1	Isr: 1
	Topic: connect-offsets	Partition: 7	Leader: 2	Replicas: 2	Isr: 2
	Topic: connect-offsets	Partition: 8	Leader: 3	Replicas: 3	Isr: 3
	Topic: connect-offsets	Partition: 9	Leader: 1	Replicas: 1	Isr: 1
	Topic: connect-offsets	Partition: 10	Leader: 2	Replicas: 2	Isr: 2
	Topic: connect-offsets	Partition: 11	Leader: 3	Replicas: 3	Isr: 3
	Topic: connect-offsets	Partition: 12	Leader: 1	Replicas: 1	Isr: 1
	Topic: connect-offsets	Partition: 13	Leader: 2	Replicas: 2	Isr: 2
	Topic: connect-offsets	Partition: 14	Leader: 3	Replicas: 3	Isr: 3
	Topic: connect-offsets	Partition: 15	Leader: 1	Replicas: 1	Isr: 1
./bin/kafka-topics --zookeeper zookeeper1:2181,zookeeper2:2181,zookeeper3:2181 --describe --topic metrics
Topic:metrics	PartitionCount:1	ReplicationFactor:1	Configs:
	Topic: metrics	Partition: 0	Leader: 2	Replicas: 2	Isr: 2
-------End Listing...
```

Any ideas?

**Comment by DCameronMauch** [comment]
It appears that the exception in the set method in KafkaOffsetBackingStore on line 121 results in the handleFinishWrite method in OffsetStorageWriter to never run.  Thus the "toFlush" variable remains non-null forever.  Which causes all the following error messages from method beginFlush in OffsetStorageWriter on line 110.

**Comment by SmedbergM** [comment]
It also looks like `SetCallbackFuture` is implementing `org.apache.kafka.clients.producer.Callback` incorrectly. That interface specifies that when `callback.onCompletion(metadata, exception)` is called, exactly one of `metadata` and `exception` must be non-`null`. However, on line 166 of `KafkaOffsetBackingStore.java`, this method is called with both parameters `null`, and on line 157 it is called with the exception in the first slot instead of the second.

**Comment by Ishiihara** [comment]
@Astn I think the null exception is from "mode = bulk". In this case, no offset information will be saved in the `SourceRecord` and we instead pass in `null` for offset when constructing `SourceRecord`. Can you try to set "mode=incrementing" to see whether the exception still exists?

**Comment by Astn** [comment]
Yeah, I'll check that out.

**Comment by Astn** [comment]
@Ishiihara Thanks for the tip! Bulk does seem to be part of the problem. This error does go away when I change the mode to incrementing.

**Comment by SmedbergM** [comment]
Tracked down a [similar issue](https://github.com/apache/kafka/pull/1186) today, triggered when validating records against the schema registry:

**Comment by muftring** [comment]
does this need to be added as a JIRA? if so, can anyone open an issue there?

**Comment by gauravnanda79** [comment]
Can this error be ignored in Bulk mode ?

**Comment by ewencp** [comment]
Yes, this appears to be a bug in the implementation of the Connect framework, not the connector itself.

**Comment by gauravnanda79** [comment]
Are there any side effects of this bug ? Or can we ignore this error and continue using the connector in Bulk mode ?

Are any messages lost due to this ?

**Comment by shikhar** [comment]
This is fixed with https://issues.apache.org/jira/browse/KAFKA-3500 (Kafka 0.10.0.1, CP 3.0.1)

@gauravnanda79 in bulk mode, I believe this error should not pose a problem (@ewencp correct me if I'm wrong)

**Comment by gauravnanda79** [comment]
thanks @shikhar
