### ISSUE TITLE
Unable to load data into Redshift with Redshift JDBC driver

### ISSUE THREAD

**Issue by Hoiy** [confluentinc/kafka-connect-jdbc#542]
I am using docker `confluentinc/cp-kafka-connect:5.0.1` image to setup a AWS Redshift sink with the latest [Redshift JDBC driver](https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/1.2.16.1027/RedshiftJDBC42-1.2.16.1027.jar). The topic is in avro format.

Below is the configuration of my connector:
```name=<name>
connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
tasks.max=1

topics=<my_topic>
connection.url=jdbc:redshift://<mycluster>:5439/<mydatabase>
connection.user=<user>
connection.password=<password>

table.name.format=${topic}
pk.mode=record_value
pk.fields=my_record_id

auto.create=true
insert.mode=upsert
```

And got the following errors on starting the connector.
```
[2018-12-10 10:03:54,973] ERROR WorkerSinkTask{id=cms_article_sink_redshift-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:584)
org.apache.kafka.connect.errors.ConnectException: null (INT8) type doesn't have a mapping to the SQL database column type
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.getSqlType(GenericDatabaseDialect.java:1688)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.writeColumnSpec(GenericDatabaseDialect.java:1606)
```

I have also try running the same config with postgresql connector over Redshift, it failed at inserting the data probably due to data format issues, but at least it started inserting data. Any idea on how should I work around this problem?

**Comment by Hoiy** [comment]
Just know that this is not supported

**Comment by sunnikumar** [comment]
connection.user = null
	fields.whitelist = []
	insert.mode = insert
	max.retries = 10
	pk.fields = []
	pk.mode = none
	retry.backoff.ms = 3000
	table.name.format = ${topic}
 (io.confluent.connect.jdbc.sink.JdbcSinkConfig:279)
[2020-04-28 20:02:34,605] INFO Initializing writer using SQL dialect: GenericDialect (io.confluent.connect.jdbc.sink.JdbcSinkTask:52)
[2020-04-28 20:02:34,605] INFO WorkerSinkTask{id=redshift-sink-4} Sink task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask:282)
[2020-04-28 20:02:34,628] WARN [Consumer clientId=consumer-5, groupId=connect-redshift-sink] Error while fetching metadata with correlation id 2 : { postgres_courses=INVALID_TOPIC_EXCEPTION,  postgres_content_groups=INVALID_TOPIC_EXCEPTION} (org.apache.kafka.clients.NetworkClient:882)
[2020-04-28 20:02:34,628] INFO Cluster ID: I3Q7IfA1RP63TiilTTh2aQ (org.apache.kafka.clients.Metadata:265)
[2020-04-28 20:02:34,631] INFO [Consumer clientId=consumer-5, groupId=connect-redshift-sink] Discovered group coordinator ip-10-0-0-247:9092 (id: 2147483644 rack: null) (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:605)
[2020-04-28 20:02:34,639] INFO [Consumer clientId=consumer-5, groupId=connect-redshift-sink] Revoking previously assigned partitions [] (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:411)

> I have also try running the same config with postgresql connector over Redshift, it failed at

**Comment by gwasky** [comment]
@sunnikumar Specify the dialect property dialect.name=PostgreSqlDatabaseDialect
