### ISSUE TITLE
Unable to create tables in oracle while doing bulk load

### ISSUE THREAD

**Issue by manikanthkoora** [confluentinc/kafka-connect-jdbc#544]
Hi,

While  I am trying to load data using bulk mode, tables are not getting created. Its throwing following error. I was using following property.
table.name.format=${topic}

WARN Write of 201 records failed, remainingRetries=3 (io.confluent.connect.jdbc.sink.JdbcSinkTask:77)
java.sql.BatchUpdateException: ORA-00942: table or view does not exist

        at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:10500)
        at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:230)
        at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:138)
        at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:66)
        at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:75)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:495)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

But If i use, table.name.format=prefix_${topic}, then tables are getting created. Could you please help me in this. Thanks.

**Comment by rmoff** [comment]
What version of Kafka Connect are you using? Can you share your complete connector config please?
