### ISSUE TITLE
double quote appearing in the columns after the where clause caused ORA 0094 error

### ISSUE THREAD

**Issue by johnteoKheng** [confluentinc/kafka-connect-jdbc#555]
[2018-12-22 20:16:14,567] INFO TimestampIncrementingTableQuerier{table=null, query='select ............................, CAST(LCHG_TIME AS TIMESTAMP) LCHG_UTC_TIME FROM TBAADM.GAM WHERE "LCHG_UTC_TIME" < ? AND (("LCHG_UTC_TIME" = ? AND "ACID_NUM" > ?) OR "LCHG_UTC_TIME" > ?) ORDER BY "LCHG_UTC_TIME","ACID_NUM" ASC

The column name should not have a double quotes as this is causing ORA 0094 error.

**Comment by johnteoKheng** [comment]
java.sql.SQLSyntaxErrorException: ORA-00904: "LCHG_UTC_TIME": invalid identifier

        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
        at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:208)
        at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:886)
        at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1175)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1296)
        at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3613)
        at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3657)
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1495)
        at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.executeQuery(TimestampIncrementingTableQuerier.java:168)
        at io.confluent.connect.jdbc.source.TableQuerier.maybeStartQuery(TableQuerier.java:88)
        at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.maybeStartQuery(TimestampIncrementingTableQuerier.java:60)
        at io.confluent.connect.jdbc.source.JdbcSourceTask.poll(JdbcSourceTask.java:306)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:244)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:220)

**Comment by rhauch** [comment]
It is possible to bypass these quotes with #572, which was recently made and has not yet been released. In the meantime, you can build the connector locally and try the new feature to disable quoting.

I'll mark this as closed, but feel free to reopen if you try the feature and it does not work for you.
