### ISSUE TITLE
Upsert Sink to PostgreSQL 9.4 does not work

### ISSUE THREAD

**Issue by tolgamalachi** [confluentinc/kafka-connect-jdbc#578]
Hello guys,

I see there are some problems regarding _insert.mode=upsert_ but i did not find this specific error and I hope that it can help you make this project better. And btw: thanks for such a great project!

I am using the latest Kafka Docker Image from the Debezium project and their Kafka-Connect Image that means I am using Kafka in version 2.1.0.

I get the following error message:

```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:546)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:302)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:205)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:173)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.ConnectException: java.sql.SQLException: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "kolli" ("kollinr","typ","beschreibung","zeitpunkt") VALUES ('1',1,'ein stuhl',1548274216469672) ON CONFLICT ("kollinr") DO UPDATE SET "typ"=EXCLUDED."typ","beschreibung"=EXCLUDED."beschreibung","zeitpunkt"=EXCLUDED."zeitpunkt" was aborted: ERROR: syntax error at or near "ON"
  Position: 87  Call getNextException to see other errors in the batch.
org.postgresql.util.PSQLException: ERROR: syntax error at or near "ON"
  Position: 87
org.postgresql.util.PSQLException: ERROR: syntax error at or near "ON"
  Position: 87

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:86)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:524)
	... 10 more
Caused by: java.sql.SQLException: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "kolli" ("kollinr","typ","beschreibung","zeitpunkt") VALUES ('1',1,'ein stuhl',1548274216469672) ON CONFLICT ("kollinr") DO UPDATE SET "typ"=EXCLUDED."typ","beschreibung"=EXCLUDED."beschreibung","zeitpunkt"=EXCLUDED."zeitpunkt" was aborted: ERROR: syntax error at or near "ON"
  Position: 87  Call getNextException to see other errors in the batch.
org.postgresql.util.PSQLException: ERROR: syntax error at or near "ON"
  Position: 87
org.postgresql.util.PSQLException: ERROR: syntax error at or near "ON"
  Position: 87
```

sink-config:

```
{
  "name": "postgres-kolli-sink",
  "config": {
    "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
    "tasks.max": "1",
    "topics": "kolli",
    "connection.url": "jdbc:postgresql://zeb:5432/daten?currentSchema=b1&user=test&password=testing",
    "transforms": "unwrap",
    "transforms.unwrap.type": "io.debezium.transforms.UnwrapFromEnvelope",
    "batch.size": "3000",
    "auto.create": "false",
    "auto.evolve": "false",
    "insert.mode": "upsert",
    "pk.mode": "record_key",
    "pk.fields": "kollinr"
  }
}
```

It is a quite simple setup and the insert-mode works fine. The source-postgresql is from the debezium project with postgresql version 9.6. The target-postgresql is from the base postgresql docker image in version 9.4

If you need more Information I can provide them for you.

**Comment by tolgamalachi** [comment]
I made a completely new Container with the latest kafka-connect-image and installed the latest debezium myself. I cannot reproduce the error. So i think this is rather a configuration error from the debezium project or their images are not the latest.

**Comment by riteshpanjwani** [comment]
Hi @tolgamalachi, you got the syntax error because Postgres 9.4 does not support UPSERT.
