### ISSUE TITLE
Another mysql JDBC issue

### ISSUE THREAD

**Issue by the3rdguy** [confluentinc/kafka-connect-jdbc#606]
I've read https://www.confluent.io/blog/kafka-connect-deep-dive-jdbc-source-connector but I'm still stuck. I'm trying to connect to a mysql server 5.7 instance with the latest recommended driver with no luck. Debug output indicates my driver is being registered. Nmap indicates the port is open, and I'm able to connect with the standalone mysql client. Are here any other troubleshooting steps I can take?    

    [2019-02-28 15:19:57,915] INFO Loading plugin from: /opt/confluent-5.0.0/share/java/kafka-connect-jdbc/mysql-connector-java-8.0.15.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:218)
    [2019-02-28 15:19:57,915] DEBUG Loading plugin urls: [file:/opt/confluent-5.0.0/share/java/kafka-connect-jdbc/mysql-connector-java-8.0.15.jar] (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:225)
    [2019-02-28 15:19:58,071] INFO Registered loader: PluginClassLoader{pluginLocation=file:/opt/confluent-5.0.0/share/java/kafka-connect-jdbc/mysql-connector-java-8.0.15.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:241)
    [2019-02-28 15:19:58,087] DEBUG Registered java.sql.Driver: com.mysql.cj.jdbc.Driver@64d7f7e0 to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:279)    
    
    [2019-02-28 15:20:04,974] DEBUG Attempting to connect to MySql (io.confluent.connect.jdbc.util.CachedConnectionProvider:86)
    [2019-02-28 15:20:04,985] INFO Unable to connect to database on attempt 1/3. Will retry in 10000 ms. (io.confluent.connect.jdbc.util.CachedConnectionProvider:93)
    java.sql.SQLException: No suitable driver found for jdbc:mysql://192.168.1.22:3306/clitest
            at java.sql.DriverManager.getConnection(DriverManager.java:689)
            at java.sql.DriverManager.getConnection(DriverManager.java:208)
            at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.getConnection(GenericDatabaseDialect.java:193)
            at io.confluent.connect.jdbc.util.CachedConnectionProvider.newConnection(CachedConnectionProvider.java:87)
            at io.confluent.connect.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:62)
            at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:53)
            at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:75)
            at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
            at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
            at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
            at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
            at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
            at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at java.lang.Thread.run(Thread.java:748)

**Comment by rmoff** [comment]
@the3rdguy random shot: can you try it with the previous JAR version (5.1.47) instead? No reason 8 shouldn't work, but I've only ever used 5.

**Comment by rmoff** [comment]
@the3rdguy can you share: 

* Kafka Connect worker config (specifically, but not only, `plugin.path` value)
* Listing of the Kafka Connect JDBC folder and its full path

This is what I see when Kafka Connect loads, note the long list of JARs including the MySQL one but others also: 

```
[2019-03-04 11:01:44,022] INFO Loading plugin from: /usr/share/java/kafka-connect-jdbc (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
[2019-03-04 11:01:44,161] DEBUG Loading plugin urls: [file:/usr/share/java/kafka-connect-jdbc/audience-annotations-0.5.0.jar, file:/usr/share/java/kafka-connect-jdbc/common-utils-5.1.0.jar, file:/usr/share/java/kafka-connect-jdbc/jline-0.9.94.jar, file:/usr/share/java/kafka-connect-jdbc/jtds-1.3.1.jar, file:/usr/share/java/kafka-connect-jdbc/kafka-connect-jdbc-5.1.0.jar, file:/usr/share/java/kafka-connect-jdbc/mssql-jdbc-7.0.0.jre8.jar, file:/usr/share/java/kafka-connect-jdbc/mysql-connector-java-8.0.13/lib/c3p0-0.9.1-pre6.jar, file:/usr/share/java/kafka-connect-jdbc/mysql-connector-java-8.0.13/lib/c3p0-0.9.1-pre6.src.zip, file:/usr/share/java/kafka-connect-jdbc/mysql-connector-java-8.0.13/lib/jboss-common-jdbc-wrapper-src.jar, file:/usr/share/java/kafka-connect-jdbc/mysql-connector-java-8.0.13/lib/jboss-common-jdbc-wrapper.jar, file:/usr/share/java/kafka-connect-jdbc/mysql-connector-java-8.0.13/lib/protobuf-java-3.6.1.jar, file:/usr/share/java/kafka-connect-jdbc/mysql-connector-java-8.0.13/lib/slf4j-api-1.6.1.jar, file:/usr/share/java/kafka-connect-jdbc/mysql-connector-java-8.0.13/mysql-connector-java-8.0.13.jar, file:/usr/share/java/kafka-connect-jdbc/netty-3.10.6.Final.jar, file:/usr/share/java/kafka-connect-jdbc/ojdbc8.jar, file:/usr/share/java/kafka-connect-jdbc/postgresql-9.4-1206-jdbc41.jar, file:/usr/share/java/kafka-connect-jdbc/slf4j-api-1.7.25.jar, file:/usr/share/java/kafka-connect-jdbc/sqlite-jdbc-3.25.2.jar, file:/usr/share/java/kafka-connect-jdbc/zkclient-0.10.jar, file:/usr/share/java/kafka-connect-jdbc/zookeeper-3.4.13.jar] (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
[2019-03-04 11:01:48,039] DEBUG Skipping class org.apache.kafka.connect.source.SourceConnector as it is not concrete implementation (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
[2019-03-04 11:01:48,051] DEBUG Skipping class org.apache.kafka.connect.sink.SinkConnector as it is not concrete implementation (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
[2019-03-04 11:01:48,083] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/java/kafka-connect-jdbc/} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
[2019-03-04 11:01:48,083] INFO Added plugin 'io.confluent.connect.jdbc.JdbcSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
[2019-03-04 11:01:48,084] INFO Added plugin 'io.confluent.connect.jdbc.JdbcSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
[2019-03-04 11:01:48,144] DEBUG Registered java.sql.Driver: jTDS 1.3.1 to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
[2019-03-04 11:01:48,347] DEBUG Registered java.sql.Driver: SQLServerDriver:2 to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
[2019-03-04 11:01:48,407] DEBUG Registered java.sql.Driver: com.mysql.cj.jdbc.Driver@365c30cc to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
[2019-03-04 11:01:48,708] DEBUG Registered java.sql.Driver: oracle.jdbc.OracleDriver@c540f5a to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
[2019-03-04 11:01:48,779] DEBUG Registered java.sql.Driver: org.postgresql.Driver@1e67a849 to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
[2019-03-04 11:01:48,790] DEBUG Registered java.sql.Driver: org.sqlite.JDBC@4ae3c1cd to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
```

**Comment by the3rdguy** [comment]
regarding trying the version 5 driver of mysql: I tried postgresql as well.  vresion 9.2 on rhel 6, and version 10.5 on rhel 7. Both timeI tried with the stock confluent driver, with the same error.    
    
config values:
I've played with plugin path a lot, currently it reads
    plugin.path=/opt/confluent-5.0.0/share/java/kafka-connect-jdbc
I also have a line currently commented out that reads:
    plugin.path=/usr/local/share/java,/opt/confluent-5.0.0/share/java/kafka-connect-jdbc,/opt/connectors,/usr/bin/java,/opt/kafka/share/java,/opt/kafka/share/plugins,/opt/confluent-5.0.0/share/java/kafka-connect-jdbc

other current configs:
    bootstrap.servers=192.168.1.20:9092
    key.converter=org.apache.kafka.connect.json.JsonConverter
    value.converter=org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable=false
    value.converter.schemas.enable=false
    offset.flush.interval.ms=10000
    offset.storage.file.filename=/tmp/connect.offsets

I've also tried the '...storage.StringConverter' and every combination of enabling and disabling the key and value keys.    
    
folder contents:
    ls /opt/confluent-5.0.0/share/java/kafka-connect-jdbc
    audience-annotations-0.5.0.jar jtds-1.3.1.jar
    mysql-connector-java-8.0.15.jar 
    slf4j-api-1.7.25.jar zookeeper-3.4.13.jar 
    common-utils-5.0.0.jar 
    kafka-connect-jdbc-5.0.0.jar 
    netty-3.10.6.Final.jar sqlite-jdbc-3.8.11.2.jar 
    jline-0.9.94.jar log4j-1.2.17.jar 
    postgresql-9.4-1206-jdbc41.jar zkclient-0.10.jar

I figured leaving the mysql jar in the default locatio was an issue, so I moved it in here.    

Since it fails with the same error on 2 postgres servers and a mysql server, is it possible I got messed up env variables, or even java versions? I
