### ISSUE TITLE
JDBC sink fails to Postgres database

### ISSUE THREAD

**Issue by kccheung** [confluentinc/kafka-connect-jdbc#609]
I encounter the following error when I sink a topic to my postgres database:

```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:546)
at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:302)
at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:205)
at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:173)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
used by: java.lang.ClassCastException: java.util.HashMap cannot be cast to org.apache.kafka.connect.data.Struct
at io.confluent.connect.jdbc.sink.PreparedStatementBinder.bindRecord(PreparedStatementBinder.java:61)
at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:116)
at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:69)
at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:69)
at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:524)
... 10 more
```

My sink connector config:

```
{
    "name": "pg_sink_S_COUNTS_VA_INTERMEDIATE",
    "config": {
        "topics": "S_COUNTS_VA_INTERMEDIATE",
        "tasks.max": 1,
        "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
        "key.converter": "org.apache.kafka.connect.storage.StringConverter",
        "key.ignore": "true",
        "schema.ignore": "true",
        "schemas.enable": "false",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter.schemas.enable": "false",
        "type.name": "kafka-connect",
        "connection.url": "jdbc:postgresql://*****.com:5433/kafka-sink",
        "connection.user": "****",
        "connection.password": "*****",
        "insert.mode": "upsert",
        "auto.create": true,
        "auto.evolve": true,
        "pk.mode": "kafka",
        "pk.fields": "__connect_topic,__connect_partition,__connect_offset",
        "batch.size": 30
    }
}
```

The producer can produce JSON data to Kafka without schema defined.

**Comment by rmoff** [comment]
```
"value.converter": "org.apache.kafka.connect.json.JsonConverter",
"value.converter.schemas.enable": "false",
```

The JDBC Sink requires a schema to your data. I'm not sure why this is triggering the error you're seeing, but you definitely to include a schema, either as part of your JSON or using Avro. See https://www.confluent.io/blog/kafka-connect-deep-dive-converters-serialization-explained

**Comment by krishkir** [comment]
Facing the same issue with mongo as source and mysql as sink.Request your help..
"value.converter": "org.apache.kafka.connect.json.JsonConverter",
"value.converter.schemas.enable": "false"

**Comment by cricket007** [comment]
@krishkir As explained, JDBC sink connector requires schemas to be *enabled*

@fabiotc You'd have to write a custom Connect SMT or other processor that could parse your topic and return a new record with a schema applied

**Comment by fabiotc** [comment]
Thanks @cricket007

**Comment by rmoff** [comment]
Some notes on this: https://rmoff.net/2020/01/22/kafka-connect-classcastexception/

**Comment by yousufdev** [comment]
@cricket007 Thanks for the suggestion on writing a custom SMT @fabiotc here is a SMT I wrote for appending schema to a record [https://github.com/yousufdev/kafka-connect-append-schema](url). Hope it helps.

**Comment by fabiotc** [comment]
thanks @rmoff
@yousufdev thanks for this! And using your example, Is it possible to append a schema into a complex and nested JSON structure?

**Comment by yousufdev** [comment]
@fabiotc yes you can append schema into a complex structure, just it in the schema property of the SMT.

**Comment by OneCricketeer** [comment]
> java.lang.String cannot be cast to org.apache.kafka.connect.data.Struct

JDBC sink requires Structured data, not strings.

FileStream source only writes strings unless you use a HoistField transform, for example

**Comment by OneCricketeer** [comment]
How about using the JDBC source connector (or Debezium) from one database to another? The problem isn't the connector itself, it's the data you're sending through Connect, and the FileStream source just isn't a good example one to use

**Comment by ggabmc** [comment]
> That error has already been answered in this thread
> 
> [#609 (comment)](https://github.com/confluentinc/kafka-connect-jdbc/issues/609#issuecomment-577300246)
> 
> How about using the JDBC source connector (or Debezium) from one database to another? The problem isn't the connector itself, it's the data you're sending through Connect, and the FileStream source just isn't a good example one to use



Thank you so much , I changed the way  I was doing it... I'm directly sending the message to the topic with the kafka-console-producer including the schema and payload  and the sink is able to write those fields in the DB, thank you for your help I'm building a prove of concept to present it at work, thanks.

      kafka-console-producer.bat --bootstrap-server 127.0.0.1:9092  --topic demo-2-distributed
      {
      "schema": {
      "type": "struct", "optional": false, "version": 1, "fields": [
      { "field": "id", "type": "string", "optional": true },
      { "field": "artist", "type": "string", "optional": true },
      { "field": "song", "type": "string", "optional": true }
      ] },
      "payload": {
      "id": 1,
      "artist": "Rick Astley",
      "song": "Never Gonna Give You Up"
      }
      }


Kafka JDBC connector configuration

{
  "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
  "connection.password": "postgres",
  "topics": "demo-2-distributed",
  "tasks.max": "1",
  "key.converter.schemas.enable": "false",
  "fields.whitelist": "Id,artist,song",
  "auto.evolve": "true",
  "connection.user": "postgres",
  "value.converter.schemas.enable": "true",
  "auto.create": "true",
  "connection.url": "jdbc:postgresql://postgres:5432/postgres",
  "value.converter": "org.apache.kafka.connect.json.JsonConverter",
  "insert.mode": "upsert",
  "key.converter": "org.apache.kafka.connect.storage.StringConverter",
  "pk.mode": "kafka",
  "pk.fields": "__connect_topic,__connect_partition,__connect_offset"
}

**Comment by yousufdev** [comment]
> @cricket007 Thanks for the suggestion on writing a custom SMT. @fabiotc here is a SMT I wrote for appending schema to a record https://github.com/yousufdev/kafka-connect-append-schema, hope it helps.

@OneCricketeer can you please start my SMT repo again ? My account got compromised and deleted.Thanks
