### ISSUE TITLE
JDBC type -155 (datetimeoffset) not currently supported (io.confluent.connect.jdbc.dialect.SqlServerDatabaseDialect)

### ISSUE THREAD

**Issue by lmathukumalli** [confluentinc/kafka-connect-jdbc#614]
I am using kafka-connect-jdbc v 5.2.x. 

Ran into the following error when trying to test using timestamp columns that are of type datetimeoffset (JDBC Source connectors polling from SQL Server database mssql-jdbc-7.0.0.jre8.jar)

[2019-03-15 09:36:49,193] INFO WorkerSourceTask{id=datetimeoffset.ts.connector.test-0} Source task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSourceTask)
[2019-03-15 09:36:49,193] INFO Attempting to open connection #1 to SqlServer (io.confluent.connect.jdbc.util.CachedConnectionProvider)
[2019-03-15 09:36:49,228] INFO Begin using SQL query: SELECT ID, Name, DateUpdated FROM test WHERE "DateUpdated" < ? AND (("DateUpdated" = ? AND "ID" > ?) OR "DateUpdated" > ?) ORDER BY "DateUpdated","ID" ASC (io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier)
[2019-03-15 09:36:49,267] **WARN JDBC type -155 (datetimeoffset) not currently supported (io.confluent.connect.jdbc.dialect.SqlServerDatabaseDialect)**
[2019-03-15 09:36:49,297] INFO Closing resources for JDBC source task (io.confluent.connect.jdbc.source.JdbcSourceTask)
[2019-03-15 09:36:49,298] INFO Closing connection #1 to SqlServer (io.confluent.connect.jdbc.util.CachedConnectionProvider)
[2019-03-15 09:36:49,298] INFO WorkerSourceTask{id=datetimeoffset.ts.connector.test-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask)
[2019-03-15 09:36:49,299] INFO WorkerSourceTask{id=datetimeoffset.ts.connector.test-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask)
[2019-03-15 09:36:49,299] ERROR WorkerSourceTask{id=datetimeoffset.ts.connector.test-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
**org.apache.kafka.connect.errors.DataException: DateUpdated is not a valid field name**
	at org.apache.kafka.connect.data.Struct.lookupField(Struct.java:254)
	at org.apache.kafka.connect.data.Struct.get(Struct.java:74)
	at io.confluent.connect.jdbc.source.TimestampIncrementingCriteria.extractOffsetTimestamp(TimestampIncrementingCriteria.java:239)
	at io.confluent.connect.jdbc.source.TimestampIncrementingCriteria.extractValues(TimestampIncrementingCriteria.java:209)
	at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.extractRecord(TimestampIncrementingTableQuerier.java:196)
	at io.confluent.connect.jdbc.source.JdbcSourceTask.poll(JdbcSourceTask.java:318)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:245)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:221)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2019-03-15 09:36:49,300] ERROR WorkerSourceTask{id=datetimeoffset.ts.connector.test-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
[2019-03-15 09:36:49,301] INFO Stopping JDBC source task (io.confluent.connect.jdbc.source.JdbcSourceTask)

Can you please help?

Thanks.

**Comment by lmathukumalli** [comment]
Resolved the issue by overriding addFieldToSchema and createColumnConverter methods in io.confluent.connect.jdbc.dialect.SqlServerDatabaseDialect.

**Comment by cconstantinxpo** [comment]
@lmathukumalli would you be able to share the code?

**Comment by cconstantin** [comment]
@lmathukumalli would you be able to share the code?

**Comment by lmathukumalli** [comment]
<  @Override
  public String addFieldToSchema(
      ColumnDefinition columnDefn,
      SchemaBuilder builder
  ) {
    // Handle any SQL Server specific data types first, before adding the generic data types
    final String fieldName = fieldNameFor(columnDefn);
    switch (columnDefn.type()) {
      // Timestamp is a date + time
      case microsoft.sql.Types.DATETIMEOFFSET: {
          boolean optional = columnDefn.isOptional();
          SchemaBuilder tsSchemaBuilder = org.apache.kafka.connect.data.Timestamp.builder();
          if (optional) {
            tsSchemaBuilder.optional();
          }
          builder.field(fieldName, tsSchemaBuilder.build());
          return fieldName;
        }
      default:
    	  // Delegate for the remaining logic
    	  return super.addFieldToSchema(columnDefn, builder);
    }


  }>

<
  @Override
  public ColumnConverter createColumnConverter(
      ColumnMapping mapping
  ) {
	// Handle any SQL Server specific data types first, before mapping the generic data types
    ColumnDefinition columnDefn = mapping.columnDefn();
    int col = mapping.columnNumber();
    TimeZone timeZone;
    if (config instanceof JdbcSourceConnectorConfig) {
        timeZone = ((JdbcSourceConnectorConfig) config).timeZone();
      } else if (config instanceof JdbcSinkConfig) {
        timeZone = ((JdbcSinkConfig) config).timeZone;
      } else {
        timeZone = TimeZone.getTimeZone(ZoneOffset.UTC);
      }
    switch (columnDefn.type()) {
      // Timestamp is a date + time
      case microsoft.sql.Types.DATETIMEOFFSET: {
        return rs -> rs.getTimestamp(col, DateTimeUtils.getTimeZoneCalendar(timeZone));
      }

      default:
    	// Delegate for the remaining logic
    	return super.createColumnConverter(mapping);
    }


  }
>

**Comment by cconstantin** [comment]
Awesome, thanks @lmathukumalli
