### ISSUE TITLE
Sink connect fails with NPE (mysql-5.5)

### ISSUE THREAD

**Issue by rochapaulo** [confluentinc/kafka-connect-jdbc#624]
Scenario:

- MySQL: 5.5
- JDBC Driver: mysql-connector-java-5.1.17
- Connector Version: 5.1.2

**connector-configuration**
```
name=test-0005
topics=kafkatest.testcdc5.sourcedb.my_topic_name
connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
connection.password=kafka
connection.url=jdbc:mysql://MY_HOST_NAME:3306
connection.user=kafka
auto.create=true
auto.evolve=true
```

**connect-configuration**
```
config.storage.replication.factor=1
status.storage.replication.factor=1
key.converter.schema.registry.url=http://MY_HOST_NAME:8081
key.converter=io.confluent.connect.avro.AvroConverter
value.converter.schemas.enable=true
rest.port=8083
key.converter.schemas.enable=true
plugin.path=/etc/plugins/jars
offset.storage.replication.factor=1
status.storage.topic=connect-avro-status
rest.advertised.host.name=MY_HOST_NAME
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
config.storage.topic=connect-avro-config
group.id=connect-avro
internal.key.converter.schemas.enable=false
bootstrap.servers=MY_HOST_NAME:9092
internal.value.converter.schemas.enable=false
log4j.root.loglevel=INFO
offset.storage.topic=connect-avro-offsets
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=http://MY_HOST_NAME:8081
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
```

Exception:
```
[2019-03-21 18:32:48,726] INFO Creating table with sql: CREATE TABLE `kafkatest`.`testcdc5` (<SCHEMA_REMOVED>) (io.confluent.connect.jdbc.sink.DbStructure)
[2019-03-21 18:32:48,740] INFO Checking MySql dialect for existence of table "kafkatest"."testcdc5" (io.confluent.connect.jdbc.dialect.MySqlDatabaseDialect)
[2019-03-21 18:32:48,743] INFO Using MySql dialect table "kafkatest"."testcdc5" absent (io.confluent.connect.jdbc.dialect.MySqlDatabaseDialect)
[2019-03-21 18:32:48,744] ERROR WorkerSinkTask{id=test-0005-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask)
java.lang.NullPointerException
	at io.confluent.connect.jdbc.sink.DbStructure.amendIfNecessary(DbStructure.java:123)
	at io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:73)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:84)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:65)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:73)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2019-03-21 18:32:48,751] ERROR WorkerSinkTask{id=test-0005-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:586)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at io.confluent.connect.jdbc.sink.DbStructure.amendIfNecessary(DbStructure.java:123)
	at io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:73)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:84)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:65)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:73)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
	... 10 more
```

Response from Rest endpoint:
```json
{
	"name": "test-0005",
	"connector": {
		"state": "RUNNING",
		"worker_id": "MY_HOST_NAME:8083"
	},
	"tasks": [{
		"state": "FAILED",
		"trace": "org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:586)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.lang.NullPointerException\n\tat io.confluent.connect.jdbc.sink.DbStructure.amendIfNecessary(DbStructure.java:123)\n\tat io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:73)\n\tat io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:84)\n\tat io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:65)\n\tat io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:73)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)\n\t... 10 more\n",
		"id": 0,
		"worker_id": "MY_HOST_NAME:8083"
	}],
	"type": "sink"
}
```

**Comment by rochapaulo** [comment]
Problem fixed, I was missing **table.name.format** , my config now looks like:
```
{
    "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
    "table.name.format": "${topic}",
    "connection.password": "kafka",
    "transforms": "t1",
    "topics.regex": "kafkatest.testcdc5.(.*)",
    "transforms.t1.type": "org.apache.kafka.connect.transforms.RegexRouter",
    "auto.evolve": "true",
    "transforms.t1.regex": "([^.]+)\\.([^.]+)\\.([^.]+)\\.([^.]+)\\.([^.]+)",
    "connection.user": "kafka",
    "name": "test-0005",
    "auto.create": "true",
    "connection.url": "jdbc:mysql://MY_HOST_NAME:3306/kafkatest",
    "transforms.t1.replacement": "$5"
}
```
