### ISSUE TITLE
Exiting WorkerSinkTask due to unrecoverable exception: NullPointerException (Postgres)

### ISSUE THREAD

**Issue by wowo** [confluentinc/kafka-connect-jdbc#631]
Hi,

I'm using JdbcSinkConnector with postgres.

Config:

```
{
   "name":"jdbc",
   "config":{
      "topics":"some_topic",
      "connector.class":"io.confluent.connect.jdbc.JdbcSinkConnector",
      "connection.url": "jdbc:postgresql://ip/sometable?user=postgresadmin&password=pass",
      "auto.create": true,
      "table.name.format": "sometable",
      "pk.mode": "none",
      "insert.mode": "insert",
      "tasks.max":"1",
      "transforms": "ReplaceValueWithAfter",
      "transforms.ReplaceValueWithAfter.type":"org.apache.kafka.connect.transforms.ExtractField$Value",
      "transforms.ReplaceValueWithAfter.field":"after"
   }  
}  
```
The data is in avro format. When I start worker, it processes around 370k records and fails on the one particular message, which looks totally fine. It's not corrupted or so. The only thing is that it has one micro timestamp field = null (column is nullable both in avro schema and in database, which this connector creates). I've tried all possible combination (with key mode kafka, insert modes, whitelisting fields to limit them to minimum, and so on). Nothing works :( 

Always getting

 ```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:194)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException 
```

However, once got something more verbose (I think there was `pk.mode` set to `kafka`):
```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:194)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at io.confluent.connect.jdbc.sink.PreparedStatementBinder.bindNonKeyFields(PreparedStatementBinder.java:134)
	at io.confluent.connect.jdbc.sink.PreparedStatementBinder.bindRecord(PreparedStatementBinder.java:70)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:138)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:124)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:65)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:73)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:565)
	... 10 more
```

```
version: "2.1.0-cp1",
commit: "bda8715f42a1a3db",
```

I give up after 6 hours of debugging... Please help!

**Comment by wowo** [comment]
Guys, anyone stumbled upon similar error before?

**Comment by wowo** [comment]
Kind reminder. Any hints what to do?

**Comment by wowo** [comment]
It appears to be a thing sometimes still :)

**Comment by venky2100b** [comment]
Hello Guys,
While sending data from Kafka to Cassandra I am getting below error  any one have an idea why this is happening it would be great help.
Oracle to Kafka - cassandra ;: 
1.oracle field is  gr_process_time type: **Number**(3,0)
2.kafka field is a string( mapping source connector like **tochar**(gr_process_time)
3.cassandra field gr_process type is **text**

ERROR WorkerSinkTask{id=dse-gcp-connector-mm-2} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:561)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.CompletionException: java.lang.ClassCastException: java.math.BigDecimal cannot be cast to java.lang.String
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1629)
        ... 3 more
Caused by: java.lang.ClassCastException: java.math.BigDecimal cannot be cast to java.lang.String
        at com.datastax.dsbulk.commons.codecs.string.StringToStringCodec.externalToInternal(StringToStringCodec.java:14)
        at com.datastax.dsbulk.commons.codecs.ConvertingCodec.encode(ConvertingCodec.java:63)
        at com.datastax.kafkaconnector.RecordMapper.bindColumn(RecordMapper.java:239)
        at com.datastax.kafkaconnector.RecordMapper.map(RecordMapper.java:140)
        at com.datastax.kafkaconnector.DseSinkTask.mapAndQueueRecord(DseSinkTask.java:226)
        at com.datastax.kafkaconnector.DseSinkTask.lambda$put$1(DseSinkTask.java:132)

**Comment by SherryShi11010** [comment]
> Guys, anyone stumbled upon similar error before?

Hi wowo, I encountered with similar issue like yours. May I know if you've figured this out yet?
