### ISSUE TITLE
Support for JSON and JSONB in Postgres Sink

### ISSUE THREAD

**Issue by marcospassos** [confluentinc/kafka-connect-jdbc#643]
It looks like that the sink connector does not support either JSON or JSONB fields. 

I'm trying to export a topic, in Avro format, to a Postgres database. The topic records contain a map of strings, which I'd like to store in a JSONB field:

```json
{
  "type": "record",
  "name": "Example",
  "fields": [
    {
      "name": "foo",
      "type": "string"
    },
    {
      "name": "bar",
      "type": {
        "type": "map",
        "values": "string"
      }
    }
  ]
}
```

```
name=example-sink
connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
tasks.max=1
topics=test-topic
key.converter=org.apache.kafka.connect.storage.StringConverter
key.converter.schemas.enable=true
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schemas.enable=true
value.converter.schema.registry.url=http://localhost:8081
connection.url=jdbc:postgresql://postgres:5432/postgres
connection.user=postgres
connection.password=postgres
insert.mode=upsert
pk.mode=kafka
pk.fields=__connect_topic,__connect_partition,__connect_offset
fields.whitelist=data
auto.create=false
auto.evolve=true
```
With the above schema the connector fails:
```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
    at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:484)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:265)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:182)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:150)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```
I tried then a schema containing a text field already serialized in JSON:
```json
{
  "type": "record",
  "name": "Example",
  "fields": [
    {
      "name": "foo",
      "type": "string"
    },
    {
      "name": "bar",
      "type": "string"
    }
  ]
}
```
But it also does not work. 

Is there any way to convert that field to string and instruct the connector to export it as JSON?

**Comment by rmoff** [comment]
I don't have an answer to this specific issue, but just want to point out here for others coming across this issue that `org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.` is just an indicator that a Kafka Connect task has died; it is itself not the root cause. You need to scroll up the Connect worker log to see the actual cause of the task's failure.

**Comment by Dishwasha** [comment]
This works instead:
```
CREATE OR REPLACE FUNCTION varchar_to_jsonb (varchar) RETURNS jsonb AS $$ SELECT to_jsonb($1) $$ LANGUAGE SQL;
CREATE CAST (varchar as jsonb) WITH FUNCTION varchar_to_jsonb(varchar) AS IMPLICIT;
```

**Comment by NathanNam** [comment]
https://github.com/confluentinc/kafka-connect-jdbc/issues/46#issuecomment-1135209669
