### ISSUE TITLE
long table names cause NPE

### ISSUE THREAD

**Issue by markteehan** [confluentinc/kafka-connect-jdbc#675]
I am JDBC Sinking all topics into Postgres. Long table names such as 
k__confluent-controlcenter-5-3-0-1-metrics-trigger-measurement-rekey
fail with NPE and short topic names (such as connect-offsets-1359-A) succeed.

If i create this table manually, it succeeds.
CREATE TABLE "k__confluent-controlcenter-5-3-0-1-metrics-trigger-measurement-rekey" ("line" BYTEA NULL)

The connector appears to fail when the topic name exceeds a certain length.

     {
            "name": "jdbc_sink_NONE",
             "config": {
                               "connector.class":"io.confluent.connect.jdbc.JdbcSinkConnector"
                     ,                    "name":"jdbc_sink_NONE"
                     ,            "topics.regex":"connect(.*)"
                     ,       "table.name.format":"k_${topic}"
                     ,             "insert.mode":"insert"
                     ,          "connection.url":"jdbc:postgresql://localhost/db_gdelt?currentSchema=public"
                     ,          "connection.user":"gdelt"
                     ,      "connection.password":"gdelt_pw"
                     ,        "poll.interval.ms":"3000"
                     ,         "numeric.mapping":"best_fit"
                     ,               "tasks.max":"1"
                     ,             "auto.create":"true"
                     ,             "auto.evolve":"false"
                     ,            "value.schema":"{\"name\":\"schema.struct\" ,\"type\":\"STRUCT\",\"isOptional\":true,\"fieldSchemas\":{\"KEY\":{\"type\":\"STRING\",\"isOptional\":true},\"VALUE\":{\"type\":\"INT64\",\"isOptional\":true}"
                     , "transforms":"HoistField","transforms.HoistField.type":"org.apache.kafka.connect.transforms.HoistField$Value","transforms.HoistField.field":"line"
                     }
      }

```[2019-07-05 15:24:28,994] DEBUG starting (io.confluent.monitoring.clients.interceptor.MonitoringInterceptor:176)
[2019-07-05 15:24:29,030] DEBUG Received 500 records. First record kafka coordinates:(_confluent-controlcenter-5-3-0-1-metrics-trigger-measurement-rekey-0-123800). Writing them to the database... (io.confluent.connect.jdbc.sink.JdbcSinkTask:68)
[2019-07-05 15:24:29,030] INFO Attempting to open connection #1 to PostgreSql (io.confluent.connect.jdbc.util.CachedConnectionProvider:87)
[2019-07-05 15:24:29,100] INFO JdbcDbWriter Connected (io.confluent.connect.jdbc.sink.JdbcDbWriter:49)
[2019-07-05 15:24:29,109] DEBUG Records is empty (io.confluent.connect.jdbc.sink.BufferedRecords:166)
[2019-07-05 15:24:29,112] INFO Checking PostgreSql dialect for existence of table "k__confluent-controlcenter-5-3-0-1-metrics-trigger-measurement-rekey" (io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialect:511)
[2019-07-05 15:24:29,129] INFO Using PostgreSql dialect table "k__confluent-controlcenter-5-3-0-1-metrics-trigger-measurement-rekey" absent (io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialect:519)
[2019-07-05 15:24:29,131] INFO Creating table with sql: CREATE TABLE "k__confluent-controlcenter-5-3-0-1-metrics-trigger-measurement-rekey" (
"line" BYTEA NULL) (io.confluent.connect.jdbc.sink.DbStructure:92)
[2019-07-05 15:24:29,146] INFO Checking PostgreSql dialect for existence of table "k__confluent-controlcenter-5-3-0-1-metrics-trigger-measurement-rekey" (io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialect:511)
[2019-07-05 15:24:29,148] INFO Using PostgreSql dialect table "k__confluent-controlcenter-5-3-0-1-metrics-trigger-measurement-rekey" absent (io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialect:519)
[2019-07-05 15:24:29,149] ERROR WorkerSinkTask{id=jdbc_sink_NONE-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:558)
java.lang.NullPointerException
        at io.confluent.connect.jdbc.sink.DbStructure.amendIfNecessary(DbStructure.java:124)
        at io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:74)
        at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:121)
        at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:66)
        at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2019-07-05 15:24:29,150] DEBUG WorkerSinkTask{id=jdbc_sink_NONE-0} Skipping offset commit, no change since last commit (org.apache.kafka.connect.runtime.WorkerSinkTask:426)
[2019-07-05 15:24:29,150] DEBUG WorkerSinkTask{id=jdbc_sink_NONE-0} Finished offset commit successfully in 1 ms for sequence number 1: null (org.apache.kafka.connect.runtime.WorkerSinkTask:264)
[2019-07-05 15:24:29,151] ERROR WorkerSinkTask{id=jdbc_sink_NONE-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
```

A successful excerpt is more like this:
```
[2019-07-05 17:32:58,870] INFO Using PostgreSql dialect table "k_connect-status-A-1729" absent (io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialect:519)
[2019-07-05 17:32:58,870] INFO Creating table with sql: CREATE TABLE "k_connect-status-A-1729" (
"line" BYTEA NULL) (io.confluent.connect.jdbc.sink.DbStructure:92)
[2019-07-05 17:32:58,874] INFO Checking PostgreSql dialect for existence of table "k_connect-status-A-1729" (io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialect:511)
[2019-07-05 17:32:58,876] INFO Using PostgreSql dialect table "k_connect-status-A-1729" present (io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialect:519)
[2019-07-05 17:32:58,877] DEBUG Querying PostgreSql dialect column metadata for catalog:null schema:null table:k_connect-status-A-1729 (io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialect:545)
[2019-07-05 17:32:58,882] INFO Setting metadata for table "k_connect-status-A-1729" to Table{name='"k_connect-status-A-1729"', columns=[Column{'line', isPrimaryKey=false, allowsNull=true, sqlType=bytea}]} (io.confluent.connect.jdbc.util.TableDefinitions:64)
[2019-07-05 17:32:58,883] DEBUG INSERT sql: INSERT INTO "k_connect-status-A-1729"("line") VALUES(?) deleteSql: null meta: FieldsMetadata{keyFieldNames=[], nonKeyFieldNames=[line], allFields={line=SinkRecordField{schema=Schema{BYTES}, name='line', isPrimaryKey=false}}} (io.confluent.connect.jdbc.sink.BufferedRecords:129)
[2019-07-05 17:32:58,883] INFO Closing BufferedRecords with updatePreparedStatement: null deletePreparedStatement: null (io.confluent.connect.jdbc.sink.BufferedRecords:242)
[2019-07-05 17:32:58,883] DEBUG Records is empty (io.confluent.connect.jdbc.sink.BufferedRecords:166)
[2019-07-05 17:32:58,883] INFO Checking PostgreSql dialect for existence of table "k_connect-configs-A-1729" (io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialect:511)
[2019-07-05 17:32:58,886] INFO Using PostgreSql dialect table "k_connect-configs-A-1729" absent (io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialect:519)
[2019-07-05 17:32:58,886] INFO Creating table with sql: CREATE TABLE "k_connect-configs-A-1729" (
"line" BYTEA NULL) (io.confluent.connect.jdbc.sink.DbStructure:92)
[2019-07-05 17:32:58,888] INFO Checking PostgreSql dialect for existence of table "k_connect-configs-A-1729" (io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialect:511)
[2019-07-05 17:32:58,890] INFO Using PostgreSql dialect table "k_connect-configs-A-1729" present (io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialect:519)
[2019-07-05 17:32:58,890] DEBUG Querying PostgreSql dialect column metadata for catalog:null schema:null table:k_connect-configs-A-1729 (io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialect:545)
```

**Comment by markteehan** [comment]
PG maximum size is 61 bytes. The connector should either exclude topic names from the selection (that exceed 61 bytes) or exhibit the same behaviour as PG by automatically truncating the table name:

sql> CREATE TABLE "k__confluent-controlcenter-5-3-0-1-metrics-trigger-measurement-rekey" (
       "line" BYTEA NULL)
[2019-07-06 11:51:38] [42622] identifier "k__confluent-controlcenter-5-3-0-1-metrics-trigger-measurement-rekey" will be truncated to "k__confluent-controlcenter-5-3-0-1-metrics-trigger-measurement-"
[2019-07-06 11:51:38] completed in 47 ms

**Comment by gharris1727** [comment]
@markteehan While truncating the name in an interactive user environment is a reasonable choice, truncating it automatically in a connector might be risky, non-obvious behavior. Not to mention that it could cause table collisions, if two topics differ by only their truncated suffixes.

I also think the control-flow for ignoring certain topics due to their name length is pretty complicated, and would be hard to implement given the current expectations of database dialects.

In this case, I would suggest applying an SMT to transform these topic names to something shorter, in a way that would satisfy the the 61 character limit, and be sufficiently unique. The [RegexRouter](https://docs.confluent.io/current/connect/transforms/regexrouter.html#regexrouter) might be sufficient for this use-case, so i'd try that before we move on to changes to the JDBC connector.

As an aside, the fact that this error appears as an NPE and not a more descriptive error message has been fixed by https://github.com/confluentinc/kafka-connect-jdbc/pull/706 and should be appearing in a release soon.

If you have more questions, feel free to re-open this issue.
