### ISSUE TITLE
Confluent JDBC Source Connect v5.2.2 gives “org.apache.kafka.connect.errors.DataException”

### ISSUE THREAD

**Issue by arslanakhtar61** [confluentinc/kafka-connect-jdbc#676]
This is a reference to the [question](https://stackoverflow.com/questions/56898018/confluent-jdbc-source-connect-v5-2-2-gives-org-apache-kafka-connect-errors-data) asked on stackoverflow. I am using standalone confluent-jdbc-source connector v5.2.2 using confluent-schema-registry to pull table data from DB2 v10.5.0.10. Everything works fine in v5.0.0 but I am getting the following error with v5.2.2.

`
ERROR WorkerSourceTask{id=source-ibm-db2-jdbc-project-0} Task threw an uncaught and unre
coverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.ja
va:178)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.convertTransformedRecord(WorkerSourceTask.java:269)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:293)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:228)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.kafka.connect.errors.DataException: Kafka Connect Date type should not have any time fields set to non-z
ero values.
        at org.apache.kafka.connect.data.Date.fromLogical(Date.java:64)
        at io.confluent.connect.avro.AvroData$6.convert(AvroData.java:275)
        at io.confluent.connect.avro.AvroData.fromConnectData(AvroData.java:419)
        at io.confluent.connect.avro.AvroData.fromConnectData(AvroData.java:606)
        at io.confluent.connect.avro.AvroData.fromConnectData(AvroData.java:365)
        at io.confluent.connect.avro.AvroConverter.fromConnectData(AvroConverter.java:77)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.lambda$convertTransformedRecord$2(WorkerSourceTask.java:269)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128
)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.ja
va:162)
        ... 11 more
[2019-07-05 12:19:25,217] ERROR WorkerSourceTask{id=source-ibm-db2-jdbc-project-0} Task is being killed and will n
ot recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
`

**confluent-jdbc-source-connector.properties**

`
connection.url=jdbc:db2://*****:50000/dbName
connection.user=*****
connection.password=*****

schema.pattern=schemaName
table.whitelist=TableName
poll.interval.ms=5000
validate.non.null=false

mode=timestamp
timestamp.column.name=CREATE_TIMESTAMP,SYN_TIMESTAMP
db.timezone= Asia/Hong_Kong
numeric.mapping=best_fit

topic.prefix=TopicPrefix.

transforms=ExtractKey, SetSchemaMetadata, SetSchemaMetadataKey
transforms.ExtractKey.type=org.apache.kafka.connect.transforms.ValueToKey
transforms.ExtractKey.fields=ID

transforms.SetSchemaMetadataKey.type=org.apache.kafka.connect.transforms.SetSchemaMetadata$Key
transforms.SetSchemaMetadataKey.schema.name=namespace.ClassNameKey
transforms.SetSchemaMetadataKey.schema.version=1

transforms.SetSchemaMetadata.type= org.apache.kafka.connect.transforms.SetSchemaMetadata$Value
transforms.SetSchemaMetadata.schema.name=namespace.ClassNameValue
transforms.SetSchemaMetadata.schema.version=1
`

**connect-standalone.properties**

`
###JsonConverter###
#key.converter=org.apache.kafka.connect.json.JsonConverter
#value.converter=org.apache.kafka.connect.json.JsonConverter

#key.converter.schemas.enable=false
#value.converter.schemas.enable=false

###AvroConverter###
key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://localhost:8084

value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=http://localhost:8084

offset.flush.interval.ms=10000
plugin.path=/Users/confluent-5.2.2/share/java/confluentinc-kafka-connect-jdbc-5.2.2
`

I have also tried using JsonConverter by commenting out all the AvroConverter related fields from connect-standalone.properties but a similar error still persist.

The IBM DB2 Database table have columns as: CREATE_TIMESTAMP (TYPE_NAME=TIMESTAMP, IS_NULLABLE=NO), SYN_TIMESTAMP (TYPE_NAME=TIMESTAMP, IS_NULLABLE=YES), EVENT_DATE (TYPE_NAME=DATE, IS_NULLABLE=NO), Rest of the columns are CHAR, DECIMALS and VARCHAR defined with IS_NULLABLE=NO

Why does it work for v5.0.0 but not for v5.2.2? The reason I want to use v5.2.2 is that a similar confluent-jdbc-sink connector I defined for IBM DB2 Database doesn't work with v5.0.0 but works with v5.2.2. I would want to use the latest version for both jdbc sink and source.

**Comment by gharris1727** [comment]
@arslanakhtar61

It appears that #505 was merged Oct 30, 2018, after 5.0.0 was released on July 31, 2018. Therefore 5.0.0 wouldn't contain the `db.timezone` feature or any of its associated logic, while 5.2.2 would.

The relevant line in [GenericDatabaseDialect](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java#L1235) that gives the timezone to the database driver should cause the database driver to convert the date. This conversion is somehow causing the final date object to have some time component, likely because your `db.timezone` is not UTC, and the driver is converting a midnight UTC offset into some non-midnight UTC offset.

I would suggest trying the same setup with `db.timezone=UTC` and see if the issue persists, and verify that the dates are converted as you would expect.

**Comment by brandonwittwer** [comment]
It doesn't seem appropriate to adjust a DATE object that does not already have a time component with a timezone setting.  It seems the [offending lines](https://github.com/confluentinc/kafka-connect-jdbc/blob/e7b424ac80a1fbd7ce142d3b6bfc9dd3512dc2e4/src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java#L1235) should be removed.  Thoughts?
