### ISSUE TITLE
JDBC sink connector for more then one topic not working 

### ISSUE THREAD

**Issue by vaibhavpatil123** [confluentinc/kafka-connect-jdbc#685]
Below config for sink connector not working 
{

    "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
    "database.dbname": "db1",
    "connection.password": "postgres",
    **"topics": "db1.public.t1,db1.public.t2",**
    "transforms": "unwrap",
    "database.server.name": "db1",
    "database.port": "31642",
    "database.hostname": "10.105.32.218",
    "connection.user": "postgres",
    "name": "pg_sink_connector_db1",
    "auto.create": "true",
    "transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
    "connection.url": "jdbc:postgresql://21212:31642/db1?user=postgres&password=postgres",
    "tasks.max" :"3"

    
}

getting error as below :

Caused by: org.apache.kafka.connect.errors.ConnectException: io.debezium.data.VariableScaleDecimal (STRUCT) type doesn't have a mapping to the SQL database column type
--
  | at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.getSqlType(GenericDatabaseDialect.java:1709)
  | at io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialect.getSqlType(PostgreSqlDatabaseDialect.java:215)

**Comment by vaibhavpatil123** [comment]
using topics="t1,t2,t3"

Working config so closing ticket
