### ISSUE TITLE
Prepared statement breaks on PostgreSQL when schema changed

### ISSUE THREAD

**Issue by gfodor** [confluentinc/kafka-connect-jdbc#69]
There is an issue when using prepared statements on PostgreSQL with wildcard (SELECT *) queries -- if the schema is changed so the query columns will change, then the following error occurs:

```
ERROR Failed to run query for table TimestampIncrementingTableQuerier{name='spaces', query='null', topicPrefix='positron-db-', timestampColumn='updated_at', incrementingColumn='null'}: {} (io.confluent.connect.jdbc.JdbcSourceTask:239)
org.postgresql.util.PSQLException: ERROR: cached plan must not change result type
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:495)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:380)
```

PR available at #68

**Comment by wicknicks** [comment]
Thanks for pointing out this bug! A simple workaround for this issue would be to restart the connector with the [REST API](https://docs.confluent.io/current/connect/references/restapi.html#post--connectors-(string-name)-restart).

**Comment by marbon87** [comment]
We had the same problem and restarting the connector did not help. We had to restart the postgres-instance.

**Comment by marbon87** [comment]
the solution is to DEALLOCATE <STMT_NAME> the prepared statements or instead use DEALLOCATE ALL.

test setup:
create table foo(a text);
prepare x as select a from foo;
insert into foo values ('1');

execute x;

--> no problem

alter table foo alter a type int using a::int;

execute x;

ERROR:  cached plan must not change result type

deallocate x; // or deallocate all

prepare x as select a from foo;

execute x;

--> no problem

**Comment by PSanetra** [comment]
It looks like you can work around the problem by adding the option `preparedStatementCacheQueries=0` to the connection url. This prevents the connector from caching queries using "Server Prepared Statements" (See [psql jdbc docs](https://jdbc.postgresql.org/documentation/head/connect.html#connection-parameters)).

**Comment by GiannisDimitriou** [comment]
There is another option `autosave=conservative` you can set to the connection url as stated [here](https://stackoverflow.com/questions/2783813/postgres-error-cached-plan-must-not-change-result-type/48536394#48536394) instead of disabling prepared statements. I have tried that but with no success though. 
Did anyone tried this option or is willing to test it as well ?
Thanks.
