### ISSUE TITLE
Desrializing error with JDBC sink from KSQL topic

### ISSUE THREAD

**Issue by Vetrenik** [confluentinc/kafka-connect-jdbc#718]
I'm trying to upload enriched data from KSQL-stream topic and getting the following deserialization error:
```
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:484)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:464)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:320)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: Failed to deserialize data for topic LOGIN_EVENT_3 to Avro:
    at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:107)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$0(WorkerSinkTask.java:484)
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
    ... 13 more
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id -1
Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!
```
I'm running standalone Zookeeper+Kafka+Schemaregistry+KSQL with distributed KafkaConnect using default **connect-avro-distributed.properties** file. 
The source data is loaded with JDBC source connectors from Porstgres, then transformed to KTables and KStreams and joined. 
Example of data in topic: 
```
{ 
   "LOGIN":{ 
      "string":"Vasya"
   },
   "SUCCESS":{ 
      "boolean":true
   },
   "DEVICEINFO":{ 
      "string":"Iphone X"
   },
   "ID":{ 
      "long":24
   },
   "IDCLIENT":{ 
      "int":1
   },
   "PAN":{ 
      "string":"4321223432123756"
   },
   "CUSTOMERID":{ 
      "int":111
   }
}
```
Got that data with **kafka-avro-console-consumer**
Topic schema from shema-registry is:
```
{
  "type": "record",
  "name": "KsqlDataSourceSchema",
  "namespace": "io.confluent.ksql.avro_schemas",
  "fields": [
	{
  	"name": "LOGIN",
  	"type": [
    	"null",
    	"string"
  	],
  	"default": null
	},
	{
  	"name": "SUCCESS",
  	"type": [
    	"null",
    	"boolean"
  	],
  	"default": null
	},
	{
  	"name": "DEVICEINFO",
  	"type": [
    	"null",
    	"string"
  	],
  	"default": null
	},
	{
  	"name": "ID",
  	"type": [
    	"null",
    	"long"
  	],
  	"default": null
	},
	{
  	"name": "IDCLIENT",
  	"type": [
    	"null",
    	"int"
  	],
  	"default": null
	},
	{
  	"name": "PAN",
  	"type": [
    	"null",
    	"string"
  	],
  	"default": null
	},
	{
  	"name": "CUSTOMERID",
  	"type": [
    	"null",
    	"int"
  	],
  	"default": null
	}
  ]
}
```
JDBC sink connector config is: 
```
{ 
   "connector.class":"io.confluent.connect.jdbc.JdbcSinkConnector",
   "connection.url":"jdbc:postgresql://192.168.76.183:5432/kafka",
   "connection.user":"postgres",
   "connection.password":"admin",
   "topics":"LOGIN_EVENT_3",
   "pk.mode":"record_value",
   "pk.field":"ID",
   "table.name.format":"target.login_event_enriched",
   "insert.mode":"insert",
   "auto.create":"true",
   "key.converter":"io.confluent.connect.avro.AvroConverter",
   "value.converter":"io.confluent.connect.avro.AvroConverter",
   "auto.evolve":"true",
   "task.max":"1",
   "key.converter.schema.registry.url":"http://localhost:8081",
   "value.converter.schema.registry.url":"http://localhost:8081"
}
```

**Comment by rmoff** [comment]
KSQL writes string keys, so you need 

    "key.converter":"org.apache.kafka.connect.storage.StringConverter'",
