### ISSUE TITLE
Support for topic prefix filter when establishing table name

### ISSUE THREAD

**Issue by daniellavoie** [confluentinc/kafka-connect-jdbc#731]
# Problem Description 

Currently, the Sink Connector can use a placeholder in the table name format. This means that the table name will be composed from the entire topic name. For a table called`customers`, the only option is to have a topic explicitly named `customers`. Table name format allows to mutate the destination name but not the source topic name. 

Kafka being generally used in a multi-tenant environment, I might be interested in prefixing the topic names while the target table name is stripped from that prefix. 

Example : topic : `database1.cdc.customers` and target table name : `customers`. This would allow handling table name conflict if Kafka is used to sink tables from different data sources to different databases.

# Proposal

Add a filter configuration to the table name format. For example : `topic.name-prefix` set to `database1.cdc`. This configuration would be used to filter the prefix from the target table name.

**Comment by starcalm** [comment]
Why not just define `table.name.format` to be what you want? in your example just configure it to be "customers"?

**Comment by daniellavoie** [comment]
Great recommendation, however, it means one connector instance per table. With a `topic.name-prefix`, it would still be possible to support multiple tables with a single connector instance.

**Comment by junzebao** [comment]
ah yes, good point! It might be too much trouble to create one connector for one topic. I just found out some useful [transformations](https://docs.confluent.io/current/connect/transforms/index.html) that might give something working without what you're asking for. Like you could use the `InsertField` to inject the topic name into the key or value and then use the `ExtractTopic` to change the record topic. It sounds much of a trouble though ;) (Caveat: the `ExtractTopic` transformation is only provided by Confluent, not Apache Kafka)

I do see the need for the issue you brought up though and I think we'll probably face similar issues too.  Hope they'll consider it, but at least we have some hacky "workarounds".

**Comment by hishamjaved** [comment]
This is very much needed feature to join multiple topics to merge the data from different source topics of different tenants into one sink table. Option should be generic to cater all the cases.

**Comment by ahmetorhan** [comment]
I have tried the above-suggested config and got the following error, I am not sure if anyone succeeded or not. Maybe I am missing something?

Config:
```
{
	"name": "jdbc-sink",
	"config": {
	"connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
	"tasks.max": "1",		
	"connection.url": "jdbc:mysql://mariadb-sink:3306/rsp_audit?verifyServerCertificate=false&nullCatalogMeansCurrent=true",
	"connection.user": "root",
	"connection.password": "*****",
        "topics.regex": "mariadb-source\\.mydb\\.(.*)",
	"auto.create": "true",
        "auto.evolve": "true",
	"insert.mode": "upsert",
        "transforms": "route, unwrap",
        "transforms.route.type": "org.apache.kafka.connect.transforms.RegexRouter",
        "transforms.route.regex": "([^.]+)\\.([^.]+)\\.([^.]+)",
        "transforms.route.replacement": "$3",
        "transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
        "transforms.unwrap.drop.tombstones": "false",
        "delete.enabled": "true",
        "pk.mode": "record_key",
        "key.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "key.converter.schemas.enable": "false",
        "value.converter.schemas.enable": "false"
	}
}

```

Stacktrace:

```
[2020-10-21 11:27:10,671] ERROR WorkerSinkTask{id=jdbc-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: null (org.apache.kafka.connect.runtime.WorkerSinkTask:586)
java.lang.NullPointerException
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:174)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:72)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:198)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
[2020-10-21 11:27:10,673] ERROR WorkerSinkTask{id=jdbc-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:187)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:588)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:198)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:174)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:72)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
	... 10 more
```


Using Apache Kafka 2.6.0, kafka-connect-jdbc (confluent sink) : 5.3.2, Debezium source connector: 1.3.0.Final

**Comment by orasik** [comment]
I faced the same issue, the solution is to use dropPrefix.

Example, to save data from topic hello.dbo.table1,hello.dbo.table2 to table1 and table2 in the database, use the following config:

```
    tasks.max: 1
    topics: hello.dbo.table1, hello.dbo.table2
    connection.url: jdbc:sqlserver://server:port;database=dbname;user=dbuser
    connection.user: dbuser
    connection.password: dbpass
    transforms: dropPrefix,unwrap
    transforms.dropPrefix.type: org.apache.kafka.connect.transforms.RegexRouter
    transforms.dropPrefix.regex: hello\.dbo\.(.*)
    transforms.dropPrefix.replacement: $1
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: false
    auto.create: true
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: true
    insert.mode: upsert
    delete.enabled: true
    pk.mode: record_key
```

**Comment by sauljabin** [comment]
> I faced the same issue, the solution is to use dropPrefix.
> 
> Example, to save data from topics `hello.dbo.table1`,`hello.dbo.table2` to `table1` and `table2` in the database, use the following config:
> 
> ```
>     tasks.max: 1
>     topics: hello.dbo.table1, hello.dbo.table2
>     connection.url: jdbc:sqlserver://server:port;database=dbname;user=dbuser
>     connection.user: dbuser
>     connection.password: dbpass
>     transforms: dropPrefix,unwrap
>     transforms.dropPrefix.type: org.apache.kafka.connect.transforms.RegexRouter
>     transforms.dropPrefix.regex: hello\.dbo\.(.*)
>     transforms.dropPrefix.replacement: $1
>     transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
>     transforms.unwrap.drop.tombstones: false
>     auto.create: true
>     value.converter: org.apache.kafka.connect.json.JsonConverter
>     value.converter.schemas.enable: true
>     insert.mode: upsert
>     delete.enabled: true
>     pk.mode: record_key
> ```

It works perfectly, thanks!, I do not understand why the unwrap

**Comment by tushargoyal22** [comment]
if I specify `table.name.format` as just table_name which is `raft_tbl` in my case then it dumps the data in the table under the default schema `dbo`

whereas when I tried to specify `table.name.format` as `guest.raft_tbl` where `guest` is one of the schemas in my database, **com.microsoft.sqlserver.jdbc.SQLServerException: Database 'guest' does not exist. Make sure that the name is entered correctly.** , I am not sure **why it is looking for Database `guest`**


JDBC sink connector config for reference

```
{
    "name": "SinkConnector3",
    "config": {
        "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
        "tasks.max": 1,
        "topics": "raft.public.goyaltu.subscription.manager.test_client",

        "key.converter": "io.confluent.connect.avro.AvroConverter",
        "key.converter.schema.registry.url": "http://mwkafka-schema-registry-staging.deshaw.com:5036",
        "value.converter": "io.confluent.connect.avro.AvroConverter",
        "value.converter.schema.registry.url": "http://mwkafka-schema-registry-staging.deshaw.com:5036",

        "transforms": "AlignSchemaWithRegistry",
        "transforms.AlignSchemaWithRegistry.type": "deshaw.raft.connect.transforms.AlignSchemaWithRegistry",
        "transforms.AlignSchemaWithRegistry.schema.registry.urls": "http://mwkafka-schema-registry-staging.deshaw.com:5036",

        "connection.url": "jdbc:sqlserver://riskdb;databaseName=sandbox;integratedSecurity=true;authenticationScheme=JavaKerberos;encrypt=true;trustServerCertificate=true;",

        "dialect.name": "SqlServerDatabaseDialect",

        "insert.mode": "upsert",
        "table.name.format": "guest.raft_tbl",
        "pk.mode": "record_key",
        "pk.fields": "id",
        "batch.size": "2",
        "poll.interval.ms": 60000,

        "tasks.recovery.mechanism": "STATE_BASED",


        "consumer.override.client.id": "raft.goyaltu.sinkconnector.jdbc.client",
        "consumer.override.group.id": "raft.test.sinkconnector.consumer",

        "consumer.override.java.security.auth.login.config": "/prod/tools/middleware/kafkautils/dist/etc/config/kafka/zookeeper_client_jaas.conf",
        "consumer.override.security.protocol": "SASL_PLAINTEXT",
        "consumer.override.sasl.mechanism": "GSSAPI",
        "consumer.override.sasl.kerberos.service.name": "kafka",
        "consumer.override.sun.security.jgss.native": true,
        "consumer.override.sun.security.jgss.lib": "/usr/libexec/libgsswrap.so",
        "consumer.override.javax.security.auth.useSubjectCredsOnly": false
    }
}

```
