### ISSUE TITLE
Kafka Connect JDBC Sink with Teradata failing with ipv6 address not found issue

### ISSUE THREAD

**Issue by rb5acgusr** [confluentinc/kafka-connect-jdbc#736]
I am trying to load data from Kafka topic to Teradata database. The connector fails with could not connect to ipv6 address. I am able to test that CLIV2 connection to Teradata is working fine. 

Caused by: java.sql.SQLException: [Teradata JDBC Driver] [TeraJDBC 16.20.00.10] [Error 1000] [SQLState 08S01] Login failure for Connection to 192.168.157.145:1025 Mon Nov 04 16:01:51 UTC 2019 socket orig=192.168.157.145:1025 cid=161f8496 sess=0 java.net.UnknownHostException: 192.168.157.145:1025: invalid IPv6 address  at java.net.InetAddress.getAllByName(InetAddress.java:1170)  at java.net.InetAddress.getAllByName(InetAddress.java:1127)  at com.teradata.jdbc.jdbc_4.io.TDNetworkIOIF$Lookup.doLookup(TDNetworkIOIF.java:223)  at com.teradata.jdbc.jdbc_4.io.TDNetworkIOIF$Lookup.isLiteralIpAddress(TDNetworkIOIF.java:249)  at com.teradata.jdbc.jdbc_4.io.TDNetworkIOIF.connectToHost(TDNetworkIOIF.java:336)  at com.teradata.jdbc.jdbc_4.io.TDNetworkIOIF.createSocketConnection(TDNetworkIOIF.java:156)  at com.teradata.jdbc.jdbc_4.io.TDNetworkIOIF.<init>(TDNetworkIOIF.java:142)  at com.teradata.jdbc.jdbc.GenericTeradataConnection.getIO(GenericTeradataConnection.java:143)  at com.teradata.jdbc.jdbc.GenericLogonController.run(GenericLogonController.java:100)  at com.teradata.jdbc.jdbc_4.TDSession.<init>(TDSession.java:211)  at com.teradata.jdbc.jdk6.JDK6_SQL_Connection.<init>(JDK6_SQL_Connection.java:36)  at com.teradata.jdbc.jdk6.JDK6ConnectionFactory.constructSQLConnection(JDK6ConnectionFactory.java:25)  at com.teradata.jdbc.jdbc.ConnectionFactory.createConnection(ConnectionFactory.java:181)  at com.teradata.jdbc.jdbc.ConnectionFactory.createConnection(ConnectionFactory.java:171)  at com.teradata.jdbc.TeraDriver.doConnect(TeraDriver.java:236)  at com.teradata.jdbc.TeraDriver.connect(TeraDriver.java:162)  at java.sql.DriverManager.getConnection(DriverManager.java:664)  at java.sql.DriverManager.getConnection(DriverManager.java:208)  at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.getConnection(GenericDatabaseDialect.java:211)  at io.confluent.connect.jdbc.util.CachedConnectionProvider.newConnection(CachedConnectionProvider.java:88)  at io.confluent.connect.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:62)  at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:56)  at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)  at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)  at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)  at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)  at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)  at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)  at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)  at java.util.concurrent.FutureTask.run(FutureTask.java:266)  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)  at java.lang.Thread.run(Thread.java:748)
        at com.teradata.jdbc.jdbc_4.util.ErrorFactory.makeDriverJDBCException(ErrorFactory.java:95)
        at com.teradata.jdbc.jdbc_4.util.ErrorFactory.makeDriverJDBCException(ErrorFactory.java:70)
        at com.teradata.jdbc.jdbc_4.util.ErrorFactory.makeIoJDBCException(ErrorFactory.java:208)
        at com.teradata.jdbc.jdbc_4.util.ErrorAnalyzer.analyzeIoError(ErrorAnalyzer.java:59)
        at com.teradata.jdbc.jdbc_4.io.TDNetworkIOIF.createSocketConnection(TDNetworkIOIF.java:163)
        at com.teradata.jdbc.jdbc_4.io.TDNetworkIOIF.<init>(TDNetworkIOIF.java:142)
        at com.teradata.jdbc.jdbc.GenericTeradataConnection.getIO(GenericTeradataConnection.java:143)
        at com.teradata.jdbc.jdbc.GenericLogonController.run(GenericLogonController.java:100)
        at com.teradata.jdbc.jdbc_4.TDSession.<init>(TDSession.java:211)
        at com.teradata.jdbc.jdk6.JDK6_SQL_Connection.<init>(JDK6_SQL_Connection.java:36)
        at com.teradata.jdbc.jdk6.JDK6ConnectionFactory.constructSQLConnection(JDK6ConnectionFactory.java:25)

How to pass prefer ipv4 address setting in Kafka connection json file?

**Comment by rb5acgusr** [comment]
I realized when I do not put port information in JDBC URL it is working fine. But, I feel this needs to be fixed.

**Comment by gharris1727** [comment]
@rb5acgusr I think the behavior for handling IPv4 vs IPv6 addresses in the `connection.url` is completely contained within the Teradata JDBC driver, and neither Connect nor the JDBC connector has a lot of say over what is accepted and what is not.

It appears that the [Teradata JDBC URL specification](https://teradata-docs.s3.amazonaws.com/doc/connectivity/jdbc/reference/current/jdbcug_chapter_2.html#BABJIHBJ) doesn't support the `:<port>` syntax for specifying the database port, and instead uses the `DBS_PORT=<port>` option.

On an unrelated note, you should be aware that there is a known issue with time and date timezone conversions when using Teradata with this connector. Please use caution and test the connector before deploying it to make sure that it's behaving how you expect. We're planning on releasing a Teradata Connector soon on Confluent Hub that officially supports the Teradata database, and will address this issue.

**Comment by gharris1727** [comment]
If you have any more questions, please re-open this issue and i'd be happy to answer them.
