### ISSUE TITLE
Jdbc Sink Connector tries to validate the value schema of a tombstone record (MySql)

### ISSUE THREAD

**Issue by gkalogiros-nutmeg** [confluentinc/kafka-connect-jdbc#744]
Hi, 

I'm trying to use the Sink Connector in order to insert/delete entries based on a Kafka topic but I hit a blocking issue.

While, the insertion works like a dream, the deletion fails. 

It seems that the connector tries to validate the schema of the value for a tombstone record. In my opinion it shouldn't do that given that it's `null`.  

The interesting part is that the problem only appears when I use the `org.apache.kafka.connect.transforms.ReplaceField$Value` transformation. Unfortunately, I can't avoid it as my record's field names do not map 100% to my column names.

You can see the details/exception below:

Versions:
```
Kafka Connect: 5.3.1
Jdbc Connector: 5.3.1
MySql Server: 8.0.15
Driver: mysql-connector-java-8.0.18
```

Connector Configuration:
```
{
    "name": "sink-connector",
    "config": {
        "table.name.format": "test_table",
        "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
        "connection.url": "jdbc:mysql://database:3306/test?useUnicode=true&characterEncoding=utf8",
        "connection.user": "user",
        "connection.password": "pass",
        "batch.size": "1",
        "insert.mode": "upsert",
        "delete.enabled": "true",
        "pk.mode": "record_key",
        "pk.fields": "entityId",
        "tasks.max": "1",
        "topics": "test-topic",
        "key.converter": "org.apache.kafka.connect.storage.StringConverter",
        "value.converter": "io.confluent.connect.avro.AvroConverter",
        "value.converter.schema.registry.url": "http://kafka-schema-registry:8081",
        "auto.create": "true",
        "auto.evolve": "true",
        "transforms": "RenameFields",
        "transforms.RenameFields.type": "org.apache.kafka.connect.transforms.ReplaceField$Value",
        "transforms.RenameFields.renames": "id:entityId,producedAt:createdAt",
        "max.retries": "3",
        "retry.backoff.ms": "1000"
    }
}
```

Connector Exception:
```
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
	at org.apache.kafka.connect.runtime.TransformationChain.apply(TransformationChain.java:50)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:506)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:464)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:320)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: Only Map objects supported in absence of schema for [field replacement], found: null
	at org.apache.kafka.connect.transforms.util.Requirements.requireMap(Requirements.java:38)
	at org.apache.kafka.connect.transforms.ReplaceField.applySchemaless(ReplaceField.java:134)
	at org.apache.kafka.connect.transforms.ReplaceField.apply(ReplaceField.java:127)
	at org.apache.kafka.connect.runtime.TransformationChain.lambda$apply$0(TransformationChain.java:50)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
```

I'd appreciate any help!

Thank you very much!

**Comment by aelsaman** [comment]
any updates here? is this resolved or is it just invalid bug? @gkalogiros-nutmeg

**Comment by gkalogiros-nutmeg** [comment]
> any updates here? is this resolved or is it just invalid bug? @gkalogiros-nutmeg

@aelsaman it was indeed a problem but mainly related to Kafka transforms. Have a look at this ticket: https://issues.apache.org/jira/browse/KAFKA-9204
