### ISSUE TITLE
MySQL: sink confused / breaks when multiple databases 

### ISSUE THREAD

**Issue by ctoomey** [confluentinc/kafka-connect-jdbc#778]
I've got a target sink server with multiple schemas/databases, call them `A`, `B`, and `C`. I'm trying to use the sink connector to write to `C.users`, which exists, but it keeps failing with the error `java.sql.SQLSyntaxErrorException: Table 'A.users' doesn't exist`, which it's hitting per the following stack trace. I've tried both the following ways of telling it to write to `C.users` and both result in the same error, with either the MySQLDialect and the Generic one. Prior to the exception it logs `INFO Using Generic dialect table "C"."users" present` in case of Config 2.

Any ideas how to workaround or fix this?

Config 1:
```
connection.url=jdbc:mysql://localhost:30003/C
...
table.name.format=users
```

Config 2:
```
connection.url=jdbc:mysql://localhost:30003/
...
table.name.format=C.users
```

```
java.sql.SQLSyntaxErrorException: Table 'A.users' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1218)
	at com.mysql.cj.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:2980)
	at com.mysql.cj.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:2968)
	at com.mysql.cj.jdbc.IterateBlock.doForAll(IterateBlock.java:56)
	at com.mysql.cj.jdbc.DatabaseMetaData.getPrimaryKeys(DatabaseMetaData.java:3021)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.primaryKeyColumns(GenericDatabaseDialect.java:729)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.describeColumns(GenericDatabaseDialect.java:566)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.describeTable(GenericDatabaseDialect.java:765)
	at io.confluent.connect.jdbc.util.TableDefinitions.get(TableDefinitions.java:62)
	at io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:58)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:121)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:66)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
```

When I set `table.name.format` to a particular db/table like `C.users`

**Comment by ctoomey** [comment]
I found  a workaround for config. 1 (specifying the target database/schema on the MySQL connection URL), but this workaround is limited to cases where you're only writing to a single target db/schema that is known in advance. So it's still a bug that config. 2 doesn't work, and without a fix a connector would be subject to this single db/schema limitation using the workaround.

The workaround: add parameter `nullDatabaseMeansCurrent=true` to the connection URL in which you've specified the target DB, e.g., update config. 1 to be

```
connection.url=jdbc:mysql://localhost:30003/C?nullDatabaseMeansCurrent=true
...
table.name.format=users
```
