### ISSUE TITLE
the connector can not find oracle jdbc driver

### ISSUE THREAD

**Issue by luckyJonh** [confluentinc/kafka-connect-jdbc#822]
I have viewed other issues mentioned problems like mine,but it did not work ,there are some  configurations of my connector and some logs:

**connnector properties:**

```
name=feed_like_subject_data
connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
tasks.max=1
connection.password=xxx
connection.url=jdbc:oracle:thin:@192.xxx.xx.xxx:1521:orcl
connection.user=xxx
table.whitelist=T_TABLE
mode=timestamp+incrementing
timestamp.column.name=UPDATE_TIME
incrementing.column.name=ID
topic.prefix=test-feed_like
timestamp.delay.interval.ms=1584668294000
dialect.name=OracleDatabaseDialect
```

**log of  loading plugins**

```
2020-03-20 20:17:52,778] INFO Loading plugin from: /usr/local/src/kafka_2.12-2.4.1/share/jdbc/plugins/kafka-connect-jdbc-5.4.1.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:241)
[2020-03-20 20:17:52,778] DEBUG Loading plugin urls: [file:/usr/local/src/kafka_2.12-2.4.1/share/jdbc/plugins/kafka-connect-jdbc-5.4.1.jar] (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:248)

[2020-03-20 20:17:52,880] INFO Added plugin 'io.confluent.connect.jdbc.JdbcSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:193)

[2020-03-20 20:17:53,333] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/local/src/kafka_2.12-2.4.1/share/jdbc/plugins/ojdbc7.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:264)
[2020-03-20 20:17:53,400] DEBUG Registered java.sql.Driver: oracle.jdbc.OracleDriver@6f195bc3 to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:300)
[2020-03-20 20:17:58,166] DEBUG Skipping class org.apache.kafka.connect.sink.SinkConnector as it is not concrete implementation (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:352)
[2020-03-20 20:17:58,210] DEBUG Skipping class org.apache.kafka.connect.source.SourceConnector as it is not concrete implementation (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:352)
[2020-03-20 20:17:58,212] DEBUG Skipping class org.apache.kafka.connect.converters.NumberConverter as it is not concrete implementation (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:352)
```

**and  the errores of connect logs**

```
[2020-03-20 20:18:02,019] DEBUG Using dialect OracleDatabaseDialect with score 100 against JDBC subprotocol 'oracle' and source 'jdbc:oracle:thin:@192.168.11.170:1521:orcl' (io.confluent.connect.jdbc.dialect.DatabaseDialects:133)
[2020-03-20 20:18:02,021] INFO AbstractConfig values: 
 (org.apache.kafka.common.config.AbstractConfig:347)
[2020-03-20 20:18:02,029] ERROR Failed to create job for config/oracle-liked-data-connector.properties (org.apache.kafka.connect.cli.ConnectStandalone:110)
[2020-03-20 20:18:02,031] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:121)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid and contains the following 2 error(s):
Invalid value java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@192.168.11.170:1521:orcl for configuration Couldn't open connection to jdbc:oracle:thin:@192.168.11.170:1521:orcl
Invalid value java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@192.168.11.170:1521:orcl for configuration Couldn't open connection to jdbc:oracle:thin:@192.168.11.170:1521:orcl
You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
	at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:115)
	at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:99)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:118)
Caused by: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid and contains the following 2 error(s):
Invalid value java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@192.168.11.170:1521:orcl for configuration Couldn't open connection to jdbc:oracle:thin:@192.168.11.170:1521:orcl
Invalid value java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@192.168.11.170:1521:orcl for configuration Couldn't open connection to jdbc:oracle:thin:@192.168.11.170:1521:orcl
You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
	at org.apache.kafka.connect.runtime.AbstractHerder.maybeAddConfigErrors(AbstractHerder.java:560)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:194)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:115)
```
my JDK version is 1.8,and oracle version is 11g.I hava tried to use ojdbc8.jar instead of ojdbc7.jar,it did not work neither......

**Comment by luckyJonh** [comment]
I found it is my mistake....

**Comment by jimtoGXYZ** [comment]
跟你错误一毛一样
