### ISSUE TITLE
"value.converter.schemas.enable": "false" doesn't work 

### ISSUE THREAD

**Issue by barambuk** [confluentinc/kafka-connect-jdbc#824]
Hello, 
I would like to use kafka connect jdbc sink to store messages in PostgreSQL. I'm using cnfldemos/cp-server-connect-datagen:0.2.0-5.4.0 docker and last version of postgres in docker as well. The message in topic in plain json format without schema. I don't want to attach the schema to each message so according to Robin Moffatt's [article ](https://rmoff.net/2017/09/06/kafka-connect-jsondeserializer-with-schemas.enable-requires-schema-and-payload-fields), I can use "value.converter.schemas.enable": "false" . Unfortunately after using this parameter,  I got following error:

```
connect             | org.apache.kafka.connect.errors.ConnectException: No fields found using key and value schemas for table: status
connect             |   at io.confluent.connect.jdbc.sink.metadata.FieldsMetadata.extract(FieldsMetadata.java:126)
connect             |   at io.confluent.connect.jdbc.sink.metadata.FieldsMetadata.extract(FieldsMetadata.java:63)
connect             |   at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:114)
connect             |   at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:66)
connect             |   at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
connect             |   at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
connect             |   at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
connect             |   at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
connect             |   at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
connect             |   at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
connect             |   at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
connect             |   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
connect             |   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
connect             |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
connect             |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
connect             |   at java.lang.Thread.run(Thread.java:748)
connect             | [2020-03-26 09:10:35,776] ERROR WorkerSinkTask{id=status-jdbc-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
connect             | org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
connect             |   at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:561)
connect             |   at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
connect             |   at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
connect             |   at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
connect             |   at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
connect             |   at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
connect             |   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
connect             |   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
connect             |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
connect             |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
connect             |   at java.lang.Thread.run(Thread.java:748)
connect             | Caused by: org.apache.kafka.connect.errors.ConnectException: No fields found using key and value schemas for table: status
connect             |   at io.confluent.connect.jdbc.sink.metadata.FieldsMetadata.extract(FieldsMetadata.java:126)
connect             |   at io.confluent.connect.jdbc.sink.metadata.FieldsMetadata.extract(FieldsMetadata.java:63)
connect             |   at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:114)
connect             |   at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:66)
connect             |   at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
connect             |   at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
connect             |   ... 10 more
```

So, it seems to me, that the feature doesn't work.

Connector's config is attached:
```
{
  "name": "status-jdbc-sink",
  "config": {
    "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
    "tasks.max": "1",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": "false",
    "connection.user": "postgres",
    "connection.password": "postgres",
    "topics": "status",
    "auto.create": "true",
    "connection.url": "jdbc:postgresql://postgres:5432/postgres"
  }
```

**Comment by rmoff** [comment]
You've only got half the story there though :) The setting *does* work, but the connector, in this case, *requires* that you have a schema to your data. 

Check out this section of my tutorial here to understand more: https://www.youtube.com/watch?v=b-3qN_tlYR4&t=981
