### ISSUE TITLE
Deadlock occure every time when writing to SQL Server

### ISSUE THREAD

**Issue by Yosafat1997** [confluentinc/kafka-connect-jdbc#829]
I have experienced this issue many times in my JDBC sink:
```
[2020-04-02 12:50:45,627] INFO JdbcDbWriter Connected (io.confluent.connect.jdbc.sink.JdbcDbWriter:49)
[2020-04-02 12:50:45,700] WARN Write of 37 records failed, remainingRetries=10 (io.confluent.connect.jdbc.sink.JdbcSinkTask:76)
com.microsoft.sqlserver.jdbc.SQLServerException: Transaction (Process ID 98) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet$FetchBuffer.nextRow(SQLServerResultSet.java:5431)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.fetchBufferNext(SQLServerResultSet.java:1770)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.next(SQLServerResultSet.java:1028)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.tableExists(GenericDatabaseDialect.java:543)
	at io.confluent.connect.jdbc.util.TableDefinitions.get(TableDefinitions.java:61)
	at io.confluent.connect.jdbc.sink.DbStructure.amendIfNecessary(DbStructure.java:112)
	at io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:74)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:120)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:66)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[2020-04-02 12:50:45,700] INFO Closing connection #1 to SqlServer (io.confluent.connect.jdbc.util.CachedConnectionProvider:118)
```
And in the end several table cannot written to SQL Server. I use JDBC connectors v.5.4.1 and SQL Server 2019. I operate this connectors in distributed mode. Any help are appreciated.

This is my connectors config:
```
{
	"name" : "sqlservercon_$FILENAME",
		"config":{
    			"connector.class":"io.confluent.connect.jdbc.JdbcSinkConnector",
    			"topics":"$FILENAME",
    			"connection.url":"jdbc:sqlserver:/XXX",
    			"transforms":"unwrap",
    			"transforms.unwrap.type":"io.debezium.transforms.ExtractNewRecordState",
    			"transforms.unwrap.drop.tombstones":"false",
    			"auto.create":"true",
   	 		"insert.mode":"upsert",
    			"pk.fields":"$PK_FIELD",
    			"pk.mode":"record_key",
    			"destination.table.format":"db.dbo.$FILENAME",
    			"errors.tolerance":"all",
			"flush.size": "10000"
}
}
```

**Comment by Yosafat1997** [comment]
any updates for this?

**Comment by gharris1727** [comment]
@Yosafat1997 

The stacktrace indicates that the deadlock is occurring when we test whether the table exists, in order to create the table if it does not exist. The connector does this by calling [`connection.getMetaData().getTables()`](https://github.com/confluentinc/kafka-connect-jdbc/blob/28dbe1c4212cd43ce398dc8375c6183556d4a1a9/src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java#L537), which in SQLServer executes [sp_tables](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-tables-transact-sql?view=sql-server-ver15) to list the tables.

As to why it is deadlocking, that is unclear from this stacktrace. Do you have other clients on the database that may be creating or altering tables while the connector is running? I think that you may be able to reproduce this error by calling `sp_tables` directly from another sql client, and use that to further diagnose any deadlocks inside of your database.

**Comment by Yosafat1997** [comment]
I maybe have some client i guess, for example opening it in DB dashboard like MSSQL Manager or DBeaver for monitoring purpose with the same connection properties. Is there any problems with that?

**Comment by gharris1727** [comment]
Since it's a deadlock, it's my intuition that it's an interaction with some other client and the locks that they hold causing the error. You'll need to debug further to figure out exactly what's happening. I see [`sp_lock`](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-lock-transact-sql?view=sql-server-ver15) mentioned in some deadlock debugging guides, so perhaps you can take a look at that.

**Comment by Yosafat1997** [comment]
i see, i will check the sp_lock this morning and i will tell if something interesting are found. this problems make several tables from my source connection are not inserted properly

**Comment by Yosafat1997** [comment]
I have check all performance in database. I have more than 1 connection using my database user to same db. I see due i use several kafka sink to the same database, but to different database. This is because i have different tables to pull and different pk. Some of them in sleep condition. If it's okay, is  kafka connection can be killed after there's no new messages with listening topic, and attached again if there's new message come.

**Comment by Yosafat1997** [comment]
I see, if several retry failed, the task stop and the table cannot be listed, follow by several warn and error at the end. Here's the detailed error I have:
```
[2020-04-03 00:35:15,044] WARN Write of 20 records failed, remainingRetries=0 (io.confluent.connect.jdbc.sink.JdbcSinkTask:76)
com.microsoft.sqlserver.jdbc.SQLServerException: Transaction (Process ID 175) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet$FetchBuffer.nextRow(SQLServerResultSet.java:5431)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.fetchBufferNext(SQLServerResultSet.java:1770)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.next(SQLServerResultSet.java:1028)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.tableExists(GenericDatabaseDialect.java:543)
	at io.confluent.connect.jdbc.util.TableDefinitions.get(TableDefinitions.java:61)
	at io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:58)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:120)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:66)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[2020-04-03 00:35:15,044] ERROR WorkerSinkTask{id=XXX} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:559)
org.apache.kafka.connect.errors.ConnectException: java.sql.SQLException: com.microsoft.sqlserver.jdbc.SQLServerException: Transaction (Process ID 175) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:87)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.sql.SQLException: com.microsoft.sqlserver.jdbc.SQLServerException: Transaction (Process ID 175) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

	... 12 more
[2020-04-03 00:35:15,044] ERROR WorkerSinkTask{id=XXX} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:561)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.connect.errors.ConnectException: java.sql.SQLException: com.microsoft.sqlserver.jdbc.SQLServerException: Transaction (Process ID 175) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:87)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
	... 10 more
Caused by: java.sql.SQLException: com.microsoft.sqlserver.jdbc.SQLServerException: Transaction (Process ID 175) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

	... 12 more
```

**Comment by Yosafat1997** [comment]
any updates about this? this is really challenging things.

**Comment by Yosafat1997** [comment]
> any updates about this? this is really challenging things.

as i found that no other user or client accessing the db other than my kafka jdbc connection

**Comment by house1081** [comment]
hi，when  insert mysql  has errors,how pass it  and  not killed the  task

**Comment by Yosafat1997** [comment]
**UPDATE**

So i have investigate the problem and lead me to two diagnose:

The first one is i assume there's workers exhausting due two heavy job from both connectors side (one connectors to pull data from postgresql and one connectors for push the message into SQL Server from database). I have see the behaviour if i restart the workers sometimes, new tables are inserted to db, but the number of rows are not same as actual number of postgres table. So o decide to make two workers, one for pull from postgres and one to push to sql server. However, after load some connectors to second workers, the connectors shutdown after several minutes and not give any error or warn on log.


The second one is, i see there's another connection to sql server with username name is same as my server name where kafka brokers established. I still don't know how it could be in there, but i assumed it makes deadlock problem with it.

The case is, i have 200 less or more connectors as same as number of tables. The problem is the techique that i need to use to deliver data as near as rea l time transfer from postgres to sql server. Still stuck around the sink problem. Have create each topic with only single partition and 3 replicas since i use 3 brokers have done, but no effect with the deadlock. Is connectors can have like switcher to choose which table should loaded?

**Comment by Yosafat1997** [comment]
**Another update:**

after checking for several minutes, and separate sink and source workers, I still face the problem. I think is it okay to put all sink connectors to one workers and let it works? For every topics that each sink consume, it only has 1 partition and 3 replicas. I still stuck at the deadlock problem.

**Comment by Yosafat1997** [comment]
I have solved this issue. At first operational, i need to group some tables based from its size, and prioritize table based from its size. Table larger than 100k rows must run first.
