### ISSUE TITLE
JDBC Sink Connector 

### ISSUE THREAD

**Issue by asthraa** [confluentinc/kafka-connect-jdbc#834]
I am having issue with JDBC Sink Connector Connecting to Oracle DB

```
kafka.connect.runtime.WorkerSourceTask:433)
Apr 15, 2020 12:32:40 AM oracle.simplefan.impl.FanManager configure
SEVERE: attempt to configure ONS in FanManager failed with oracle.ons.NoServersAvailable: Subscription time out
[2020-04-15 00:32:40,422] ERROR WorkerSinkTask{id=oracle_sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:559)
java.lang.IllegalArgumentException: ONS configuration failed
	at oracle.simplefan.impl.FanManager.configure(FanManager.java:108)
	at oracle.jdbc.driver.HAManager.configure(HAManager.java:146)
	at oracle.jdbc.driver.HAManager.<init>(HAManager.java:122)
	at oracle.jdbc.driver.HAManager.getInstance(HAManager.java:126)
	at oracle.jdbc.driver.HAManager.enableHAIfNecessary(HAManager.java:725)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:713)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.getConnection(GenericDatabaseDialect.java:224)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.newConnection(CachedConnectionProvider.java:93)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:62)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:56)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: oracle.ons.NoServersAvailable: Subscription time out
	at oracle.ons.NotificationNetwork.waitUntilOnline(NotificationNetwork.java:96)
	at oracle.ons.ONS.init(ONS.java:96)
	at oracle.ons.ONS.<init>(ONS.java:154)
	at oracle.simplefan.impl.FanManager$1.run(FanManager.java:102)
	at oracle.simplefan.impl.FanManager$1.run(FanManager.java:100)
	at java.security.AccessController.doPrivileged(Native Method)
	at oracle.simplefan.impl.FanManager.configure(FanManager.java:100)
	... 25 more
[2020-04-15 00:32:40,428] ERROR WorkerSinkTask{id=oracle_sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:561)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: ONS configuration failed
	at oracle.simplefan.impl.FanManager.configure(FanManager.java:108)
	at oracle.jdbc.driver.HAManager.configure(HAManager.java:146)
	at oracle.jdbc.driver.HAManager.<init>(HAManager.java:122)
	at oracle.jdbc.driver.HAManager.getInstance(HAManager.java:126)
	at oracle.jdbc.driver.HAManager.enableHAIfNecessary(HAManager.java:725)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:713)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.getConnection(GenericDatabaseDialect.java:224)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.newConnection(CachedConnectionProvider.java:93)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:62)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:56)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
	... 10 more
Caused by: oracle.ons.NoServersAvailable: Subscription time out
	at oracle.ons.NotificationNetwork.waitUntilOnline(NotificationNetwork.java:96)
	at oracle.ons.ONS.init(ONS.java:96)
	at oracle.ons.ONS.<init>(ONS.java:154)
	at oracle.simplefan.impl.FanManager$1.run(FanManager.java:102)
	at oracle.simplefan.impl.FanManager$1.run(FanManager.java:100)
	at java.security.AccessController.doPrivileged(Native Method)
	at oracle.simplefan.impl.FanManager.configure(FanManager.java:100)
	... 25 more
```

My sink-connector.properties

```
name=oracle_sink
connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
tasks.max=1
topics=schema-changes.inventory
connection.url=jdbc:oracle:thin:@IP:1521/servicename
connection.user=*****
connection.password=*****
auto.create=true
auto.evolve=true
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
```
Can anyone help where am I going wrong?

**Comment by gharris1727** [comment]
@asthraa I've never seen this issue before, but I found a similar error message in a stackoverflow post: https://stackoverflow.com/questions/58873384/spring-boot-app-error-log-says-attempt-to-configure-ons-in-fanmanager-failed-wit
You could try their suggestion to add `-Doracle.jdbc.fanEnabled=false` to the command line options before you start connect. You can also enable it with an environment variable if you don't want to edit any startup scripts: `export KAFKA_OPTS="-Doracle.jdbc.fanEnabled=false”`

**Comment by asthraa** [comment]
@gharris1727: I am beginner to kafka-connect. My sink database is Oracle. I have extracted the whole JDBC package from oracle into ```confluentinc-kafka-connect-jdbc-5.4.1/lib```directory. Below are the list of files you get from oracle package

```
ojdbc8.jar    ons.jar        orai18n.jar    osdt_core.jar  simplefan.jar  xdb6.jar
ojdbc.policy  oraclepki.jar  osdt_cert.jar  README.txt     ucp.jar
```
I removed ```simplefan.jar``` and restarted connector. It worked. I know this is not the optimal solution. But I got the job done.

My Source DB: MySQL
My Sink DB: Oracle
