### ISSUE TITLE
org.apache.kafka.connect.errors.DataException: JsonConverter with schemas.enable requires "schema" and "payload"

### ISSUE THREAD

**Issue by aditya-inapp** [confluentinc/kafka-connect-jdbc#859]
**Work Flow:**
Source Connector: Debezium SQL Server produces message to Topic1
Python Faust is used to stream messages from Topic1 to Topic2
Sink Connector:  Jdbc Sink connector (MySQL)  reads message from Topic2

Kafka: v2.5
Confluent JDBC Sink Connector: v5.5

Error occurs when **DELETE operation is performed in SQL Server DB**:
`[2020-05-19 15:14:48,158] ERROR WorkerSinkTask{id=arielai-mysql-sink-arielai-dev-39-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:488)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:465)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.connect.errors.DataException: JsonConverter with schemas.enable requires "schema" and "payload" fields and may not contain additional fields. If you are trying to deserialize plain JSON data, set schemas.enable=false in your converter configuration.
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:359)
	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:86)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$2(WorkerSinkTask.java:488)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
	... 13 more
[2020-05-19 15:14:48,162] ERROR WorkerSinkTask{id=arielai-mysql-sink-arielai-dev-39-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:180)
`

**MESSAGE in TOPIC1 (Key Value seperated by : colon)**
> {"schema":{"type":"struct","fields":[{"type":"int32","optional":false,"field":"ID"}],"optional":false,"name":"ariel2_39.dbo.Holidays.Key"},"payload":{"ID":112}}:null

**MESSAGE IN TOPIC2 (Key Value seperated by : colon)**
> {"schema": {"type": "struct", "fields": [{"type": "int32", "optional": false, "field": "ID"}], "optional": false, "name": "ariel2_39.dbo.Holidays.Key"}, "payload": {"ID": 112}}:null

Left Image: Topic1 & Right Image: Topic2
![delete](https://user-images.githubusercontent.com/58760801/82312261-6ee02d00-99e4-11ea-8c51-0b2b054f2e58.jpg)

Sink Config
![image](https://user-images.githubusercontent.com/58760801/82312471-b9fa4000-99e4-11ea-886f-44c2460a6adb.png)

**NOTE: All other operations works as expected.
NOTE: Delete works when sink connector reads directly from Topic1**
How does it not work when it reads from Topic 2 when both topics have the exact same message?

**Comment by adityagesh** [comment]
Kafka: v2.5
Confluent JDBC Sink Connector: v5.5

**Comment by aditya-inapp** [comment]
To further debug the issue, Workflow has been changed to,
Source connector -> Topic1 -> Sink Connector

1. Deleted record with ID 123 using SQL DELETE query. Tombstone record produced in topic1 by Source connector and consumed with sink connector without error.

![image](https://user-images.githubusercontent.com/58760801/82629573-c0b7cb80-9c0d-11ea-8843-2d31f5938bd7.png)

2. Deleted record with ID 121 by using console producer to produce message to topic1. **This results in an error**.
![image](https://user-images.githubusercontent.com/58760801/82629670-0f656580-9c0e-11ea-8fdf-0637db6e980e.png)

**ERROR:**
![image](https://user-images.githubusercontent.com/58760801/82629750-3fad0400-9c0e-11ea-968d-c43498d8d410.png)

**Comment by aditya-inapp** [comment]
**Found the issue**

![image](https://user-images.githubusercontent.com/58760801/82648602-8104da00-9c35-11ea-98f5-55d84ad95525.png)

Check the last two rows. 
The second last row is the tombstone record created by the debezium connector. In this case the null value results in empty message.
The last row is the tombstone record created by the console producer. In this case, the null value results in a **null string** in the message.

How do I solve this?

**Comment by aditya-inapp** [comment]
Solved it!
For anyone else looking at the same issue,
1. https://github.com/robinhood/faust/issues/597
2. https://stackoverflow.com/questions/61948427/kafka-jdbc-sink-org-apache-kafka-connect-errors-dataexception-jsonconverter
