### ISSUE TITLE
ORA-01000: maximum open cursors exceeded

### ISSUE THREAD

**Issue by dhawal55** [confluentinc/kafka-connect-jdbc#86]
I'm using kafka connect (Confluent platform v2.0.1) to pull data from Oracle db and getting the below error. Is there a connection leak?. Here's my job configuration:

```
{
  "name": "oracle-db-test",
  "config": {
    "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
    "tasks.max": "3",
    "connection.url": "jdbc:oracle:thin:user/password@hostname:port:dbname",
    "query": "SELECT * FROM TEST_DB",
    "mode": "timestamp",
    "timestamp.column.name": "MODIFIED_DATE",
    "topic.prefix": "test-topic"
  }
}
```

Error:

```
ERROR Error while trying to get updated table list, ignoring and waiting for next table poll interval (io.confluent.connect.jdbc.TableMonitorThread:107)
java.sql.SQLException: ORA-01000: maximum open cursors exceeded

    at oracle.jdbc.driver.SQLStateMapping.newSQLException(SQLStateMapping.java:70)
    at oracle.jdbc.driver.DatabaseError.newSQLException(DatabaseError.java:131)
    at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:204)
    at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:455)
    at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:413)
    at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:1034)
    at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:194)
    at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:791)
    at oracle.jdbc.driver.T4CPreparedStatement.executeMaybeDescribe(T4CPreparedStatement.java:866)
    at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1186)
    at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3387)
    at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3431)
    at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1203)
    at oracle.jdbc.OracleDatabaseMetaData.getTables(OracleDatabaseMetaData.java:2503)
    at io.confluent.connect.jdbc.JdbcUtils.getTables(JdbcUtils.java:90)
    at io.confluent.connect.jdbc.JdbcUtils.getTables(JdbcUtils.java:79)
    at io.confluent.connect.jdbc.TableMonitorThread.updateTables(TableMonitorThread.java:105)
    at io.confluent.connect.jdbc.TableMonitorThread.run(TableMonitorThread.java:61)
```

**Comment by ewencp** [comment]
I think you're right -- there's at least a couple of cases where the `ResultSet` from a call on `DatabaseMetadata` is not properly being closed.

**Comment by stewartbryson** [comment]
I'm still seeing this issue in Confluent Platform 3.0.

**Comment by shikhar** [comment]
@stewartbryson the fix will be in CP 3.0.1 (ETA next few days)

**Comment by SunYour** [comment]
Still present in 4.0.0

kafka-connect             | [2017-12-15 08:48:10,361] ERROR Error while trying to get updated table list, ignoring and waiting for next table poll interval (io.confluent.connect.jdbc.source.TableMonitorThread)
kafka-connect             | java.sql.SQLException: ORA-01000: maximum open cursors exceeded
kafka-connect             | ORA-06512: at "SYS.XML_SCHEMA_NAME_PRESENT", line 17
kafka-connect             |     at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
kafka-connect             |     at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
kafka-connect             |     at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)
kafka-connect             |     at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
kafka-connect             |     at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
kafka-connect             |     at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
kafka-connect             |     at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:225)
kafka-connect             |     at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:53)
kafka-connect             |     at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:774)
kafka-connect             |     at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:925)
kafka-connect             |     at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1111)
kafka-connect             |     at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4798)
kafka-connect             |     at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:4845)
kafka-connect             |     at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1501)
kafka-connect             |     at oracle.jdbc.OracleDatabaseMetaData.getTables(OracleDatabaseMetaData.java:3723)
kafka-connect             |     at io.confluent.connect.jdbc.util.JdbcUtils.getTables(JdbcUtils.java:89)
kafka-connect             |     at io.confluent.connect.jdbc.source.TableMonitorThread.updateTables(TableMonitorThread.java:121)
kafka-connect             |     at

**Comment by SunYour** [comment]
@rhauch When can we expect a fix for this one? Known workaround in the mean time?

**Comment by rhauch** [comment]
We'll be working on the JDBC connector issues over the next few months, but contributions are always welcome.

**Comment by SunYour** [comment]
@rhauch Of course :-)
Bug is also present in 3.3.1 but not in 3.3.0 is at least some kind of contribution.

**Comment by wicknicks** [comment]
There were framework level changes that caused this problem. This [commit](https://github.com/apache/kafka/commit/ee8abb2f7053575bd2abec8152907e0642b1d713) should have resolved this issue. 

Also, as discussed in https://community.oracle.com/thread/3774048, there were bugs in the older version of the Oracle driver. Upgrading to the latest version of the driver should resolve them.
