### ISSUE TITLE
Unable to load data into Redshift using Redshift sink connector

### ISSUE THREAD

**Issue by madhavvishnubhatta** [confluentinc/kafka-connect-jdbc#860]
Hi,

I am trying to load data from Kafka into Redshift using Redshift sink connector. I followed the instructions from here:
https://docs.confluent.io/current/connect/kafka-connect-aws-redshift/index.html#create-an-amazon-redshift-instance

When I try to load data, I get the following error.

```bash
[2020-05-19 20:39:17,163] DEBUG Received 500 records. First record kafka coordinates:(<tablename>-0-0). Writing them to the database... (io.confluent.connect.aws.redshift.jdbc.sink.JdbcSinkTask:68)
[2020-05-19 20:39:17,164] INFO Attempting to open connection #1 to Redshift (io.confluent.connect.aws.redshift.jdbc.util.CachedConnectionProvider:87)
[2020-05-19 20:39:17,595] INFO JdbcDbWriter Connected (io.confluent.connect.aws.redshift.jdbc.sink.JdbcDbWriter:49)
[2020-05-19 20:39:17,762] DEBUG Flushing records in JDBC Writer for table ID: "schemaname"."tablename" (io.confluent.connect.aws.redshift.jdbc.sink.JdbcDbWriter:71)
[2020-05-19 20:39:17,766] DEBUG Flushing 500 buffered records (io.confluent.connect.aws.redshift.jdbc.sink.BufferedRecords:169)
[2020-05-19 20:39:17,766] ERROR WorkerSinkTask{id=sink_redshift_8-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:559)
java.lang.NullPointerException
        at io.confluent.connect.aws.redshift.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:174)
        at io.confluent.connect.aws.redshift.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:72)
        at io.confluent.connect.aws.redshift.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2020-05-19 20:39:17,768] DEBUG WorkerSinkTask{id=sink_redshift_8-0} Skipping offset commit, no change since last commit (org.apache.kafka.connect.runtime.WorkerSinkTask:427)
[2020-05-19 20:39:17,768] DEBUG WorkerSinkTask{id=sink_redshift_8-0} Finished offset commit successfully in 0 ms for sequence number 1: null (org.apache.kafka.connect.runtime.WorkerSinkTask:264)
[2020-05-19 20:39:17,769] ERROR WorkerSinkTask{id=sink_redshift_8-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:561)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at io.confluent.connect.aws.redshift.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:174)
        at io.confluent.connect.aws.redshift.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:72)
        at io.confluent.connect.aws.redshift.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
        ... 10 more
[2020-05-19 20:39:17,769] ERROR WorkerSinkTask{id=sink_redshift_8-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:180)
[2020-05-19 20:39:17,769] INFO Stopping task (io.confluent.connect.aws.redshift.jdbc.sink.JdbcSinkTask:105)
[2020-05-19 20:39:17,769] INFO Closing connection #1 to Redshift (io.confluent.connect.aws.redshift.jdbc.util.CachedConnectionProvider:113)
```

Here is my config file:

```
name=sink_redshift
confluent.topic.bootstrap.servers=localhost:9092
confluent.topic.replication.factor=1
connector.class=io.confluent.connect.aws.redshift.RedshiftSinkConnector
aws.redshift.domain=*****************************************************
aws.redshift.port=*****
aws.redshift.database=****
aws.redshift.user=**************
aws.redshift.password=**************
topics=schemaname.tablename
auto.create:true
insert.mode=insert
```

The AWS cluster properties are correct, since the messages above show that a connection is successful. I tried with both true and false values for auto.create.

I see that someone else has raised [a similar issue on StackOverflow](https://stackoverflow.com/questions/61865407/kafka-redshift-connector-throwing-nullpointerexception).

Can someone help me find out what I am doing wrong?

**Comment by gharris1727** [comment]
I believe that this is an instance of #789, which happens if the data you're writing does not have schemas. Make sure to enable schemas for your converters (source and sink), and clear the topic of any bad records if you have to change the data source.

**Comment by madhavvishnubhatta** [comment]
That was indeed the reason. Thank you.
