### ISSUE TITLE
Table is created with NOT NULL fields even though they are not in the source

### ISSUE THREAD

**Issue by rmoff** [confluentinc/kafka-connect-jdbc#868]
Version: Confluent Platform 5.5

Expected behaviour: I should be able to specify a field as the primary key in order to use `upsert`, and other fields in the payload remain nullable

Actual behaviour: If I set `pk.mode=none` fields (e.g. `EMAIL`) are set to `NULL`. If I set `pk.mode=record_value` and a single field (`ID`) as the `pk.field`, *all* the fields are set to `NOT NULL. See logs and schema below. 

## pk.mode=none

This works fine: (pk.mode=none is the default and so implicit in the config here) 

```
curl -X PUT http://localhost:8083/connectors/sink-postgres-dbz-00/config \
    -H "Content-Type: application/json" \
    -d '{
        "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
        "key.converter": "io.confluent.connect.avro.AvroConverter",
        "key.converter.schema.registry.url": "http://schema-registry:8081",
        "connection.url": "jdbc:postgresql://postgres:5432/",
        "connection.user": "postgres",
        "connection.password": "postgres",
        "tasks.max": "1",
        "topics": "ora-CUSTOMERS-jdbc",
        "auto.create": "true",
        "auto.evolve":"true",
        "table.name.format":"customers"
    }'
```

```
[2020-06-15 10:39:03,291] INFO [sink-postgres-dbz-00|task-0] Creating table with sql: CREATE TABLE "customers" (
"ID" BIGINT NOT NULL,
"FIRST_NAME" TEXT NULL,
"LAST_NAME" TEXT NULL,
"EMAIL" TEXT NULL,
"GENDER" TEXT NULL,
"CLUB_STATUS" TEXT NULL,
"COMMENTS" TEXT NULL,
"CREATE_TS" TIMESTAMP NULL,
"UPDATE_TS" TIMESTAMP NULL,
"messagetopic" TEXT NULL,
"messagesource" TEXT NULL) (io.confluent.connect.jdbc.sink.DbStructure:92)
[2020-06-15 10:39:03,303] INFO [sink-postgres-dbz-00|task-0] Checking PostgreSql dialect for existence of table "customers" (io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialect:536)
[2020-06-15 10:39:03,308] INFO [sink-postgres-dbz-00|task-0] Using PostgreSql dialect table "customers" present (io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialect:544)
[2020-06-15 10:39:03,321] INFO [sink-postgres-dbz-00|task-0] Setting metadata for table "customers" to Table{name='"customers"', columns=[Column{'CREATE_TS', isPrimaryKey=false, allowsNull=true, sqlType=timestamp}, Column{'GENDER', isPrimaryKey=false, allowsNull=true, sqlType=text}, Column{'ID', isPrimaryKey=false, allowsNull=false, sqlType=int8}, Column{'LAST_NAME', isPrimaryKey=false, allowsNull=true, sqlType=text}, Column{'EMAIL', isPrimaryKey=false, allowsNull=true, sqlType=text}, Column{'CLUB_STATUS', isPrimaryKey=false, allowsNull=true, sqlType=text}, Column{'messagesource', isPrimaryKey=false, allowsNull=true, sqlType=text}, Column{'messagetopic', isPrimaryKey=false, allowsNull=true, sqlType=text}, Column{'COMMENTS', isPrimaryKey=false, allowsNull=true, sqlType=text}, Column{'FIRST_NAME', isPrimaryKey=false, allowsNull=true, sqlType=text}, Column{'UPDATE_TS', isPrimaryKey=false, allowsNull=true, sqlType=timestamp}]} (io.confluent.connect.jdbc.util.TableDefinitions:64)
```

## pk.mode=record_value

If I set ID as primary key and the table is created with each column `NOT NULL`: 

```
curl -X PUT http://localhost:8083/connectors/sink-postgres-dbz-00/config \
    -H "Content-Type: application/json" \
    -d '{
        "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
        "key.converter": "io.confluent.connect.avro.AvroConverter",
        "key.converter.schema.registry.url": "http://schema-registry:8081",
        "connection.url": "jdbc:postgresql://postgres:5432/",
        "connection.user": "postgres",
        "connection.password": "postgres",
        "tasks.max": "1",
        "topics": "ora-CUSTOMERS-jdbc",
        "auto.create": "true",
        "auto.evolve":"true",
        "pk.mode":"record_value",
        "pk.field":"ID",
        "insert.mode": "upsert",
        "table.name.format":"customers"
    }'
```

```
[2020-06-15 10:42:40,048] INFO [sink-postgres-dbz-01|task-0] Creating table with sql: CREATE TABLE "customers01" (                                                                       "ID" BIGINT NOT NULL,
"FIRST_NAME" TEXT NOT NULL,
"LAST_NAME" TEXT NOT NULL,
"EMAIL" TEXT NOT NULL,
"GENDER" TEXT NOT NULL,
"CLUB_STATUS" TEXT NOT NULL,
"COMMENTS" TEXT NOT NULL,                                                                                                                                                                "CREATE_TS" TIMESTAMP NOT NULL,
"UPDATE_TS" TIMESTAMP NOT NULL,                                                                                                                                                          "messagetopic" TEXT NOT NULL,                                                                                                                                                            "messagesource" TEXT NOT NULL,                                                                                                                                                           PRIMARY KEY("ID","FIRST_NAME","LAST_NAME","EMAIL","GENDER","CLUB_STATUS","COMMENTS","CREATE_TS","UPDATE_TS","messagetopic","messagesource")) (io.confluent.connect.jdbc.sink.DbStructure:
92)                                                                                                                                                                                      [2020-06-15 10:42:40,062] INFO [sink-postgres-dbz-01|task-0] Checking PostgreSql dialect for existence of table "customers01" (io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialec
t:536)
[2020-06-15 10:42:40,066] INFO [sink-postgres-dbz-01|task-0] Using PostgreSql dialect table "customers01" present (io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialect:544)      [2020-06-15 10:42:40,076] INFO [sink-postgres-dbz-01|task-0] Setting metadata for table "customers01" to Table{name='"customers01"', columns=[Column{'ID', isPrimaryKey=true, allowsNull=
false, sqlType=int8}, Column{'LAST_NAME', isPrimaryKey=true, allowsNull=false, sqlType=text}, Column{'UPDATE_TS', isPrimaryKey=true, allowsNull=false, sqlType=timestamp}, Column{'messag
etopic', isPrimaryKey=true, allowsNull=false, sqlType=text}, Column{'messagesource', isPrimaryKey=true, allowsNull=false, sqlType=text}, Column{'EMAIL', isPrimaryKey=true, allowsNull=false, sqlType=text}, Column{'CREATE_TS', isPrimaryKey=true, allowsNull=false, sqlType=timestamp}, Column{'COMMENTS', isPrimaryKey=true, allowsNull=false, sqlType=text}, Column{'FIRST_NAM
E', isPrimaryKey=true, allowsNull=false, sqlType=text}, Column{'GENDER', isPrimaryKey=true, allowsNull=false, sqlType=text}, Column{'CLUB_STATUS', isPrimaryKey=true, allowsNull=false, s
qlType=text}]} (io.confluent.connect.jdbc.util.TableDefinitions:64)
```

This then causes the sink to fail because some of the fields do not have a value: 

```
[2020-06-15 10:42:40,082] WARN [sink-postgres-dbz-01|task-0] Write of 11 records failed, remainingRetries=10 (io.confluent.connect.jdbc.sink.JdbcSinkTask:76)
java.sql.BatchUpdateException: Batch entry 10 INSERT INTO "customers01" ("ID","FIRST_NAME","LAST_NAME","EMAIL","GENDER","CLUB_STATUS","COMMENTS","CREATE_TS","UPDATE_TS","messagetopic","
messagesource") VALUES (42,'Rick','Astley',NULL,NULL,'Bronze',NULL,'2020-06-15 10:20:32.135+00','2020-06-15 10:20:32+00','ora-CUSTOMERS-jdbc','JDBC Source Connector from Oracle on asgar
d') ON CONFLICT ("ID","FIRST_NAME","LAST_NAME","EMAIL","GENDER","CLUB_STATUS","COMMENTS","CREATE_TS","UPDATE_TS","messagetopic","messagesource") DO NOTHING was aborted: ERROR: null valu
e in column "EMAIL" violates not-null constraint
  Detail: Failing row contains (42, Rick, Astley, null, null, Bronze, null, 2020-06-15 10:20:32.135, 2020-06-15 10:20:32, ora-CUSTOMERS-jdbc, JDBC Source Connector from Oracle on asgard
).  Call getNextException to see other errors in the batch.
        at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:153)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2246)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:509)
        at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:850)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:873)                                                                                                                    at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1569)
```

## Source Avro schema

```json
{
  "type": "record",
  "name": "CUSTOMERS",
  "fields": [
    {
      "name": "ID",
      "type": "long"
    },
    {
      "name": "FIRST_NAME",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "LAST_NAME",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "EMAIL",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "GENDER",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "CLUB_STATUS",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "COMMENTS",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "CREATE_TS",
      "type": [
        "null",
        {
          "type": "long",
          "connect.version": 1,
          "connect.name": "org.apache.kafka.connect.data.Timestamp",
          "logicalType": "timestamp-millis"
        }
      ],
      "default": null
    },
    {
      "name": "UPDATE_TS",
      "type": [
        "null",
        {
          "type": "long",
          "connect.version": 1,
          "connect.name": "org.apache.kafka.connect.data.Timestamp",
          "logicalType": "timestamp-millis"
        }
      ],
      "default": null
    },
    {
      "name": "messagetopic",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "messagesource",
      "type": [
        "null",
        "string"
      ],
      "default": null
    }
  ],
  "connect.name": "CUSTOMERS"
}
```

**Comment by rmoff** [comment]
Tiniest of typos has a big effect…

        "pk.fields":"ID",

vs

        "pk.field":"ID",
