### ISSUE TITLE
Table full.test.ccc-smt is missing and auto-creation is disabled

### ISSUE THREAD

**Issue by shenzgang** [confluentinc/kafka-connect-jdbc#897]
I set the auto-creation property to false in the configuration and I had created the table in the mysql database, but there would still be this exception：
[2020-08-05 01:07:57,127] ERROR WorkerSinkTask{id=mdm-sink-connector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:557)
org.apache.kafka.connect.errors.ConnectException: Table full.test.ccc-smt is missing and auto-creation is disabled
	at io.confluent.connect.jdbc.sink.DbStructure.create(DbStructure.java:87)
	at io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:63)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:78)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:69)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:70)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:537)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:315)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:218)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:186)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
my table name contains the special character ". ", which I think is the reason for the exception. But I still think it's a drawback！
I tried to modify the source code which has been resolved as follows：
try (ResultSet rs = meta.getTables(catalog, schema, "%", new String[]{"TABLE"})) {
      boolean exists = false;
      while (rs.next()){
        String TABLE_NAME = rs.getString("TABLE_NAME");
        if (tableName.equals(TABLE_NAME)) { exists = true; }
      }
      log.info(
              "product:{} schema:{} catalog:{} -- table:{} is {}",
              product,
              schema,
              catalog,
              tableName,
              exists ? "present" : "absent"
      );
      return exists;
    }

**Comment by shenzgang** [comment]
> I set the auto-creation property to false in the configuration and I had created the table in the mysql database, but there would still be this exception：
> [2020-08-05 01:07:57,127] ERROR WorkerSinkTask{id=mdm-sink-connector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:557)
> org.apache.kafka.connect.errors.ConnectException: Table full.test.ccc-smt is missing and auto-creation is disabled
> at io.confluent.connect.jdbc.sink.DbStructure.create(DbStructure.java:87)
> at io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:63)
> at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:78)
> at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:69)
> at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:70)
> at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:537)
> at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:315)
> at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:218)
> at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:186)
> at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
> at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> my table name contains the special character ". ", which I think is the reason for the exception. But I still think it's a drawback！
> I tried to modify the source code which has been resolved as follows：
> try (ResultSet rs = meta.getTables(catalog, schema, "%", new String[]{"TABLE"})) {
> boolean exists = false;
> while (rs.next()){
> String TABLE_NAME = rs.getString("TABLE_NAME");
> if (tableName.equals(TABLE_NAME)) { exists = true; }
> }
> log.info(
> "product:{} schema:{} catalog:{} -- table:{} is {}",
> product,
> schema,
> catalog,
> tableName,
> exists ? "present" : "absent"
> );
> return exists;
> }
