### ISSUE TITLE
JDBC Sink: JsonConverter with schemas.enable requires "schema" and "payload" fields

### ISSUE THREAD

**Issue by sayjavajava** [confluentinc/kafka-connect-jdbc#903]
I am getting following exception 

```
 ERROR Plugin class loader for connector: 'io.confluent.connect.jdbc.JdbcSinkConnector' was not found. Returning: org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader@1af146 (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
[2020-08-16 21:22:06,850] ERROR WorkerSinkTask{id=sink-postgres-test21-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:488)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:465)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: JsonConverter with schemas.enable requires "schema" and "payload" fields and may not contain additional fields. If you are trying to deserialize plain JSON data, set schemas.enable=false in your converter configuration.
        at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:359)
        at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:86)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$2(WorkerSinkTask.java:488)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
```

**following config i am using** 

```
{
    "name":"sink-postgres-test21",
     "config":{
         
         "connector.class":"io.confluent.connect.jdbc.JdbcSinkConnector",
          "tasks.max":"1",
          "key.converter":"org.apache.kafka.connect.storage.StringConverter",
"value.converter":"org.apache.kafka.connect.json.JsonConverter",
"key.converter.schemas.enable":true,
"value.converter.schemas.enable":true,
          "connection.url":"jdbc:postgresql://localhost:5432/testconnect",
          "connection.user":"user",
          "connection.password":"user",
          "topics": "visa-application",
          "auto.create":"true" ,
          "auto.evolve":"true",
          "insert.mode":"insert",
          "pk.mode":"kafka",
          "pk.fields":"__connect_topic,__connect_partition,__connect_offset",
          "fields.whitelist":"id,channel,appType"
     }
}
```

Note: jdbc connect version : kafka-connect-jdbc-5.4.1

Thanks in advance

**Comment by NiramayVaidya** [comment]
Try setting both key.converter.schemas.enable and value.converter.schemas.enable to false.
