### ISSUE TITLE
Can we connect to Google Big query ?

### ISSUE THREAD

**Issue by akhileshacc** [confluentinc/kafka-connect-jdbc#913]
Hi, 

I am building source connector for google big query. I used "Simba" jdbc driver to build connection and it worked fine. I could fetch table when trying on simple java file.

But when I used it with kafka connector. Connection worked, but nothing is being fetched.

Is JDBC connector restricted to certain database only ?

**Comment by akhileshacc** [comment]
My config is
```
curl -X POST http://localhost:8083/connectors \
	-H "Content-Type: application/json" \
	-d '{
    "name": "bq-source1",
    "config": {
        "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
        "topic.prefix": "db-bq",
        "tasks.max": "1",
        "table.whitelist": "persons1",        
        "mode": "bulk",
        "connection.url": "jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId=connector-test-281616;OAuthType=0;OAuthServiceAcctEmail=kafka-865@connector-test-281616.iam.gserviceaccount.com;OAuthPvtKeyPath=/tmp/data/bigquery/bq-xx.json;Dataset=kafkaconnectdb",
        }
    }'
```

**Comment by akhileshacc** [comment]
These are the error logs

```
[2020-09-02 10:23:56,744] INFO Starting JDBC source task (io.confluent.connect.jdbc.source.JdbcSourceTask:81)
[2020-09-02 10:23:56,748] INFO JdbcSourceTaskConfig values: 
        batch.max.rows = 100
        catalog.pattern = null
        connection.attempts = 3
        connection.backoff.ms = 10000
        connection.password = null
        connection.url = jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId=connector-test-281616;OAuthType=0;OAuthServiceAcctEmail=kafka-865@connector-test-281616.iam.gserviceaccount.com;OAuthPvtKeyPath=/tmp/data/bigquery/bq-xx.json;DefaultDataset=kafkaconnectdb;
        connection.user = null
        db.timezone = UTC
        dialect.name = 
        incrementing.column.name = id
        mode = incrementing
        numeric.mapping = null
        numeric.precision.mapping = false
        poll.interval.ms = 5000
        query = 
        query.suffix = 
        quote.sql.identifiers = ALWAYS
        schema.pattern = null
        table.blacklist = []
        table.poll.interval.ms = 60000
        table.types = [TABLE]
        table.whitelist = [persons1]
        tables = [`connector-test-281616`.`kafkaconnectdb`.`persons1`]
        timestamp.column.name = []
        timestamp.delay.interval.ms = 0
        timestamp.initial = null
        topic.prefix = db-bq
        validate.non.null = true
 (io.confluent.connect.jdbc.source.JdbcSourceTaskConfig:347)
[2020-09-02 10:23:56,750] INFO Using JDBC dialect Generic (io.confluent.connect.jdbc.source.JdbcSourceTask:98)
[2020-09-02 10:23:56,831] INFO [Producer clientId=connector-producer-bq-source1-0] Cluster ID: p07hkCRAR0K-2YNz3brmBg (org.apache.kafka.clients.Metadata:261)
[2020-09-02 10:23:57,387] INFO Attempting to open connection #1 to Generic (io.confluent.connect.jdbc.util.CachedConnectionProvider:92)
[2020-09-02 10:23:58,050] INFO Unable to connect to database on attempt 1/3. Will retry in 10000 ms. (io.confluent.connect.jdbc.util.CachedConnectionProvider:99)
java.sql.SQLFeatureNotSupportedException: [Simba][JDBC](10220) Driver does not support this optional feature.
        at com.simba.googlebigquery.exceptions.ExceptionConverter.toSQLException(Unknown Source)
        at com.simba.googlebigquery.jdbc.common.SConnection.setAutoCommit(Unknown Source)
        at io.confluent.connect.jdbc.source.JdbcSourceTask$1.onConnect(JdbcSourceTask.java:265)
        at io.confluent.connect.jdbc.util.CachedConnectionProvider.newConnection(CachedConnectionProvider.java:94)
        at io.confluent.connect.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:62)
        at io.confluent.connect.jdbc.source.JdbcSourceTask.validateNonNullable(JdbcSourceTask.java:428)
        at io.confluent.connect.jdbc.source.JdbcSourceTask.start(JdbcSourceTask.java:161)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:208)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by akhileshacc** [comment]
When i give incorrent table name, it doesnt show connection error and just says
```
- [2020-09-02 10:22:52,557] WARN No tasks will be run because no tables were found (io.confluent.connect.jdbc.JdbcSourceConnector:150)
            
```

**Comment by OneCricketeer** [comment]
Not clear why you want to use this connector

https://docs.confluent.io/current/connect/kafka-connect-bigquery/index.html

**Comment by akhileshacc** [comment]
Just wanted to do everything with JDBC.

Thanks for the help, will use that one.

**Comment by akhileshacc** [comment]
For sink native one works. For source connector how do i go about using JDBC. Above errors came while trying source connectors.

**Comment by OneCricketeer** [comment]
setAutoCommit is not supported by your driver, which would be needed by a source

**Comment by akhileshacc** [comment]
Thanks for help.

**Comment by Munaf305** [comment]
Looking for setting up to connect BigQuery using JDBC. is there a still restriction in 2023 to connect BIGQUERY using JDBC connector

**Comment by OneCricketeer** [comment]
> Any alternatives is highly appreciated

@Munaf305 As linked above, there is a specific BigQuery Connector (which I believe does not use JDBC, but rather a direct client API)

**Comment by Munaf305** [comment]
@OneCricketeer : That the sink connector not the source connector.For source connector does jdbc support connecting to kafka to bigquery?

**Comment by OneCricketeer** [comment]
@Munaf305 Apologies, you did not clarify source/sink initially. 

The [dialects package](https://github.com/confluentinc/kafka-connect-jdbc/tree/master/src/main/java/io/confluent/connect/jdbc/dialect) lists out the officially supported databases. If yours is not there, then the generic dialect will be used, which may not work for the database you are trying to connect with.
