### ISSUE TITLE
Support for clickhouse in confluent 

### ISSUE THREAD

**Issue by shivakumarss** [confluentinc/kafka-connect-jdbc#923]
I am trying JdbcSinkConnector to dump the data from kafka topic to clickhouse. 

following are the things done :

1. Downloaded clickhouse-jdbc-0.2.4-shaded.jar and put in the classpath of connnector.
   https://repo1.maven.org/maven2/ru/yandex/clickhouse/clickhouse-jdbc/0.2.4/clickhouse-jdbc-0.2.4-shaded.jar ( 5.7 mb ) 
2. Used the following command in the ksql terminal to create connector.
```
    CREATE SINK CONNECTOR "jdbcYesWinCH15" WITH (
        'connector.class'     = 'io.confluent.connect.jdbc.JdbcSinkConnector',
        'key.converter'       = 'org.apache.kafka.connect.storage.StringConverter',
        'connection.url'      = 'jdbc:clickhouse://xxx:8123/logs',
        'connection.user'     = 'user',
        'errors.retry.timeout'= '100',
        'errors.retry.delay.max.ms' = '60000',
        'connection.password' = 'password',
        'topics'              = 'mytopic',
        'auto.create'         = 'true',
        'auto.evolve'         = 'true',
        'schemas.enable' = 'false',
        'db.timezone'         = 'UTC',
        'batch.size'          = '500', 
        'insert.mode'         = 'upsert',   
        'pk.mode'             = 'record_key',
        'pk.fields'           = 'key',
        'table.name.format'   = 'table_name'
    );
```
3. My kafka topic has very basic field, here is the schema for the same  
```
{
  "doc": "Schema  ",
  "fields": [
    {
      "name": "requestid",
      "type": "string"
    },
    {
      "name": "click",
      "type": "int"
    },
    {
      "name": "click_meta",
      "type": "string"
    }
  ],
  "name": "value_co_conf_one",
  "namespace": "com.mycompany.kafka.schema.co.conf.one",
  "type": "record"
}
```

4. I see following error message in the connector.log 

```logs
[2020-09-21 18:33:53,926] INFO [Consumer clientId=connector-consumer-jdbcYesWinCH15-0, groupId=connect-jdbcYesWinCH15] Resetting offset for partition coconfone-0 to offset 28669. (org.apache.kafka.clients.consumer.internals.SubscriptionState:397)
[2020-09-21 18:33:55,624] INFO Attempting to open connection #1 to Generic (io.confluent.connect.jdbc.util.CachedConnectionProvider:92)
[2020-09-21 18:33:56,392] INFO JdbcDbWriter Connected (io.confluent.connect.jdbc.sink.JdbcDbWriter:49)
[2020-09-21 18:33:56,908] INFO Checking Generic dialect for existence of TABLE "coconfone_ch" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:548)
[2020-09-21 18:33:57,164] INFO Using Generic dialect TABLE "coconfone_ch" absent (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:556)
[2020-09-21 18:33:57,165] ERROR WorkerSinkTask{id=jdbcYesWinCH15-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: null (STRING) type doesn't have a mapping to the SQL database column type (org.apache.kafka.connect.runtime.WorkerSinkTask:565)
org.apache.kafka.connect.errors.ConnectException: null (STRING) type doesn't have a mapping to the SQL database column type
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.getSqlType(GenericDatabaseDialect.java:1818)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.writeColumnSpec(GenericDatabaseDialect.java:1734)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.lambda$writeColumnsSpec$33(GenericDatabaseDialect.java:1723)
	at io.confluent.connect.jdbc.util.ExpressionBuilder.append(ExpressionBuilder.java:558)
	at io.confluent.connect.jdbc.util.ExpressionBuilder$BasicListBuilder.of(ExpressionBuilder.java:597)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.writeColumnsSpec(GenericDatabaseDialect.java:1725)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.buildCreateTableStatement(GenericDatabaseDialect.java:1648)
	at io.confluent.connect.jdbc.sink.DbStructure.create(DbStructure.java:92)
	at io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:62)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:123)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:66)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:545)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:325)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:228)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:200)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-09-21 18:33:57,166] ERROR WorkerSinkTask{id=jdbcYesWinCH15-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:186)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:567)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:325)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:228)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:200)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.ConnectException: null (STRING) type doesn't have a mapping to the SQL database column type
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.getSqlType(GenericDatabaseDialect.java:1818)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.writeColumnSpec(GenericDatabaseDialect.java:1734)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.lambda$writeColumnsSpec$33(GenericDatabaseDialect.java:1723)
	at io.confluent.connect.jdbc.util.ExpressionBuilder.append(ExpressionBuilder.java:558)
	at io.confluent.connect.jdbc.util.ExpressionBuilder$BasicListBuilder.of(ExpressionBuilder.java:597)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.writeColumnsSpec(GenericDatabaseDialect.java:1725)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.buildCreateTableStatement(GenericDatabaseDialect.java:1648)
	at io.confluent.connect.jdbc.sink.DbStructure.create(DbStructure.java:92)
	at io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:62)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:123)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:66)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:545)
	... 10 more
[2020-09-21 18:33:57,166] ERROR WorkerSinkTask{id=jdbcYesWinCH15-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:187)
[2020-09-21 18:33:57,166] INFO Stopping task (io.confluent.connect.jdbc.sink.JdbcSinkTask:107)
[2020-09-21 18:33:57,166] INFO Closing connection #1 to Generic (io.confluent.connect.jdbc.util.CachedConnectionProvider:118)
[2020-09-21 18:33:57,167] INFO [Consumer clientId=connector-consumer-jdbcYesWinCH15-0, groupId=connect-jdbcYesWinCH15] Revoke previously assigned partitions coconfone-0 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:292)
[2020-09-21 18:33:57,167] INFO [Consumer clientId=connector-consumer-jdbcYesWinCH15-0, groupId=connect-jdbcYesWinCH15] Member connector-consumer-jdbcYesWinCH15-0-5f2279c1-1e38-415a-bc17-5971decca63e sending LeaveGroup request to coordinator xxx.gcp.confluent.cloud:9092 (id: 2147483644 rack: null) due to the consumer is being closed (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:979)
```

4. Is it something to do with `dialect.name` https://docs.confluent.io/current/connect/kafka-connect-jdbc/sink-connector/sink_config_options.html#connection because i dont see clickhouse specific dialect, and in logs it is GenericDatabaseDialect.

let me know how do i go about it. 

Thanks.

**Comment by Belorus** [comment]
Same problem here.

**Comment by Sam--Shan** [comment]
@Belorus @shivakumarss hey guys,did you solve your problems?i think some properties must be limited,like
auto.create=false
auto.evolve=false
insert.mode=insert

Did you find  any other kafka's connector support clickhouse better?

**Comment by alex88** [comment]
If you disable create/evolve clickhouse works fine, it's still missing support for some columns like MAP ones
