### ISSUE TITLE
Can't query postgresql source via jdbc source connector

### ISSUE THREAD

**Issue by bangau1** [confluentinc/kafka-connect-jdbc#974]
Hi,

I setup source connector with this configuration:
```json
{
  "name": "source_postgresql",
  "config": {
      "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
      "connection.url": "jdbc:postgresql://source:5432/postgres",
      "connection.user": "postgres",
      "connection.password": "postgres",
      "topic.prefix": "prefix_incrementing_",
      "poll.interval.ms" : 1000,
      "table.whitelist": "users",
      "schema.pattern": "public",
      "mode":"incrementing",
      "incrementing.column.name": "timestamp",
      "db.timezone": "UTC"
  }
}

```

And here is the postgresql table schema
```sql
create table IF NOT EXISTS public.users(
  id int PRIMARY KEY, 
  name varchar(15), 
  address varchar(15), 
  timestamp timestamp with time zone default current_timestamp NOT NULL
);

CREATE INDEX users_timestamp on public.users(timestamp ASC);
```

Upon checking my postgresql (version 12), it has timezone set to `UTC`, so I set the jdbc source connector `db.timezone` to `UTC` as well.

I got this error
```
ERROR Failed to run query for table TimestampIncrementingTableQuerier{table="public"."users", query='null', topicPrefix='prefix_incrementing_', incrementingColumn='timestamp', timestampColumns=[]}: {} (io.confluent.connect.jdbc.source.JdbcSourceTask)
connect           | org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp with time zone > bigint
connect           |   Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
connect           |   Position: 67
connect           |     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2510)
connect           |     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2245)
connect           |     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:311)
connect           |     at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
connect           |     at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
connect           |     at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
connect           |     at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:109)
connect           |     at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.executeQuery(TimestampIncrementingTableQuerier.java:200)
connect           |     at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.maybeStartQuery(TimestampIncrementingTableQuerier.java:159)
connect           |     at io.confluent.connect.jdbc.source.JdbcSourceTask.poll(JdbcSourceTask.java:371)
connect           |     at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:289)
connect           |     at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:256)
connect           |     at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
connect           |     at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
connect           |     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
connect           |     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
connect           |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
connect           |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
connect           |     at java.base/java.lang.Thread.run(Thread.java:834)
```

Any advice?

**Comment by agung-kargo** [comment]
Turns out there is misconfiguration in my connector. 
Should be
```
"mode":"incrementing",
"incrementing.column.name": "id",
```
